jenkinsci/acceptance-test-harness

src/test/java/plugins/CompressArtifactsPluginTest.java

[JENKINS-27042](https://issues.jenkins-ci.org/browse/JENKINS-27042)

Reproduce JENKINS-27042

---

src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsLogWatcher.java

More conservative JenkinsLogWatcher

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer.java
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile
src/test/java/plugins/XvncPluginTest.java

@reviewbybees and @olivergondza

Xvnc tests

---

src/test/java/plugins/WorkflowPluginTest.java

Shows how to strengthen a test when https://github.com/jenkinsci/script-security-plugin/pull/21 is available. This would be useful for verifying a proposed change in https://github.com/jenkinsci/parallel-test-executor-plugin/pull/14.
@reviewbybees

Prepare for whitelisted compareLessThan

---

src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackCloud.java
src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackSlaveTemplate.java
src/test/java/plugins/OpenstackCloudPluginTest.java
src/test/resources/openstack_plugin/cloud-init-jnlp

To be merged after https://github.com/jenkinsci/acceptance-test-harness/pull/32

Cover OpenStack provisioning

---

src/main/java/org/jenkinsci/test/acceptance/plugins/analysis_collector/AnalysisCollectorPluginArea.java

Fix ids modification coming from https://github.com/jenkinsci/analysis-collector-plugin/pull/2
Related to [JENKINS-30125](https://issues.jenkins-ci.org/browse/JENKINS-30125)

[JENKINS-30125] Fix properties IDs on Analysis Collector Plugin

---

src/main/java/org/jenkinsci/test/acceptance/plugins/gerrit_trigger/GerritTriggerJob.java
src/main/java/org/jenkinsci/test/acceptance/plugins/gerrit_trigger/GerritTriggerServer.java
src/test/java/plugins/GerritTriggerTest.java

1. Trigger on Ref Updated event
2. Trigger on Comment Added event
3. Trigger on Draft Published event
4. Trigger on Change Merged event

Add 4 test cases for Gerrit Trigger plugin

---

README.md
pom.xml
src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
src/main/java/org/jenkinsci/test/acceptance/recorder/JUnitScreenRecorder.java
src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
src/main/java/org/jenkinsci/test/acceptance/utils/SystemEnvironmentVariables.java
src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java

adds screen recorder capabilities.

---

src/test/java/plugins/WorkflowPluginTest.java

On hold until https://github.com/jenkinsci/workflow-plugin/pull/186 is merged and released.
@reviewbybees

[JENKINS-26942] Update acceptance test to use stashes

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
src/test/java/plugins/AnalysisCollectorPluginTest.java

Inspired by the hidden problem found in [JENKINS-30390](https://issues.jenkins-ci.org/browse/JENKINS-30390).
@reviewbybees

[JENKINS-30390] Workflow job using Analysis Collector

---

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
src/test/java/plugins/DiskUsagePluginTest.java

[JENKINS-30971](https://issues.jenkins-ci.org/browse/JENKINS-30971)
@reviewbybees

[FIXED JENKINS-30971] Refresh page after restart failure

---

src/main/java/org/jenkinsci/test/acceptance/po/FolderItem.java
src/main/java/org/jenkinsci/test/acceptance/po/FolderJob.java
src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
src/test/java/plugins/FolderPluginTest.java

[JENKINS-31648] (https://issues.jenkins-ci.org/browse/JENKINS-31648)
A simple first scenario to start incorporating folder-related tests to the ATH. A `FolderJob` is introduced as part of the process.
@reviewbybees

[JENKINS-31648] First acceptance test for Folder plugin.

---

src/main/java/org/jenkinsci/test/acceptance/po/FolderItem.java
src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
src/test/java/plugins/FolderPluginTest.java

[JENKINS-31698](https://issues.jenkins-ci.org/browse/JENKINS-31698)
Goals:
* Providing a mechanism to create jobs inside folders (including other folders).
* Review TopLevelItem equality contract in the presence of hierarchy.
* Create a simple test scenario involving a folder hierarchy.
@reviewbybees

[JENKINS-31698] Add support for folder hierarchies in ATH

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/main/java/org/jenkinsci/test/acceptance/steps/JobConfigurationSteps.java

Fixes some test failures caused by https://github.com/jenkinsci/jenkins/pull/1888 and https://github.com/jenkinsci/jenkins/pull/1889.
@reviewbybees & @olivergondza

OptionalJobProperty updates

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java

Follow-up to #61. Tested against `JobParameterSummaryPluginTest` and `TriggerRemoteBuildsTest` in trunk & LTS.
@reviewbybees, @olivergondza

OptionalJobProperty updates cont’d

---

src/test/java/plugins/WarningsPluginTest.java

@uhafner, I presume this was change in the plugin itself.

Fix Warnings test

---

src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java

TestRecorder fails in headless mode.

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java
src/test/java/org/jenkinsci/test/acceptance/docker/DockerImageTest.java

Add `DOCKER_HOST` ip resolution.
@reviewbybees

[JENKINS-33107]  Docker Fixtures might fail using Docker-Machine

---

src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java

Fixing WorkflowPluginTest for 1.14

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/LdapContainer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ldap/LdapDetails.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ldap/LdapEnvironmentVariable.java
src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm.java
src/main/java/org/jenkinsci/test/acceptance/po/User.java
src/test/java/plugins/LdapPluginTest.java

Increate test coverage for the LDAP plugin.
* Add support for adding environment variables in tests.
* Fix minor issues when selecting cache options
* Add more tests to increase coverage
@reviewbybees

[JENKINS-33292] More test cases for LDAP plugin

---

src/main/groovy/org/jenkinsci/test/acceptance/po/GlobalToolConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ant/AntInstallation.java
src/main/java/org/jenkinsci/test/acceptance/plugins/gradle/GradleInstallation.java
src/main/java/org/jenkinsci/test/acceptance/plugins/groovy/GroovyInstallation.java
src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenInstallation.java
src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
src/test/java/core/JdkTest.java
src/test/java/plugins/AntPluginTest.java
src/test/java/plugins/GradlePluginTest.java
src/test/java/plugins/GroovyPluginTest.java
src/test/java/plugins/MavenPluginTest.java

@tfennelly, it is still a work in progress

Abstract away the fact tools config page was moved away from global config

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaContainer/Dockerfile
src/test/java/plugins/SshSlavesPluginTest.java

Adding more test cases for SSH Slaves Plugin.
@reviewbybees

[JENKINS-33741] [SSH Slaves Plugin] Improve test coverage 

---

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
src/main/resources/org/jenkinsci/test/acceptance/selenium/scroller.js

Attn @olivergondza These should fix the scrolling issues + the missing plugin deps. I'm doing another local run of the tests here, so hopefully we are getting closer.
The original `scroller.js` just did not work as it was. `scrollIntoView` does not seem to be reliable (nor does `scrollBy`).

[JENKINS-33730] More ATH tweaks for Jenkins 2.0

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/BaseStandardCredentials.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Domain.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java
src/test/java/core/CredentialsTest.java

Improve ATH test coverage for Credentials Plugin
@reviewbybees

[JENKINS-33994] Improve ATH test coverage for Credentials Plugin

---

src/main/java/org/jenkinsci/test/acceptance/plugins/gerrit_trigger/GerritTriggerNewServer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/jclouds/JCloudsSlaveTemplate.java
src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackCloud.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java

- Prefer elastic waits
- Refactor some explicit waiting loops to use selenium API.

Fix element waits

---

src/main/java/org/jenkinsci/test/acceptance/plugins/groovy_postbuild/GroovyPostBuildStep.java
src/main/java/org/jenkinsci/test/acceptance/plugins/script_security/PendingSignature.java
src/main/java/org/jenkinsci/test/acceptance/plugins/script_security/ScriptApproval.java
src/test/java/plugins/ScriptSecurityPluginTest.java

See [JENKINS-34285](https://issues.jenkins-ci.org/browse/JENKINS-34285)
@reviewbybees

[JENKINS-34285] Script and signature approval tests.

---

src/test/java/plugins/MultipleScmsPluginTest.java

MultipleScmsPluginTest still referred to svn.jenkins-ci.org. Fixed.

---

src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java

* Fix timeout figure.
* Support old editor `id`.

Fix ACE editor detection in workflow projects.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/mstestrunner/MSTestRunnerBuildStep.java

To encourage the implementation of tests for this plugin.
@reviewbybees

PageObject for MsTestRunner build step

---

src/test/java/plugins/JUnitPluginTest.java

Fix toggle in JUnit build results.

---

src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
src/main/resources/org/jenkinsci/test/acceptance/selenium/overflow.js
src/main/resources/org/jenkinsci/test/acceptance/selenium/scroller.js
src/test/java/plugins/MatrixAuthPluginTest.java

See [JENKINS-34411](https://issues.jenkins-ci.org/browse/JENKINS-34411).
@reviewbybees (esp. @tfennelly and @recena )

[JENKINS-34411] Horizontal scrolling and scrolling overflows

---

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile

JIRA image now needs JDK8.

---

src/test/java/plugins/NodeLabelParameterPluginTest.java

- It seems like with the release of 1.7+, two tests no longer work
- By ensuring that we use newly created slaves for testing, the tests pass.

Fix NodeLabelParameter tests

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/SshKeyPair.java
src/main/java/org/jenkinsci/test/acceptance/SshKeyPairGenerator.java

[JENKINS-35328](https://issues.jenkins-ci.org/browse/JENKINS-35328)
@reviewbybees

[JENKINS-35328] Bump BouncyCastle version

---

src/main/java/org/jenkinsci/test/acceptance/junit/WithCredentials.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/BaseStandardCredentials.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Domain.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/UserPwdCredential.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshPrivateKeyCredential.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/slave/SshSlaveController.java
src/test/java/core/CreateSlaveTest.java
src/test/java/core/CredentialsTest.java
src/test/resources/tasks_plugin/fileset1/TSRCreateSlaveTest.java
src/test/resources/tasks_plugin/fileset1_less/TSRCreateSlaveTest.java

Bumped the required version of the credentials plugin to 2.0.7.  Added some new classes to handle the different layout, and changed classes that were dependent on the credentials.
@reviewbybees

[JENKINS-35090] - Credentials plugin upgrade/fix

---

src/main/java/org/jenkinsci/test/acceptance/po/ArtifactManagement.java
src/test/java/plugins/CompressArtifactsPluginTest.java

[JENKINS-35703](https://issues.jenkins-ci.org/browse/JENKINS-35703)
@reviewbybees esp @armfergom, @olivergondza

[JENKINS-35703] Fix test 'CompressArtifactsPluginTest#archiveLargerThan4GInTotal

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java

https://issues.jenkins-ci.org/browse/JENKINS-36048
The lack of ids on the relevant `<span>` means I had to use a fairly demented xpath to find it. Buuuuut now it works!
cc @reviewbybees esp @stephenc @kwhetstone

[FIXED JENKINS-36048] Properly choose a credentials provider when appropriate

---

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshdContainer/Dockerfile

Adding the additional KexAlgorithms and MACs gets past an error with
protocol negotiation in some environments.

Jsch had issues connecting in some cases - fix sshd_config

---

src/main/java/org/jenkinsci/test/acceptance/po/FreeStyleMultiBranchJob.java
src/main/java/org/jenkinsci/test/acceptance/po/View.java

[JENKINS-31047](https://issues.jenkins-ci.org/browse/JENKINS-31047)
@reviewbybees

[JENKINS-31047] Incorrect Behaviour on WarningsPluginTest

---

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java

Fix for [JENKINS-36036](https://issues.jenkins-ci.org/browse/JENKINS-36036)
@reviewbybees

[JENKINS-36036] Fix flaky test 'ScriptSecurityPluginTest#scriptNeedsApproval'

---

src/main/java/org/jenkinsci/test/acceptance/po/Node.java
src/main/java/org/jenkinsci/test/acceptance/po/Slave.java

[JENKINS-31738](https://issues.jenkins-ci.org/browse/JENKINS-31738) 
Downstream of #152 
@reviewbybees

[JENKINS-31738] Non-deterministic behavior in PrioritySorterPluginTest#match_jobs_by_view

---

src/test/java/plugins/AnalysisCollectorPluginTest.java

[JENKINS-34690](https://issues.jenkins-ci.org/browse/JENKINS-34690)
I suspect is some very similar to [JENKINS-31738](https://issues.jenkins-ci.org/browse/JENKINS-31738), so I used the same approach.
@reviewbybees

[JENKINS-34690] Analysis collector ATH tests failing

---

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/test/java/core/DeleteJobTest.java

[JENKINS-36818](https://issues.jenkins-ci.org/browse/JENKINS-36818) This could be useful to implement some tests

[JENKINS-36818] Add the ability to delete a project

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java

See [JENKINS-37111](https://issues.jenkins-ci.org/browse/JENKINS-37111)
@reviewbybees

[JENKINS-37111] Change update center info update

---

pom.xml
vnc.sh

Tweaks to VNC wrapper

---

src/main/java/org/jenkinsci/test/acceptance/plugins/external_workspace_manager/ExternalGlobalConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/external_workspace_manager/ExternalNodeConfig.java
src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java

Related to issue [[JENKINS-36076]](https://issues.jenkins-ci.org/browse/JENKINS-36076)
Summary of this pull request:
CC @oleg-nenashev @martinda

[JENKINS-36076] Acceptance tests for External Workspace Manager Plugin

---

src/test/java/org/jenkinsci/test/acceptance/docker/DockerImageTest.java

https://github.com/jenkinsci/acceptance-test-harness/commit/419192fff9c9c77ccab77841243b372b0ccf0fc3#diff-0e01d38750e8f41c10054e6f690694f2R22 Broke a bunch of docker tests by making ```dockerHostResolver``` static.  
This PR only modifies DockerImageTest so that it cleans ups properly after executing. The field should have never been static, however there is quite a few things depending on it now.

Fixed failing docker tests

---

src/test/java/plugins/WorkflowPluginTest.java

Was trying to reproduce [JENKINS-37538](https://issues.jenkins-ci.org/browse/JENKINS-37538) and failed. Anyway, it is useful to have a basic smoke test like this in place.
@reviewbybees

Testing Pipeline + Subversion

---

src/main/java/org/jenkinsci/test/acceptance/plugins/mailer/MailerGlobalConfig.java

Increase timeout for MailerPluginTest

---

src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java

[JENKINS-38029](https://issues.jenkins-ci.org/browse/JENKINS-38029)
@reviewbybees

[JENKINS-38029] Wait for Yes button before clicking

---

pom.xml

to avoid com.jcraft.jsch.JSchException: Algorithm negotiation fail

Upgrade to jsch 0.1.54

---

src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
src/test/java/core/CreateItemTest.java

Test case for: https://github.com/jenkinsci/jenkins/pull/2513
@jenkinsci/code-reviewers @reviewbybees

[JENKINS-37523] - wrong message displayed for duplicate item name

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java

https://issues.jenkins-ci.org/browse/JENKINS-37968

[FIXED JENKINS-37968] wait for the form to be available with a 2 sec timeout

---

src/test/java/core/JenkinsDatabaseSecurityRealmTest.java

[JENKINS-38689](https://issues.jenkins-ci.org/browse/JENKINS-38689)
Fix `JenkinsDatabaseSecurityRealmTest`
@reviewbybees

[JENKINS-38689] fix casing error

---

src/main/java/org/jenkinsci/test/acceptance/plugins/envinject/EnvInjectConfig.java

[JENKINS-38700](https://issues.jenkins-ci.org/browse/JENKINS-38700)
Fix properties path in 'EnvInjectConfig'
@reviewbybees

[JENKINS-38700] fix properties path in 'EnvInjectConfig'

---

src/main/java/org/jenkinsci/test/acceptance/po/AggregateDownstreamTestResults.java
src/main/java/org/jenkinsci/test/acceptance/po/CopyArchivedArtifactsBuildStep.java
src/main/java/org/jenkinsci/test/acceptance/po/Fingerprint.java

[JENKINS-38786](https://issues.jenkins-ci.org/browse/JENKINS-38786)
@reviewbybees

[JENKINS-38786] Missed Publishers in ATH

---

src/test/java/plugins/KerberosSsoTest.java

Tests for anonymous mode of kerberos plugin.

Add tests for anonymous kerberos mode

---

src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenBuildStep.java
src/test/java/plugins/JacocoPluginTest.java
src/test/java/plugins/MavenPluginTest.java

See [JENKINS-38936](https://issues.jenkins-ci.org/browse/JENKINS-38936)
@reviewbybees

[JENKINS-38936] Control property injection

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java

[JENKINS-38794](https://issues.jenkins-ci.org/browse/JENKINS-38794)
Make `@WithPlugins` check required version when `uploadPlugins=false`
@reviewbybees

[JENKINS-38794] make @WithPlugins check required version when 'uploadPlugins=false'

---

src/test/java/plugins/OwnershipPluginTest.java

See [JENKINS-38735](https://issues.jenkins-ci.org/browse/JENKINS-38735)
@reviewbybees

[JENKINS-38735] OwnershipPluginTest failing against for latest plugin version

---

src/test/java/core/CreateItemTest.java

Seems this test is only valid for core versions > 2.6
This poses a problem for users still on 1.651.x

Add Since for CreateItemTest

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java

Ensure that we get the element that is visible.

Make CreateSlaveTest more robust

---

single-plugin.groovy
src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java
src/main/java/org/jenkinsci/test/acceptance/steps/PluginSteps.java
src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java
src/main/java/org/jenkinsci/test/acceptance/update_center/PluginSpec.java
src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java

Ripping of the shared goods from https://github.com/jenkinsci/acceptance-test-harness/pull/207 (Rely on plugin manager instead of custom dependency resolution by default).

Reduce the number of restarts needed to install plugins

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java

[JENKINS-39354](https://issues.jenkins-ci.org/browse/JENKINS-39354)
Following up https://github.com/jenkinsci/acceptance-test-harness/pull/212
@reviewbybees and @olivergondza

[JENKINS-39354] Improve CreateSlaveTest robustness

---

src/main/java/org/jenkinsci/test/acceptance/plugins/scp/ScpGlobalConfig.java

This has come about due to the fix in PR #148

Fix SCPPluginTest

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
src/test/java/core/FreestyleJobTest.java

This test breaks without https://github.com/jenkinsci/form-element-path-plugin/pull/6

[JENKINS-38928] Add a test doing apply then save in a job

---

src/main/java/org/jenkinsci/test/acceptance/plugins/javadoc/JavadocPublisher.java
src/test/java/plugins/JavadocPluginTest.java

[JENKINS-39743](https://issues.jenkins-ci.org/browse/JENKINS-39743)
@reviewbybees

[JENKINS-39743] Create test for the javadoc retention for each build

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java

[JENKINS-39828](https://issues.jenkins-ci.org/browse/JENKINS-39828)
@reviewbybees @andresrc @olivergondza

[JENKINS-39828] Ignore test if plugin cannot be updated through the UI

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java

Reverts jenkinsci/acceptance-test-harness#225

 Revert "[JENKINS-39828] Ignore test if plugin cannot be updated through the UI"

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/BranchSource.java
src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
src/test/java/plugins/WorkflowMultibranchTest.java

- PO for Pipeline Multibranch job.
- PO for GitHub Branch Source.
[JENKINS-39930](https://issues.jenkins-ci.org/browse/JENKINS-39930)
@reviewbybees

[JENKINS-39930] Create POs for Pipeline multi branch jobs

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/ManagedCredentialsBinding.java
src/test/java/plugins/CredentialsBindingTest.java

[JENKINS-39935](https://issues.jenkins-ci.org/browse/JENKINS-39935)
@reviewbybees

[JENKINS-39935] ManagedCredentialsBinding#addCredentials is not working

---

src/main/java/org/jenkinsci/test/acceptance/update_center/LocalOverrideUpdateCenterMetadataDecoratorImpl.java
src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java

When running with `LOCAL_SNAPSHOTS=true`, a bad artifact left behind by https://github.com/jenkinsci/plugin-pom/pull/39 resulted in some perplexing errors.
@reviewbybees

Local snapshot fixes

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/ForemanContainer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/foreman_node_sharing/ForemanSharedNodeCloudPageArea.java
src/main/java/org/jenkinsci/test/acceptance/po/LabelExpressionAxis.java
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/ForemanContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/ForemanContainer/plugins/foreman_reserve.rb
src/test/java/plugins/ForemanNodeSharingPluginTest.java
src/test/resources/foreman_node_sharing_plugin/setup.sh

Plugin is not currently available update-center.
Code contribution in progress.
Please do not merge until plugin is available.

Foreman Node Sharing Plugin tests

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java

- Perform the click through an action and moving previously to the element.
- Increase the timeout to be sure we wait for enough time.
[JENKINS-39354](https://issues.jenkins-ci.org/browse/JENKINS-39354)

[JENKINS-39354] CreateSlaveTest robustness

---

src/main/java/org/jenkinsci/test/acceptance/junit/WithCredentials.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java

[JENKINS-40479](https://issues.jenkins-ci.org/browse/JENKINS-40479)
Control race condition when preparing credentials with `@WithCredentials` annotation.
@reviewbybees

[JENKINS-40479] Control rare race condition in WithCredentials annotation

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java
src/test/java/core/CredentialsTest.java

[JENKINS-40433](https://issues.jenkins-ci.org/browse/JENKINS-40433)
- Test credentials for default domain as well as custom domains.
- Test personal credentials.
@reviewbybees

[JENKINS-40433] Increase test coverage for credentials plugin

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/BranchSource.java
src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowGithubSharedLibrary.java
src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowSharedLibrary.java
src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowSharedLibraryGlobalConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
src/test/java/plugins/WorkflowPluginTest.java

[JENKINS-40567](https://issues.jenkins-ci.org/browse/JENKINS-40567)
- Create POs to configure a Pipeline Global Shared Library.
- Create test with a Pipeline which uses the Shared Library.
@reviewbybees

[JENKINS-40567] Create test for Pipeline Shared Library stored in Github

---

src/main/java/org/jenkinsci/test/acceptance/plugins/authorize_project/BuildAccessControl.java
src/main/java/org/jenkinsci/test/acceptance/plugins/authorize_project/ProjectDefaultBuildAccessControl.java
src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
src/test/java/plugins/AuthorizeProjectTest.java

[JENKINS-40502](https://issues.jenkins-ci.org/browse/JENKINS-40502)
- Create PO for Authorize project plugin.
- Make GlobalSecurity config to be able to add it.
- Create test.
@reviewbybees

[JENKINS-40502] Create PO for Authorize project plugin and a test.

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java

Fixes [JENKINS-40715](https://issues.jenkins-ci.org/browse/JENKINS-40715).
@reviewbybees

[JENKINS-40715] Fix race condition in 'UpdateCenter#waitForInstallationToComplete'

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/junit/JUnitProgressReporter.java
src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
src/test/java/core/JenkinsDatabaseSecurityRealmTest.java
src/test/java/core/PublisherOrderTest.java
src/test/java/plugins/DescriptionSetterPluginTest.java
src/test/java/plugins/KerberosSsoTest.java
src/test/java/plugins/MatrixReloadedPluginTest.java
src/test/java/plugins/PlotPluginTest.java
src/test/java/plugins/PostBuildScriptPluginTest.java
src/test/java/plugins/ProjectDescriptionSetterPluginTest.java
src/test/java/plugins/SshSlavesPluginTest.java
src/test/java/plugins/XvncPluginTest.java
src/test/resources/openstack_plugin/cloud-init

Replacing https://github.com/jenkinsci/acceptance-test-harness/pull/191

[WIP] [JENKINS-38307] Stop installing detached plugins

---

src/test/java/core/CreateItemTest.java

[JENKINS-40950](https://issues.jenkins-ci.org/browse/JENKINS-40950)
@reviewbybees

[JENKINS-40950] Fix CreateItemTest#duplicate_item_name_displays_error test

---

src/test/java/core/JenkinsDatabaseSecurityRealmTest.java

- add mailer dependency to entire test.

Fix JenkinsDatabaseSecurityRealmTest for older versions of core

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
src/main/java/org/jenkinsci/test/acceptance/po/Login.java
src/test/java/plugins/AuthorizeProjectTest.java

[JENKINS-40123](https://issues.jenkins-ci.org/browse/JENKINS-40123)
Include in Login PO methods to verify if the login attempt has succeeded or failed.
@reviewbybees

[JENKINS-40123] Login PO includes methods to wait for login success or failure

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowSharedLibrary.java

- With many plugins installed, this test can fail without this fix

Fix WorkflowSharedLibrary to better locate #name

---

src/test/java/plugins/ForemanNodeSharingPluginTest.java

- Account for new cloud resources view
- Help speedup provisioning a bit more.

Fix ForemanNodeSharingTests

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
src/test/java/plugins/FolderPluginTest.java

[JENKINS-41467](https://issues.jenkins-ci.org/browse/JENKINS-41467)
New capabilities included:
- Credentials scoped to a folder.
- Environmental properties.
- View tabs.
- Delete folders.
@reviewbybees

[JENKINS-41467] Include missing capabilities to Folders POs

---

src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/User.java
src/test/java/core/JenkinsDatabaseSecurityRealmTest.java

User.id() now calls load() and since id == null
for a logged-out user, this will then force a call
to getJson() which leads to a 403 http error.

fix JenkinsDatabaseSecurityRealmTest#login_and_logout

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java

The particular problem is addressed in https://github.com/olivergondza/dumpling/blob/master/core/src/main/java/com/github/olivergondza/dumpling/factory/PidRuntimeFactory.java#L67-L77.

[FIXED JENKINS-42017] Delegate jstack invocation to dumpling

---

src/test/java/plugins/WorkflowMultibranchTest.java

Change the number of branches processed for the multibranch project.

Change check for number of branches.

---

src/main/java/org/jenkinsci/test/acceptance/ByFactory.java
src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
src/main/java/org/jenkinsci/test/acceptance/junit/WithInstallWizard.java
src/main/java/org/jenkinsci/test/acceptance/po/WizardCreateAdminUser.java
src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java
src/main/java/org/jenkinsci/test/acceptance/po/WizardLogin.java
src/test/java/core/InstallWizardTest.java

Allow writing ATHs for the install wizard

---

src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
src/test/java/plugins/WorkflowMultibranchTest.java

[JENKINS-42581](https://issues.jenkins-ci.org/browse/JENKINS-42581)
Introduce method to trigger a re-index in a Multibranch pipeline. Also take into account that a folder might not have a create view tab.

[JENKINS-42581] Introduce method to trigger a re-index

---

pom.xml

Update to latest parent jenkins:1.37

---

src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java

[JENKINS-42884](https://issues.jenkins-ci.org/browse/JENKINS-42884)
@WithPlugins annotation to inspect superclasses for plugin specs.

[JENKINS-42884] @WithPlugins find plugins in superclasses

---

src/test/java/plugins/OpenstackCloudPluginTest.java

- Use Schedule Termination
- Wait until Node has been cleaned by CleanupThread

Correct deletion of OpenStack Node

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
src/main/java/org/jenkinsci/test/acceptance/po/UpstreamJobTrigger.java
src/test/java/core/FreestyleJobTest.java
src/test/java/plugins/AbstractAnalysisTest.java
src/test/java/plugins/CheckStylePluginTest.java
src/test/java/plugins/PmdPluginTest.java

Some new tests created during a lecture in the students testing course. These test verify some minor aspects of freestyle jobs.

Added some new test for FreestyleJobTest

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java

[JENKINS-43371](https://issues.jenkins-ci.org/browse/JENKINS-43371)
Include Matcher for page URL.

[JENKINS-43371] Include Matcher for page URL

---

src/main/java/org/jenkinsci/test/acceptance/plugins/extra_columns/LastConsoleColumn.java
src/main/java/org/jenkinsci/test/acceptance/po/ListView.java
src/test/java/plugins/ExtraColumnsPluginTest.java

A first test case for the extra columns plug-in

---

src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
src/main/java/org/jenkinsci/test/acceptance/update_center/PluginSpec.java
src/test/java/org/jenkinsci/test/acceptance/junit/WithPluginsTest.java

@jglick, @stephenc, addressing https://github.com/jenkinsci/acceptance-test-harness/pull/305#discussion_r114585989

Correctly combine WithPlugins declaration so versions can be overridden

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
src/main/java/org/jenkinsci/test/acceptance/po/DumbSlave.java
src/test/java/plugins/SshSlavesPluginTest.java
src/test/java/plugins/WorkflowPluginTest.java

To fix the ssh slaves tests on the new ssh slaves plugin.
@reviewbybees

Set the host key verification strategy to none

---

src/test/java/plugins/WorkflowMultibranchTest.java

Ignore failing test

---

src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
src/test/java/plugins/AbstractAnalysisTest.java
src/test/java/plugins/AnalysisCollectorPluginTest.java
src/test/java/plugins/WorkflowPluginTest.java
src/test/resources/pipelines/hello-world/Jenkinsfile

In order to provide some more pipeline tests an example is needed that shows how to create a pipeline that checks out the Jenkinsfile from git.

Added two test cases that use a pipeline in a Git repository.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitScm.java
src/main/java/org/jenkinsci/test/acceptance/po/Build.java
src/test/java/plugins/GitPluginTest.java

Added tests for several additional behaviours:
- Calculate changelog against a specific branch
- Clean before checkout
- Clean after checkout
- Create tag for every build
- Custom SCM name
Besides that I added Behaviour classes for the remaining additional behaviours.

Git plugin tests

---

src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/NodeStatusArea.java
src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/SlavesMixIn.java
src/test/java/plugins/MissionControlTest.java

Add tests for the node and build queue section.

Mission Control View Plugin

---

src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserOutputPage.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/test/java/plugins/LogParserTest.java
src/test/resources/logparser_plugin/console-outputs/sample-log
src/test/resources/logparser_plugin/rules/log-parser-rules-sample

add more tests for the LogParser Plugin.

Logparser Plugin Tests

---

src/main/java/org/jenkinsci/test/acceptance/po/stageview/StageView.java
src/main/java/org/jenkinsci/test/acceptance/po/stageview/StageViewBuild.java
src/main/java/org/jenkinsci/test/acceptance/po/stageview/StageViewHeadline.java
src/main/java/org/jenkinsci/test/acceptance/po/stageview/StageViewJob.java
src/main/java/org/jenkinsci/test/acceptance/po/stageview/StageViewStage.java
src/test/java/plugins/StageViewTest.java
src/test/resources/stageview_plugin/multi_job.txt
src/test/resources/stageview_plugin/multi_job_aborted.txt
src/test/resources/stageview_plugin/multi_job_fail.txt
src/test/resources/stageview_plugin/multi_job_irregularnames.txt
src/test/resources/stageview_plugin/multi_job_unstable.txt
src/test/resources/stageview_plugin/single_job.txt

Fork to test the stageview for the build overview

Feature stageviewtest

---

src/test/java/plugins/JobDslPluginTest.java

As discussed with @uhafner in our meeting on thursday, I removed unnecessary code from JobDSL test methods.

JobDSL: Remove unnecessary code in methods

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
src/main/java/org/jenkinsci/test/acceptance/plugins/foreman_node_sharing/ForemanSharedNodeCloudPageArea.java
src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackCloud.java
src/main/java/org/jenkinsci/test/acceptance/po/Artifact.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java
src/test/java/core/FormValidationTest.java
src/test/java/plugins/ForemanNodeSharingPluginTest.java
src/test/java/plugins/OpenstackCloudPluginTest.java

```java
control("field").set(42)
assertThat(
control("field").getFormValidation(),
reported(WARNING, containsString("way too much"))
);
```

Introduce form validation primitives

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java
src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java

Cf. https://github.com/jenkinsci/acceptance-test-harness/pull/211#discussion_r119151235 & #207.
@reviewbybees

Speeding up PluginManager.installPlugin by using direct REST upload

---

src/test/java/plugins/ForemanNodeSharingPluginTest.java
src/test/resources/foreman_node_sharing_plugin/setup.sh

Simplified Foreman's population
Prepared for upcoming release of ForemanNodeSharingPlugin

Fixes for ForemanNodeSharingPlugin

---

src/test/java/plugins/ForemanNodeSharingPluginTest.java

Do not set credential ID for foreman tests

---

src/test/java/plugins/WorkflowPluginTest.java

While #365 is fresh in my mind.
@reviewbybees

Minor updates to WorkflowPluginTest.linearFlow

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java

[JENKINS-46999](https://issues.jenkins-ci.org/browse/JENKINS-46999)
Update UI for changes in github-branch-source-2.2.0
@reviewbybees

[JENKINS-46999] Update UI for changes in github-branch-source-2.2.0

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
src/main/java/org/jenkinsci/test/acceptance/plugins/gerrit_trigger/GerritTriggerServer.java
src/main/java/org/jenkinsci/test/acceptance/po/Artifact.java
src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java

Configure sane HttpURLConnection timeouts

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer.java
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile

Downstream of https://github.com/jenkinsci/docker-fixtures/pull/9: would like to test it here before releasing.
@reviewbybees

Pick up new docker-fixtures

---

src/main/java/org/jenkinsci/test/acceptance/plugins/rvm/Rvm.java
src/test/java/plugins/RvmPluginTest.java

Passes on 2.90, fails on 2.91, passes again on https://github.com/jenkinsci/jenkins/pull/3154.
@reviewbybees

[JENKINS-48116] Smoke test for the rvm plugin

---

src/main/java/org/jenkinsci/test/acceptance/po/DumbSlave.java

Needed after https://github.com/jenkinsci/jenkins/pull/3076 to fix test failures in, for example, `ScriptTest.execute_system_script`.
@reviewbybees

Install command-launcher as needed

---

src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java

#192 + #382 broke the build due to https://github.com/jenkinsci/junit-attachments-plugin/pull/19.
@reviewbybees

Failure diagnostics should print ATTACHMENT only for files, not subdirectories

---

Jenkinsfile
src/test/java/plugins/WorkflowPluginTest.java

Attempt to execute in parallel. I will do modification according result of execution this pull request.

Execute ATH in parallel.

---

pom.xml
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile

Integrates https://github.com/jenkinsci/docker-fixtures/pull/11.
@reviewbybees esp. @fcojfernandez

[JENKINS-48310] Upgrade docker-fixtures

---

ath-container.sh
docs/DOCKER.md
src/main/resources/ath-container/Dockerfile

To make it easier to reproduce the run environment.

Introduce ath-container.sh helper

---

src/main/java/org/jenkinsci/test/acceptance/plugins/saml/SamlSecurityRealm.java
src/test/java/plugins/SAMLPluginTest.java
src/test/resources/saml_plugin/config.php
src/test/resources/saml_plugin/saml20-idp-hosted.php
src/test/resources/saml_plugin/saml20-idp-remote.php

[JENKINS-42127](https://issues.jenkins-ci.org/browse/JENKINS-42127)
[JENKINS-41907](https://issues.jenkins-ci.org/browse/JENKINS-41907)
* Change the session duration to 100 days to test JENKINS-42127
* Evaluate to obtain IdP Metadata from URL JENKINS-41907
@reviewbybees @jenkinsci/code-reviewers

[JENKINS-42127][JENKINS-41907] SAML Plugin test update

---

src/test/java/plugins/GroovyPluginTest.java

Method used for verification message in log should not contain saving job configuration page.

Fix failing test.

---

src/test/java/plugins/JobConfigHistoryPluginTest.java

Test constantly failing because of missing plugin dependency

Add maven plugin dependency.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/ownership/OwnershipGlobalConfig.java

Test is constantly failing because of searching for wrong text.

Fix text value of radioButton.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/artifactory/ArtifactoryGlobalConfig.java
src/test/java/plugins/ArtifactoryPluginTest.java

Artifactory plugin is not configured correctly without setting artifactory id.

Add artifactory id - it is required in UI now.

---

src/test/java/plugins/SshSlavesPluginTest.java

Amends #86 by @armfergom (which already had to be edited in #179). Needed after https://github.com/jenkinsci/ssh-slaves-plugin/pull/32.
@reviewbybees

customStartup should do a more conservative match

---

src/test/java/plugins/FindBugsPluginTest.java

Fix constant failure of test FindBugsPluginTest.should_set_pipeline_result

Add missing plugin dependency.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SubversionScm.java

Fix constant failing test plugins.SubversionPluginTest.build_has_changes_and_repoBrowser
New area is not created by selection now and "yui-menu-button" does not exists for browser now.

Change DropdownMenu selection.

---

src/test/java/plugins/AbstractAnalysisTest.java
src/test/java/plugins/AnalysisCollectorPluginTest.java
src/test/java/plugins/CheckStylePluginTest.java
src/test/java/plugins/WarningsPluginTest.java

There is a problem with optional dependencies deployed dynamically.

Avoid JENKINS-49026.

---

src/main/java/org/jenkinsci/test/acceptance/po/WizardCreateAdminUser.java

This is an alternate impl, to #434 using css classes to look up the buttons. The buttons themselves don't have IDs so we don't have anything better for now.
/cc @mikecirioli
@olivergondza @uhafner

Look up buttons based on css classes rather than label

---

Jenkinsfile
docs/DOCKER.md
src/main/resources/ath-container/Dockerfile
vnc.sh

Infer some variables automatically when run from container

---

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java

[JENKINS-52389](https://issues.jenkins-ci.org/browse/JENKINS-52389)
Not all instances of Jenkins under test can launch within the 10 seconds
that getVersion() is allowed to retrieve the version number. If it does
not, then an AssertionError will be raised.
See 6e9586d6ebb69e278613025a5d316ba0bf4314b9 where the timeout was
introduced
@reviewbybees

JENKINS-52389 - Allow up to 1 minute for Jenkins to launch

---

src/main/java/org/jenkinsci/test/acceptance/po/WizardCreateAdminUser.java
src/test/java/core/InstallWizardTest.java

Installation wizard wants fulfill/confirm Jenkins url since version 2.119

Confirm Jenkins url.

---

src/main/java/org/jenkinsci/test/acceptance/plugins/warnings/ParsersConfiguration.java

In global config was added advanced button for displaying parser's section.

UI change in adding parser.

---

src/test/java/plugins/GlobalPublishPluginTest.java

There are a few mistakes which were done when using docker cp was removed.

Fix global publisher tests

---

Jenkinsfile
docs/DOCKER.md
pom.xml
src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/MissionControlView.java
src/main/java/org/jenkinsci/test/acceptance/po/Build.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
src/main/resources/ath-container/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/selenium/scroller.js
src/test/java/plugins/KerberosSsoTest.java
src/test/java/plugins/MissionControlTest.java

My builds have seemed stable for some time, open this pull request to check how it works in upstream builds.

Selenium 3

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/jira/JiraGlobalConfig.java
src/test/java/plugins/JiraPluginTest.java

Signed-off-by: olivier lamy <olamy@apache.org>

fix jira plugin test

---

Jenkinsfile
src/main/java/org/jenkinsci/test/acceptance/plugins/gradle/GradleWrapper.java
src/test/java/plugins/GradlePluginTest.java
src/test/resources/gradle_plugin/pipeline_test_build_scan.txt
src/test/resources/gradle_plugin/pipeline_test_multiple_tasks.txt

This pull request should not be merged. It is only for debugging gradle test failures in upstream build, because I am not able to reproduce it.

Debug gradle plugin.

---

src/test/java/plugins/DeclarativePipelineTest.java

More tests are coming! But here's a start.
cc @reviewbybees esp @rsandell

Initial hello world ATH test for Declarative Pipeline

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
vnc.sh

This was accidentally removed in https://github.com/jenkinsci/acceptance-test-harness/pull/457

Bring BROWSER_DISPLAY support back

---

src/main/tool_installers/updates/hudson.tasks.Ant.AntInstaller

This should fix test added in #493

Update Ant tool cached update center file

---

src/main/resources/ath-container/Dockerfile
src/main/resources/ath-container/set-java.sh

https://issues.jenkins-ci.org/browse/JENKINS-56950

Switch ATH container from Debian to Centos that distributes all the Javas

---

src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java

Generalized version of https://github.com/jenkinsci/acceptance-test-harness/pull/498
@MRamonLeon @raul-arabaolaza

Explicitly scroll to select elements 

---

src/main/java/org/jenkinsci/test/acceptance/po/TextParameter.java

- Needed to test fix for JENKINS-57642
- See https://github.com/jenkinsci/jms-messaging-plugin/pull/124/files#diff-45d12ccd961fd0f2dfd7b46caf36602cR373 for eventual usage

Add TextArea PageObject

---

src/main/java/org/jenkinsci/test/acceptance/junit/Native.java

Some tests to be refactored to use containers

Deprecate use of @Native

---

src/main/java/org/jenkinsci/test/acceptance/plugins/configuration_as_code/JcascManage.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java
src/test/java/plugins/ConfigurationAsCodeTest.java
src/test/resources/configuration_as_code/trivial.yaml

Adding utility classes and a trivial test as this is needed from kerberos-sso plugin, too.

Add test and POs for JCasC 

---

docs/CONTRIBUTING.md

Codifying the parts of suggested guidelines[1] where there ware no disagreement so we can take advantage of what we have.
@jenkinsci/code-reviewers, you might be interested in having a look.
[1] https://docs.google.com/document/d/1k9sDlssxs0URZOjbF3jmBhTf-LoA7JQKj5TLIONmuVA/edit#

Add contributing guidelines

---

src/test/java/plugins/SshSlavesPluginTest.java

See https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/170/testReport/plugins/SshSlavesPluginTest/java_8_split8___newSlaveWithExistingCredential/
It is a follow-up to the fixes in https://github.com/jenkinsci/jenkins/pull/3967 by @jvz which got released in 2.171/

Fix the SShSlavesPluginTest#newSlaveWithExistingCredential() in Jenkins 2.176.1+

---

src/test/java/core/JdkTest.java

https://issues.jenkins-ci.org/browse/JENKINS-59298

[FIX JENKINS-59298] Remove JDK autoinstallation tests from ATH

---

src/main/java/org/jenkinsci/test/acceptance/SshKeyPair.java
src/main/java/org/jenkinsci/test/acceptance/controller/ExistingJenkinsController.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java
src/main/java/org/jenkinsci/test/acceptance/utils/SHA1Sum.java
src/test/java/plugins/WorkflowPluginTest.java

eclipse identified some resource leaks, so I fixed them (except for two which created `LocalSlaveController`s which required a larger refactoring than I wanted to do at this time

Close resources to prevent leaks.

---

src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java

builds upon #534 and as such the only change is 
b98713e

Strings are not urls

---

.gitignore

Ignore .DS_Store files 

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
src/test/java/plugins/WorkflowMultibranchTest.java
src/test/java/plugins/WorkflowPluginTest.java

Replaces https://github.com/jenkinsci/acceptance-test-harness/pull/519

Workaround broken branch source UI test

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/update_center/LocalOverrideUpdateCenterMetadataDecoratorImpl.java
src/main/java/org/jenkinsci/test/acceptance/utils/MavenLocalRepository.java
src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java

Signed-off-by: olivier lamy <olamy@apache.org>

user local repository may different from default

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/plugins/jira/JiraUpdater.java

changes are  https://github.com/jenkinsci/jira-plugin/commit/7feee5c9f2e7dfe5b140946ab81a1df8cb2e47c1
Signed-off-by: olivier lamy <olamy@apache.org>

Fix Jira ATH due to label changes in the plugin

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java

This updates credential lookup for the plugin post-application of
https://github.com/jenkinsci/credentials-plugin/pull/120

Update ManagedCredentials for credentials-2.3.2

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java

* The Check now button is not a button anymore but a link.
* Search the plugin in the filter box before selecting (To accommodate https://github.com/jenkinsci/jenkins/commit/e97fe13fbdfd0f1a311862adafb36c10e621e536)

Plugins need to be "filtered" before selecting

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/ManagedCredentials.java

This is a fix for dd6e0d61c5eec746a8456612487262d23344a741
@jeffret-b @Wadeck @daniel-beck
@bmunozm @raul-arabaolaza @imonteroperez

Fix ManagedCredentials for post 2.3.2

---

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java

builds upon #534 and #535 but does not need any of them (I was just too lazy to rebase as I have other WIP in the same tree)
6faa6c878248846c1227955175166a2b098a5262 is the isolated changes for this PR.

Save should use submit

---

src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java

Do not fail too early when scrolling can not be properly done, the
element might be clickable without scrolling, so let the test continue
and fail later with a clearer error message.

Do not fail too early on scrolling

---

docs/BROWSER.md

nuff said...
help people to avoid wasting a day like I just have :-/

help people to not crash firefox

---

src/main/java/org/jenkinsci/test/acceptance/Matchers.java

JENKINS-62869 Fix JavaDoc ATH on Jenkins >2.238 (sidebar rework)

---

src/main/java/org/jenkinsci/test/acceptance/plugins/saml/SamlSecurityRealm.java

This PR is a dependency of https://github.com/jenkinsci/jenkins/pull/3895.

JENKINS-62870 SAML Plugin test for tables to divs form rework

---

src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SubversionScm.java
src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SvnRepositoryBrowserWebSvn.java

https://issues.jenkins-ci.org/browse/JENKINS-62801

JENKINS-62801 SVN compatibility with tables to divs

---

src/main/java/org/jenkinsci/test/acceptance/po/Folder.java

Fix folders test

---

src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java

Checking the tests execution, seems like there was a problem I didn't catch up before when executing `HarRecorderTest`

Attempt to fix HarRecorderTest

---

src/test/java/plugins/StageViewTest.java

previous test was based on a bug fixed in new version https://github.com/jenkinsci/pipeline-stage-view-plugin/pull/108

fix for pipeline-stage-view-2.18

---

pom.xml

Please see https://github.com/kohsuke/wordnet-random-name/pull/5
And https://issues.jenkins.io/browse/JENKINS-58979
Using 1.5 will remove offensive words when generating random name for job, folders, ...

[JENKINS-58979] use new version of wordnet-random-name without offensive words for random names.

---

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer.java
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/Dockerfile
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/config/config.php
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/config/dav_svn.conf
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/config/supervisord.conf
src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/config/viewvc.conf
src/test/java/plugins/SubversionPluginTest.java
src/test/java/plugins/WorkflowPluginTest.java

The subversion container could no longer be built as the ubuntu version
was no longer supported and its repos removed.
Switched to Debain (from ubuntu) as this contained packages for
everything that was required.
Using ViewVC not webSVN now - but nothing was actually using this (we
could remove it entierly if we want.
took the opertunity to cleanup the docker file

fix subversion test.

---

src/test/java/plugins/GitPluginTest.java

https://github.com/jenkinsci/git-plugin/pull/1067/ changed the format of this message, updating test accordingly

[JENKINS-38676] adapt git plugin test to code changes

---

src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java

I am seeing flaky ATHs due to requests to `updateCenter/body` not working (!?)
As a workaround, this is reloading the page every 15 seconds (since polling of `waitFor` is 500ms)

Refresh plugin updates page sometimes while waiting for plugins to install

---

pom.xml

cf. https://github.com/browserup/browserup-proxy/releases/tag/v2.1.2

Updates browserup-proxy to 2.1.2

---

src/test/java/core/FormValidationTest.java

Fix another regression caused by changing text in jenkinsci/jenkins#5538.

Adapt to changes in validate text

---

src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/CustomConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/ProvidedFile.java

- Remove link which is no longer an anchor. Reason: https://github.com/jenkinsci/config-file-provider-plugin/commit/313e9d1e57dd926aa3523a1e0691bee7ca483bae#diff-b101d0df90ce240b092f193660e38a3213b7aac98b74aa4c5ce32a54f5061770R52
- The custom file content is now a CodeMirror element. Reason: https://github.com/jenkinsci/config-file-provider-plugin/pull/90/files#diff-7856449f4dfcb3c2c32ea02c5253ba72b25af847fab8bc56d2aac9ae0a8ba88cR76
Desired reviewers: @raul-arabaolaza, @jtnord, @alecharp , @car-roll , @olamy , @bitwiseman

Fix latest changes of Config File Provider

---

src/test/java/plugins/AuditTrailPluginTest.java

This fixes `AuditTrailPluginTest`

Fix AuditTrailPluginTest

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/test/java/core/FormValidationTest.java

https://bugzilla.mozilla.org/show_bug.cgi?id=1693857

Trying out the firefox workaround mentioned in mozilla bugzilla

---

src/test/java/plugins/MatrixPluginTest.java

Related to https://github.com/jenkinsci/jenkins/pull/5425

Fix MatrixPluginTest#run_configurations_on_with_a_given_label for Jenkins 2.307+

---

src/test/java/plugins/XUnitPluginTest.java

Fixes `XUnitPluginTest#publish_xunit_results`
Test trend is no longer an image.

Fix selector for test result trend

---

src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/Slave.java

Fixes
* `PrioritySorterPluginTest#match_jobs_by_name`
* `PrioritySorterPluginTest#match_jobs_by_view`

Fix PrioritySorterPluginTest tests

---

src/test/java/plugins/OwnershipPluginTest.java

Fixes `OwnershipPluginTest#correct_redirect_after_save`

Fix OwnershipPluginTest#correct_redirect_after_save

---

src/main/java/org/jenkinsci/test/acceptance/plugins/nodelabelparameter/LabelParameter.java
src/main/java/org/jenkinsci/test/acceptance/plugins/nodelabelparameter/NodeParameter.java
src/main/java/org/jenkinsci/test/acceptance/po/BuildHistory.java
src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/test/java/plugins/NodeLabelParameterPluginTest.java

the test was firstly failing as the PageObject was selecting the wrong
part of the page in the job.
secondly selecting a node was using an incorrect control
there are still failures in 3 tests that I have not looked at that also
need fixing.

Fix the NodeLabelParameterPluginTests

---

src/test/java/plugins/WorkflowPluginTest.java

- Once we use https://github.com/jenkinsci/docker-fixtures/pull/32 if we run `WorkflowPluginTest#sshGitInsideDocker` using docker-compose we face the following issue:
```
$ docker run -t -d -u 1000:1000 --network=ath-network -w /home/test/workspace/subsequent_path --volumes-from 5d019492f2d8bab1c55051291460201def84b7a3c19349b53a07b9d5adbc4f86 -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** -e ******** cloudbees/java-build-tools cat
$ docker top 251161f4ed604289ab54b8c3d18f3d46d3dd4951dc9305d9d412a7b1a8acdc36 -eo pid,comm
[Pipeline] {
[Pipeline] checkout
The recommended git …
```

Attach specific network from Docker fixtures

---

src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/read/ProjectStatusStdJobList.java
src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SvnRepositoryBrowserWebSvn.java
src/main/java/org/jenkinsci/test/acceptance/po/BuildHistory.java
src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
src/main/java/org/jenkinsci/test/acceptance/po/ListView.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/po/Slave.java
src/main/java/org/jenkinsci/test/acceptance/po/View.java
src/test/java/plugins/DashboardViewPluginTest.java
src/test/java/plugins/FolderPluginTest.java
src/test/java/plugins/JobDslPluginTest.java
src/test/java/plugins/NodeLabelParameterPluginTest.java
src/test/java/plugins/PrioritySorterPluginTest.java

Mostly related to the new tables
One test for the plugin manager deploy from url as well
All tests should pass now, before was 50+

Fix some tests

---

src/main/java/org/jenkinsci/test/acceptance/plugins/batch_task/BatchTaskDeclaration.java
src/main/java/org/jenkinsci/test/acceptance/plugins/external_workspace_manager/ExternalNodeConfig.java
src/main/java/org/jenkinsci/test/acceptance/plugins/gradle/GradleStep.java
src/main/java/org/jenkinsci/test/acceptance/plugins/job_dsl/JobDslBuildStep.java
src/main/java/org/jenkinsci/test/acceptance/plugins/mail_watcher/OnlineStatusNotification.java
src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenModuleSet.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/main/java/org/jenkinsci/test/acceptance/po/LdapSecurityRealm.java
src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
src/test/java/plugins/GradlePluginTest.java
src/test/java/plugins/TimestamperPluginTest.java

relates to https://github.com/jenkinsci/jenkins/pull/5923

Click labels for checkboxes

---

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_multibranch/GithubBranchSource.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java

Required for https://github.com/jenkinsci/jenkins/pull/5923

More checkbox locating by label

---

src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java
src/test/java/plugins/ScriptSecurityPluginTest.java

https://github.com/jenkinsci/priority-sorter-plugin/pull/104
https://github.com/jenkinsci/script-security-plugin/pull/365

Adapt to recent changes in plugins

---

src/test/java/plugins/JobDslPluginTest.java

https://issues.jenkins.io/browse/JENKINS-67689

Workaround JENKINS-67689

---

src/test/java/core/PluginManagerTest.java

Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/741

Deflake uninstall plugin test

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
src/main/java/org/jenkinsci/test/acceptance/po/ListView.java
src/main/java/org/jenkinsci/test/acceptance/po/View.java
src/test/java/plugins/JobDslPluginTest.java
src/test/java/plugins/MavenPluginTest.java

see https://github.com/jenkinsci/acceptance-test-harness/pull/730 and https://github.com/jenkinsci/jenkins/pull/6084

Forward compat for breadcrumbs

---

src/test/java/plugins/FavoriteTest.java

This changeset contains a test to validate that the Favorite plugin can correctly add and remove projects from the users' favorite.

Validate adding and removing projects to users' favorites

---

.mvn/jvm.config

Setting up a jvm configuration as code to run the testing

Setup a jvm configuration for Maven

---

src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/ConfigFileProvider.java

https://github.com/jenkinsci/acceptance-test-harness/pull/746#issuecomment-1047688212

Update config file provider UI

---

src/main/resources/ath-container/run.sh
src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
src/test/java/plugins/LogParserTest.java
src/test/java/plugins/StageViewTest.java

https://github.com/jenkinsci/jenkins/pull/6307
cc @janfaracik

Compatibility with tango item replacement

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/DomainPage.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
src/test/java/plugins/DashboardViewPluginTest.java

Fix failures caused by 
* https://github.com/jenkinsci/credentials-plugin/pull/287 (button is labelled `Create` instead of `OK`). Switched matcher to element name instead.
* and another one due to an added Jenkins logo in svg causing the matcher to fail. Matching the element title instead.

Fix credentials and weekly changes

---

Jenkinsfile

spacing was inconsistent before

Format Jenkinsfile

---

src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
src/main/resources/ath-container/run.sh
src/test/java/core/FormValidationTest.java

https://github.com/jenkinsci/jenkins/pull/6460

New form validation UI

---

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/resources/ath-container/run.sh

https://github.com/jenkinsci/jenkins/pull/6527

Testing new checkboxes for the plugin manager

---

vars.cmd

I have this script locally in another test repo that also uses the ATH.  It's probably useful to anyone else wanting to run the ATH on windows (with WSL) so add it here for others

Add vars.cmd to ease setting up an environment on windows

---

pom.xml

as demonstrated in https://github.com/jenkinsci/acceptance-test-harness/pull/756 you can not use a single version for all of jackson dependencies.
Switch to the bom for consuming the dependencies

obtain jackson via a bom version

---

src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java
src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java

Tiny fix to account for the new `div` element introduced in https://github.com/jenkinsci/matrix-auth-plugin/pull/120.
--

Fix Matrix Auth tests

---

vars.cmd

as I keep forgetting to add cygwin onto the path before I ran the command it is better to use commands that are inbuilt into the OS

remove the need for cygwin

---

src/main/resources/ath-container/run.sh

see https://github.com/jenkins-infra/helpdesk/issues/3034

Use supported URL for fetching latest WARs

---

pom.xml

Modern alternative to https://github.com/jenkinsci/acceptance-test-harness/pull/820

Exchange xmlunit with maintained xmlunit-legacy

---

pom.xml

and remove buggy dependency on scm-git as it need scm-api to be at the same level.

Upgrade release-plugin to 3.0.0-M6

---

README.md
docs/PRELAUNCH.md
pom.xml
src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
src/main/java/org/jenkinsci/test/acceptance/log/LogListener.java
src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java
src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
src/test/java/UnixDomainSocketTestServer.java

This reverts commit dbaafe1c76f813c433d6ef0ca092a52d295effd0 as per request in https://github.com/jenkinsci/acceptance-test-harness/pull/861#issuecomment-1195232104.

Revert "Remove prelaunching functionality (#861)"

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java
src/main/java/org/jenkinsci/test/acceptance/junit/GlobalRule.java
src/main/java/org/jenkinsci/test/acceptance/junit/RuleAnnotation.java
src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/PageArea.java
src/main/java/org/jenkinsci/test/acceptance/po/Trigger.java
src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
src/main/java/org/jenkinsci/test/acceptance/slave/SlaveController.java
src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java

Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/888.
Apparently, maven shows 100 errors only, but this should really resolve all of them.

More javadoc fixes

---

Jenkinsfile

https://github.com/jenkinsci/acceptance-test-harness/pull/891#discussion_r945121846
Failed correctly in https://ci.jenkins.io/blue/organizations/jenkins/Core%2Facceptance-test-harness/detail/PR-893/5/pipeline/31

Add CI stage

---

src/test/java/core/InstallWizardTest.java

Replaced msbuild plugin with junit for InstallWizardTest#wizardInstallCustomPluginsTest
cc @jtnord

replace msbuild with junit in InstallWizardTest

---

.github/dependabot.yml

Closes https://github.com/jenkinsci/acceptance-test-harness/pull/926

Fix byte-buddy dependabot exclusion

---

pom.xml

Remove obsolete Java mail dependency

---

pom.xml

Rather use a version, that is not a decade old.

Update trilead-ssh from build212-hudson-6 to build-217-jenkins-223.v546f979619d4

---

pom.xml

Let's see if it's actually obsolete...

Remove obsolete process-utils dependency

---

pom.xml
src/main/resources/ath-container/Dockerfile
src/main/resources/ath-container/set-java.sh

The newest LTS version requires Java 11 as minimum version by now.

Remove Java 8 restrictions and use Java 11

---

pom.xml

the versions of many plugins was defeined here even though they have exactly the same version in the parent.
This PR removes the redundant declaration.

remove versions specified by the parent

---

src/test/java/plugins/ConfigFileProviderTest.java

Fixes the test so that the test *should* pass on windows.
It fails with a similar reason I see in a specific other CI setup - but that is for a different fix

make the test work so it can be debugged on windows

---

src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/ConfigFileProvider.java

This is handled if visit (or an implicit navigation) is used, but not if clicking an element causes a page change.

Ensure that we disable sticky elements when changing navigation

---

src/main/java/org/jenkinsci/test/acceptance/plugins/disk_usage/DiskUsage.java
src/test/java/plugins/DiskUsagePluginTest.java

This at least checks if the buttons are there and clickable
There's not really anything to check here as far as I can tell.
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/986

Remove log checking for Disk Usage

---

pom.xml

Ideally this should be zero (not enabled here) and anyone that wants it should opt in.
CloudBees runs a subset of the tests defined here without any retries and there are a few flakes - but not many (and 1 should ideally be enough without letting bad new tests be written).

ratchet down the number of times we retry

---

src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java

This addresses the test failure in https://github.com/jenkinsci/acceptance-test-harness/pull/759

Use id for frame instead of index

---

src/main/resources/ath-container/Dockerfile

Update maven to 3.8.7

---

pom.xml

Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1068

Add URL to pom.xml

---

.github/dependabot.yml

Fix tomcat 10 dependabot path

---

src/main/resources/ath-container/Dockerfile

Update maven to 3.9.1

---

pom.xml

Closes https://github.com/jenkinsci/acceptance-test-harness/pull/1057
Closes https://github.com/jenkinsci/acceptance-test-harness/pull/1056

Bump jffi from 1.3.10 to 1.3.11

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer.java
src/main/java/org/jenkinsci/test/acceptance/plugins/ant/AntInstallation.java
src/test/java/plugins/AntPluginTest.java
src/test/resources/plugins/ant/custom-build-file.xml

[#1053] Add tests for Ant Plugin

---

src/main/java/org/jenkinsci/test/acceptance/AbstractPipelineTest.java
src/main/java/org/jenkinsci/test/acceptance/utils/PipelineTestUtils.java

Needed by #1053 e.g. #1067  #1083 #1071 
Instead of those PRs depending on #1067 that is currently stuck, we could perhaps get this one in quickly to unlock the other PRs.

Pipeline test utility classes needed for multiple contributions

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/AbstractPipelineTest.java
src/test/java/plugins/DisplayUrlApiTest.java

Add tests for DisplayUrlApi

---

src/test/java/plugins/DeclarativeAssistantMigrationTest.java
src/test/java/plugins/PipelineTest.java

Add test for declarative migration assistant and pipeline with unstable tests

---

src/test/java/plugins/SecureRequesterWhitelistTest.java

add tests for secure-requester-whitelist

---

src/test/java/plugins/MSTestPluginTest.java
src/test/java/plugins/MSTestRunnerPluginTest.java

Related to https://github.com/jenkinsci/acceptance-test-harness/issues/1053
This adds tests for the MSTestRunner plugin. All manually tested and working.

[#1053] Adding tests for MSTestRunner plugin

---

src/test/java/plugins/MetricsTest.java

[#1053] Add metrics test

---

Jenkinsfile

See [the design document](https://docs.google.com/document/d/12LdoAFA566P4LgHhu1L-fuOQuhipxk77tUDXQdNmhss/edit) for a thorough explanation of the design. This PR begins to implement the design described in that document by implementing test result collection for the ATH workspace in ATH build. (Test result collection for the ATH workspace in core builds is being done in https://github.com/jenkinsci/jenkins/pull/7857.) Test result collection is the easy part of integrating Launchable into our CI system; the difficult part (as explained in the design document) is commit collection, which I plan to work on after this. (As part of commit collection, I have various PRs open to add Git hash information to `MANIFEST.MF` for core, core components, and all plugins, so that change will need a …

Collect Launchable test results for ATH workspace in ATH builds

---

Jenkinsfile

This PR takes us further on our Launchable journey by recording builds and sessions, though the builds are so far very incomplete without any Jenkins core commits. I plan to fix that very soon after this PR is merged once core weeklies and LTS releases have the Git hash in `META-INF/MANIFEST.MF`. The next step after this PR is to wait a bit for data to be collected and then implement subsetting.

Record Launchable builds (to an approximation) and sessions

---

src/main/resources/ath-container/Dockerfile
src/main/resources/ath-container/set-java.sh

#1123 was submitted against the wrong target branch; this is a resubmission of that PR against the main branch.

Add Java 17 to Docker image

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java
src/main/java/org/jenkinsci/test/acceptance/po/Slave.java
src/main/java/org/jenkinsci/test/acceptance/utils/SauceLabsConnection.java
src/test/java/plugins/OwnershipPluginTest.java

Post-cleanup from https://github.com/jenkinsci/acceptance-test-harness/commit/be6d6fd92c68fedf4b48b97a3794d7b5b8893492 and partly other PRs.

Remove unused imports

---

.github/renovate.json

Fix geckodriver detection

---

pom.xml

For LTS 2.387.3 release on May 3rd, 2023.

Update LTS Maven profile in ATH to 2.387.3

---

Jenkinsfile
pom.xml

Backport of #1118 to the LTS line.

Add Jenkins core commit to Launchable build for LTS line

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java

When running the remote driver it would be noice to see the used image as well.

Show the image of the remote container in logging statement

---

.github/renovate.json
pom.xml

Closes https://github.com/jenkinsci/acceptance-test-harness/pull/1175

Move to Guice 6

---

Jenkinsfile

Launchable is now installed on our agents by default, so this is no longer needed.

Remove use of Launchable shared library functionality

---

src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java

use java's inbuilt Base64
use java's null stream

replace deprecated methods with JDK methods

---

src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java

@Bananeweizen did not respond to https://github.com/jenkinsci/acceptance-test-harness/pull/1180#pullrequestreview-1434318320.

Revert changes to `ExternalWorkspaceManagerPluginTest` from #1180

---

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java

Java9 introduced pid() to process so replace the reflection with the supported API

replace reflection with pid

---

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/AbstractCredentialsTest.java
src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
src/test/java/core/CredentialsTest.java
src/test/java/plugins/CredentialsBindingTest.java
src/test/java/plugins/FavoriteTest.java
src/test/java/plugins/MatrixAuthPluginTest.java
src/test/java/plugins/SSHCredentialsTest.java
src/test/java/plugins/ScriptSecurityPluginTest.java

the `mock-security-realm` is not a production quality realm and the tests here can trivially use Jenkins' internal database realm.
For CLoudBees' internal use this also means we do not need to hit the update center as the other plugins being part of the product will come from the war.
`JobDslPluginTest` and `AuthorizeProjectTest` have not been changed (leaving the only users of `mock-security-realm` in this project (there is no test of mock-security-realm here!).  
I am not intending to update these - in both cases the plugins are up for adoption - so if we feel the need to update them I would propose that we delete them instead (in a different PR)

Migrate from mock security realm

---

pom.xml

reverts #920 which was incomplete
the framework is still written using junit4 APIs (`TestWatcher` Assumptions etc) yet was running with junit5
I have seen various errors where a test fails, the subsequent interactions that then happen are seemingly not happening in an appropriate way.
Whilst this may not may not be due to running with junit5, running with junit5 should not be done until the framework is moved to junit5, and in the interim it at least rules junit5 out as a possibility of strange behaviour
ran `mvn dependency:tree` to ensure that junit5 is not creeping in unexpectedly
ran `mvn test -Dtest=CreateItemTest` to validate at least one test is still working that excersizes the framework

revert to junit4

---

src/test/java/plugins/JacocoPluginTest.java
src/test/resources/jacoco/test/pom.xml

Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1135
Edit: The scriptler test failures happened independently of this PR, and are present on the default branch too.

Forward compatibility with Java 17 in JacocoPluginTest

---

src/test/java/plugins/ScriptlerPluginTest.java

ref https://github.com/jenkinsci/acceptance-test-harness/issues/1239

Temporarily ignore scriptler tests

---

src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Script.java
src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Scriptler.java
src/test/java/plugins/ScriptlerPluginTest.java

Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1239

Adapt to scriptler plugin changes

---

pom.xml

Updated the LTS version in the Maven profile to 2.401.2.

Update LTS in Maven profile to 2.401.2

---

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container/Dockerfile

https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1272/3/testReport/junit/plugins/DeployPluginTest/latest_linux_jdk17_firefox_split4___deploy_sample_webapp_to_tomcat10/attachments/docker-Tomcat10Container.build.log
Shows:
```
#7 [4/6] RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
#7 0.214 Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
#7 0.224 Executing: /tmp/apt-key-gpghome.ITWLNzmTeG/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5
#7 60.53 gpg: keyserver receive failed: Connection timed out
#7 ERROR: process "/bin/sh -c apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 40976EAF437D05B5" did not complete successfully: exit code: 2
```
Lets try this, otherwise I …

Fix deploy plugin test

---

pom.xml

Update LTS in Maven profile to 2.401.3

---

src/test/java/plugins/DashboardViewPluginTest.java

Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1296
Code inspection not run locally
```[tasklist]
```

Don't look for project prefix to page title

---

src/test/java/plugins/ScriptSecurityPluginTest.java

`groovy-postbuild` is not as popular as `pipeline` - so this adds coverage of script-security with pipeline.
if the consensus is that we only need one or the other tested here (groovy-postbuild or pipeline) then my vote would be to test pipeline over `groovy-postbuild`.
```[tasklist]
```

add coverage for script-security with pipeline

---

src/main/java/org/jenkinsci/test/acceptance/po/Build.java
src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java

Since an app-bar has been introduced there's more DOM elements between the main panel and the heading.
Use a descendant-or-self selector rather than a child selector.
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1300
Ran the tests locally, failed before and passed after
```[tasklist]
```

Fix jobdsl tests on new core

---

src/main/resources/ath-container/run.sh

Firefox will not use a proxy for 127.0.01
can be worked around by using a custom DNS entry
fixes #1165
built the container image locally and introduced a failing test into the source
ran the test `run.sh firefox latest -DforkCount=1 -Dmaven.test.failure.ignore=true -B -Dtest=FailingTest -DElasticTime.factor=10` inside the container and inspected the resulting har
```[tasklist]
```

use custom DNS in the ath container to enable HAR recording

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Control.java

fixes for https://github.com/jenkinsci/jenkins/pull/8340
```[tasklist]
```

forward compatibility for core-8340

---

src/main/resources/ath-container/run.sh

Reverts jenkinsci/acceptance-test-harness#1314

Revert "use custom DNS in the ath container to enable HAR recording"

---

src/test/java/plugins/DeclarativePipelineTest.java
src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
src/test/java/plugins/MavenPluginTest.java
src/test/java/plugins/PipelineTest.java
src/test/java/plugins/WorkflowMultibranchTest.java
src/test/java/plugins/WorkflowPluginTest.java

Update maven to 3.9.4 in test cases, matching the maven version used in the dockerfile

Update maven in tests

---

src/test/java/plugins/WorkflowPluginTest.java

Relates to https://github.com/jenkinsci/acceptance-test-harness/issues/1320
Ran it locally and checked it passed on Java 21
```[tasklist]
```

Use jenkinsci test project for WorkflowPluginTest

---

pom.xml

These are managed in the parent POM

Remove unnecessary version number and exclusion

---

src/main/java/org/jenkinsci/test/acceptance/po/View.java
src/test/java/core/ViewTest.java

Add a test for setting a view description as well as fixing field lookup

---

src/main/java/org/jenkinsci/test/acceptance/po/Folder.java

after switching folders to use a confirmation dialog the tests no longer work for lts where still the browser native dialogs are used.
```[tasklist]
```

fix folders tests

---

pom.xml

Updated LTS in Maven profile to `2.414.3`
```[tasklist]
```

Update LTS in Maven profile to 2.414.3

---

src/test/java/plugins/GroovyPluginTest.java
src/test/java/plugins/JobDslPluginTest.java
src/test/java/plugins/ScriptSecurityPluginTest.java

see https://github.com/jenkinsci/acceptance-test-harness/issues/1444
```[tasklist]
```

Suppress known failures

---

pom.xml
src/test/java/core/FreestyleJobTest.java
src/test/java/plugins/ScriptSecurityPluginTest.java

see https://github.com/jenkinsci/jenkins/pull/8394
```[tasklist]
```

Forward compatibility for use Jenkins modal for 'Apply' button failures

---

src/test/java/plugins/GitLabPluginTest.java

see https://github.com/jenkinsci/acceptance-test-harness/issues/1461
```[tasklist]
```

Ignore flakey plugins.GitLabPluginTest.testGitLabMultibranchPipeline

---

pom.xml

Feat: Update Jenkins LTS version

---

vars.cmd

update selenium version and be tollerant of newer WSL installs

---

pom.xml

Closes #1525
Fixes #1539
Fixes #1540
Update `lts` in Maven profile to 2.440.3. 
```[tasklist]
```

Update LTS in Maven profile to 2.452.1

---

pom.xml

chore: update lts in maven profile to 2.452.2

---

.gitignore
pom.xml

Updated LTS version to 2.452.3 in Maven profile.

chore: update lts in maven profile to 2.452.3

---

Jenkinsfile
README.md
src/main/resources/ath-container/Dockerfile
src/main/resources/ath-container/set-java.sh

Upgrade Ubuntu from 22.04 to 24.04

---

src/main/resources/ath-container/Dockerfile

https://blog.mozilla.org/en/products/4-reasons-to-try-mozillas-new-firefox-linux-package-for-ubuntu-and-debian-derivatives/

Install Firefox from `packages.mozilla.org`

---

ath-container.sh
src/main/resources/ath-container/Dockerfile

Fixes https://github.com/jenkins-infra/helpdesk/issues/4192

Clean up Docker image

---

.github/dependabot.yml
.github/renovate.json

Replace Dependabot with Renovate

---

Jenkinsfile

Related to https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2270821972,
this PR removes the ci.jenkins.io Docker login step as we now have a transparent DockerHub mirror.
The registry mirror is setup at the Docker Engine level so it should also be used out of the box for all the "DonD" (Docker on Docker - e.g. socket sharing - https://github.com/jenkinsci/acceptance-test-harness/blob/3c2fb6fa19733ad2a5ceacb88cfc6362eb83591f/ath-container.sh#L37 and https://github.com/jenkinsci/acceptance-test-harness/blob/3c2fb6fa19733ad2a5ceacb88cfc6362eb83591f/Jenkinsfile#L130) usages.

chore(pipeline) stop using Docker login primitive - reverts #1634 and #1640

---

pom.xml

- **Use 2.462.1 as lts profile, not 2.452.3**
- **Use 2.471 as the base Jenkins version, not 2.470**
Refer to the 2.462.1 release checklist at:
* https://github.com/jenkins-infra/release/issues/561
None.  Relying on ci.jenkins.io to run the tests.

Use 2.462.1 and 2.471 as Jenkins versions

---

src/test/java/core/CredentialsTest.java
src/test/java/plugins/ActiveDirectoryTest.java
src/test/java/plugins/CredentialsBindingTest.java
src/test/java/plugins/DeclarativeAssistantMigrationTest.java
src/test/java/plugins/DisplayUrlApiTest.java
src/test/java/plugins/JobDslPluginTest.java
src/test/java/plugins/LdapPluginTest.java
src/test/java/plugins/MailWatcherPluginTest.java
src/test/java/plugins/MatrixAuthPluginTest.java
src/test/java/plugins/PlainCredentialsBindingTest.java
src/test/java/plugins/SSHCredentialsTest.java
src/test/java/plugins/SshSlavesPluginTest.java
src/test/java/plugins/StageViewTest.java
src/test/java/plugins/SubversionPluginTest.java
src/test/java/plugins/WorkflowMultibranchTest.java
src/test/java/plugins/WorkflowPluginTest.java
src/test/java/plugins/XvncPluginTest.java

These pinned versions are so old that I doubt we are managing to install them successfully.

Unpin plugin versions

---

src/test/java/core/JenkinsDatabaseSecurityRealmTest.java

https://issues.jenkins.io/browse/JENKINS-49524 was fixed over a year ago.
Ran the test locally.

Re-enable category

---

src/main/java/org/jenkinsci/test/acceptance/plugins/build_timeout/BuildTimeout.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/po/User.java
src/main/java/org/jenkinsci/test/acceptance/po/View.java
src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
src/test/java/plugins/JobDslPluginTest.java

Remove more dead code

---

src/main/java/org/jenkinsci/test/acceptance/controller/JBossController.java
src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsLogWatcher.java
src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
src/main/java/org/jenkinsci/test/acceptance/controller/TomcatController.java
src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java
src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
src/main/java/org/jenkinsci/test/acceptance/plugins/docker_build_step/DockerCommand.java
src/main/java/org/jenkinsci/test/acceptance/plugins/mock_security_realm/MockSecurityRealm.java
src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java
src/main/java/org/jenkinsci/test/acceptance/po/WizardLogin.java
src/test/java/plugins/AuthorizeProjectTest.java
src/test/java/plugins/GerritTriggerTest.java
src/test/java/plugins/JabberPluginTest.java

Use native Java Platform functionality where possible.

Clean up usage of third-party libraries

---

src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java

Partially revert commit 4979b2e1652e846cb505cf13b0f628457e47cd18

---

pom.xml

Per the [LTS 2.462.3 release checklist](https://github.com/jenkins-infra/release/issues/594)
None.  Rely on ci.jenkins.io testing.

Use 2.462.3 in LTS profile

---

.github/renovate.json

Filter this file with `jq` to make it easier to edit in the future.

Format `renovate.json`

---

.github/renovate.json

Migrate `renovate.json`

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/po/LabelAxis.java

Adjust to https://github.com/jenkinsci/matrix-project-plugin/pull/213

Adjust to jenkinsci-matrix-project-plugin#213

---

pom.xml
src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java

https://github.com/jenkinsci/jenkins/pull/9835#issuecomment-2403432796

Upgrade to 2.480

---

src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/Script.java
src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/ScriptResult.java

Adapt to the latest release of Scriptler, which has renamed a few things. Tested locally by running `ScriptlerPluginTest` against the latest weekly.

Fix Scriptler tests

---

pom.xml

chore(lts): update lts in maven profile to 2.479.2

---

pom.xml

As part of the LTS release checklist for 2.479.3, updating the LTS version in the Maven profile of ATH.

chore(lts): update lts in maven profile to 2.479.3

---

pom.xml

Released  5 February 2025.
Changelog:
- https://www.jenkins.io/changelog/2.492.1/
Upgrade guide:
- https://www.jenkins.io/doc/upgrade-guide/2.492/
Release checklist:
- [2.492.1 LTS Release checklist](https://github.com/jenkins-infra/release/issues/644)
Relying on ci.jenkins.io to perform the testing.

Use Jenkins 2.492.1 in LTS profile

---

src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/ScriptResult.java

Simplify Scriptler test

---

pom.xml

Released 5 March 2025.
Changelog:
https://www.jenkins.io/changelog/2.492.2/
Upgrade guide:
https://www.jenkins.io/doc/upgrade-guide/2.492/#upgrading-to-jenkins-lts-2-492-2
Release checklist:
https://github.com/jenkins-infra/release/issues/651
Relying on ci.jenkins.io to perform the testing.

chore(maven): Use Jenkins 2.492.2 in LTS profile.

---

pom.xml

Released 02 April 2025.
Changelog:
https://www.jenkins.io/changelog/2.492.3/
Upgrade guide:
https://www.jenkins.io/doc/upgrade-guide/2.492/#upgrading-to-jenkins-lts-2-492-3
Release checklist:
https://github.com/jenkins-infra/release/issues/664
Relying on ci.jenkins.io to perform the testing.

chore(maven): Use Jenkins 2.492.3 in LTS profile.

---

pom.xml

As part of the LTS release checklist for 2.504.1, updating the LTS version in the Maven profile of ATH.

chore: update lts in maven profile to 2.504.1

---

pom.xml

Like jenkinsci/jenkins#5857, pending jenkinsci/pom#371.

`surefire.runOrder=alphabetical` for reproducibility

---

vars.cmd

Selenium will report the URL to use for BiDi connections based on its own hostname which is not reachable.
Pass the SE_NODE_GRID_URL to the container with the address the local manchine can reach it on (which is the same as the normal webdriver host:port)
on my windows setup tests fail in guice before this change with the following
```
[ERROR]   FormValidationTest.validate » Provision Unable to provision, see the following errors:
1) [Guice/ErrorInCustomProvider]: ConnectionFailedException: JdkWebSocket initial request execution error
Build info: version: '4.32.0', revision: 'd17c8aa950'
System info: os.name: 'Windows 11', os.arch: 'amd64', os.version: '10.0', java.version: '21.0.1'
Driver info: driver.version: unknown
at FallbackConfig.createWebDriver(FallbackConfig.java:336)
\_ …
```

Configure the Grid URL so that BiDi connections work

---

src/main/resources/ath-container/Dockerfile

Fixes #1641
Built the image locally.

Verify Maven checksum

---

docker-compose.yml

Fixes #2039
Local build; saw that cache was used.

Fix build caching

---

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java

https://issues.chromium.org/issues/42323769#comment23 
This causes a large number of tests to fail in Chrome.

Disable password manager leak detection in Chrome

---

src/main/java/org/jenkinsci/test/acceptance/plugins/email_ext/EmailExtPublisher.java

https://issues.jenkins.io/browse/JENKINS-75797
As the refactoring done in https://github.com/jenkinsci/email-ext-plugin/pull/618 changed some fields in the jelly file; I create this PR to add the new field names.
Tested locally.

[JENKINS-75797] Update test following email-ext plugin refactoring

---

pom.xml

As part of the LTS release checklist for 2.504.3, updating the LTS version in the Maven profile of ATH.

chore(lts): update lts in maven profile to 2.504.3

---

.github/renovate.json
pom.xml

Fixes #1098
Automate update of `jenkins.version` for LTS Maven profile.
I can follow-up with updates to the release checklist, if desired.
Tested on private repo.

Automate LTS profile updates via renovate

---

.github/renovate.json
pom.xml

Fix spotless for renovate updates

---

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/Dockerfile

Docker build of the relevant file; failed before this PR and passed after.

Buster is now archived

---

src/main/java/org/jenkinsci/test/acceptance/po/Job.java

Adjustment for https://github.com/jenkinsci/jenkins/pull/10913

Adjust for 'refine-hetero-list-add'

---

docs/BROWSER.md
src/main/java/org/jenkinsci/test/acceptance/Config.java
src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
src/main/java/org/jenkinsci/test/acceptance/guice/World.java
src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java

As of #2151 this isn't a fallback anymore. It's just the configuration.
CI build

Rename `FallbackConfig` to `Config`

---

src/test/java/plugins/AntPluginTest.java

fixes: #2168
None, my machine is not apparantly throttled by apache and the tests reliably pass :)

Increase timeout on ant plugin tests

---

.github/renovate.json
vars.cmd

adjust vars.cmd so it is also updated by renovate
