jenkinsci/acceptance-test-harness

pom.xml
When I am trying to run test harness with Firefox 36, I am getting:
```
org.openqa.selenium.firefox.NotConnectedException: Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms.
...
```
Latest selenium version 2.45.0 fixes this problem for me.
Changelog is here: http://selenium.googlecode.com/git/java/CHANGELOG
=> Bump selenium version to 2.45.0

src/test/java/plugins/SupportCorePluginTest.java
Requires https://github.com/jenkinsci/support-core-plugin/pull/31 to be merged and released before this test can be expected to pass (without `LOCAL_SNAPSHOTS=true`).
@reviewbybees
=> [JENKINS-27669] Demonstrate ClassCircularityError before fix

src/main/java/org/jenkinsci/test/acceptance/plugins/emma/EmmaResultsPage.java
This [PR](https://github.com/jenkinsci/jenkins/pull/1717) have modified DOM tree in the main layout. These changes affect to `side-panel` and `main-panel`. From now on, `div#main-panel-content` won't exist.
=> [JENKINS-28550] Test reviewed to work fine with the new proposal of side-panel and main-panel

src/main/java/org/jenkinsci/test/acceptance/plugins/analysis_core/AnalysisSettings.java, src/main/java/org/jenkinsci/test/acceptance/plugins/tasks/AbstractTaskScannerBuildSettings.java
Downstream of https://github.com/jenkinsci/analysis-core-plugin/pull/31
The configuration page for any Analysis Core derived plugin has now a different HTML selector for everything under the old section ```canComputeNew```. This intermediate selector level has been removed as ```inline="true"``` [has been added in the jelly file](https://github.com/jenkinsci/analysis-core-plugin/pull/31/files#r35576335).
@reviewbybees
=> [JENKINS-25977] Reflect analysis-core configuration page modifications

docs/FIXTURES.md, pom.xml, src/main/java/org/jenkinsci/test/acceptance/docker/Docker.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerFixture.java, src/test/java/org/jenkinsci/test/acceptance/docker/DockerFixtureTest.java, src/test/java/org/jenkinsci/test/acceptance/docker/DockerTest.java, src/test/resources/org/jenkinsci/test/acceptance/docker/DockerTest/TestContainer/Dockerfile, src/test/resources/test/Dockerfile
Create an attribute to set Dockerfile in @DockerFixture. This PR also fixes one small issue [JENKINS-29984](https://issues.jenkins-ci.org/browse/JENKINS-29984) but since it was found while writing a test for [JENKINS-29976](https://issues.jenkins-ci.org/browse/JENKINS-29976) it was difficult to split at that stage to two different commits because the bug was at the same class that I touched for implementing this feature. Since it is an small bug fix (support for inner classes for DockerFixture), I decided to not overcomplicate the development by removing/copyback the code.
I paste here the description of the issue:
```
Create attribute to set Dockerfile location in @DockerFixture. By default Dockerfile fixture should be placed in the resource directory and at the same package as …
```
=> [JENKINS-29976] Create an attribute to set Dockerfile in @DockerFixture 

src/test/java/plugins/WorkflowPluginTest.java
Consistently failing on CI as for example [here](https://jenkins.ci.cloudbees.com/job/core/job/acceptance-test-harness/1233/testReport/plugins/WorkflowPluginTest/linearFlow/) but I cannot reproduce the failure locally. Looks like the build is failing prior to `input`, but my mistaken code idiom prevents this build log from being shown in ATH test output.
@reviewbybees
=> Diagnose failures in WorkflowPluginTest.linearFlow

src/test/java/plugins/MavenPluginTest.java
[JENKINS-22252](https://issues.jenkins-ci.org/browse/JENKINS-22252)
@reviewbybees
=> [JENKINS-22252] Reproduced problem in test

src/test/java/plugins/WorkflowPluginTest.java
With #42 merged, I can see that the problem is a [weird Maven error](http://stackoverflow.com/q/29983683/12916); apparently the CI job is defining `M2_HOME`, so we are forced to override it. Using `withEnv` is more the [recommended idiom](https://github.com/jenkinsci/workflow-plugin/blob/master/TUTORIAL.md#managing-the-environment) anyway.
@reviewbybees
=> Diagnosed failure in WorkflowPluginTest.linearFlow

src/test/java/plugins/GradlePluginTest.java
GradlePluginTest class contains a regular expression that is gradle --quiet but under some circumstances the output does not contain gradle --quiet but _ "..../gradle\" --quiet hello put quotes because of white space in the path. For this reason a new regular expression should be provided to fix this possibility.
@reviewbybees
=> [FIXED JENKINS-31031] incorrect matcher in GradlePluginTest.

src/test/java/plugins/JUnitPluginTest.java
In JunitPluginTest class test, the publish_rest_of_parameterized_tests test method fails because it complains that there is no tests to show when in reality there are some executions. Probably this is because of sync problem. Inspecting the code I have seen:
```java
toggle(test);
elasticSleep(1000); // Try to wait a bit to ajax to fetch the content
assertThat(driver, hasContent(msg));
toggle(test);
```
The test failure occurs in the first toggle, but as you can see there is an elasticSleep just after, so originally this test had some problems of sync. Probably we need to add an elasticSleep before first toggle as well.
@reviewbybees
=> [FIXED JENKINS-31049] adds an sleep before toggle.

src/test/java/plugins/GerritTriggerTest.java
Some test Gerrit instances may not have SSL setup correctly. This patch permits this.
Also, some logging was duplicated due to a @Before class mistake.
=> Permit insecure curl connections and fix logging

src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java, src/main/java/org/jenkinsci/test/acceptance/recorder/JUnitScreenRecorder.java
ScreenRecorder shall be JUnitAttachment aware by implementing https://wiki.jenkins-ci.org/display/JENKINS/JUnit+Attachments+Plugin#JUnitAttachmentsPlugin-ByprintingoutthefilenameinaformatthatJenkinswillunderstand so the videos could be got from any execution.
@reviewbybees
=> [FIXED JENKINS-31081] Adding JUnit Attachment support to screen recorer

src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
Running Recorder tests might fail if the Jenkins node where the test is run overrides the RECORDER property. To fix this an override of a possible variable should be done.
@reviewbybees
=> [FIXED JENKINS-31065] Override RECORDER property

src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
I have tests that controls two jenkins masters at the same time, so there is a need to be able to specify what socket the controller should use.
@reviewbybees
=> Need to be able to specify the socket

docs/INVESTIGATION.md, src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java
Hotfix incorporating parts of #54 but allowing the existing tests to run whether we are using 1.10.1 (plain text area) or 1.11-beta-3+ (ACE editor).
#54 should be adjusted to do this more cleanly somehow TBD, as well as add its tests specific to ACE using `@WithPlugins("workflow-aggregator@1.11")`.
@reviewbybees esp. @tfennelly
=> [JENKINS-28769] Allow Workflow tests to run with or without ACE

src/test/java/plugins/PrioritySorterPluginTest.java
[[JENKINS-31738]](https://issues.jenkins-ci.org/browse/JENKINS-31738)
* Make PrioritySorterPluginTest#match_jobs_by_view more deterministic by enabling build execution after the test is completely configured, as is done in #match_jobs_by_name.
* Rename some local variables that had misleading names.
@reviewbybees
=> [JENKINS-31738] Review PrioritySorterPluginTest#match_jobs_by_view

src/main/java/org/jenkinsci/test/acceptance/steps/AbstractSteps.java
If ATH is used externally and a class extends AbstractSteps, then the class
should have access to 'jenkins'
=> Allow AbstractSteps to be used outside of ATH

src/test/java/plugins/WarningsPluginTest.java
WarningPluginTest fails when showing the axis of all warning in the details section. In summary section you can see that there is 12 warnings but in the details section only 11 are shown. If you execute this test locally it works, so probably it can be a problem of refresh.
https://issues.jenkins-ci.org/browse/JENKINS-31431
@reviewbybees
=> [FIXED JENKINS-31431] Warning Axis Test refresh browser

src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java
[JENKINS-31357](https://issues.jenkins-ci.org/browse/JENKINS-31357)
Happens on Mac.
=> [Fixed JENKINS-31357] TestRecorderRule to handle HeadlessException

README.md, docs/CONTROLLER.md, docs/SUT-VERSIONS.md, src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/main/java/org/jenkinsci/test/acceptance/update_center/CachedUpdateCenterMetadataLoader.java, src/main/java/org/jenkinsci/test/acceptance/update_center/DownloadOverrideUpdateCenterMetadataDecorator.java, src/main/java/org/jenkinsci/test/acceptance/update_center/LocalOverrideUpdateCenterMetadataDecoratorImpl.java, src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java, src/main/java/org/jenkinsci/test/acceptance/utils/aether/ArtifactResolverUtil.java
User can suggest plugin version using for example `git.version=1.42` to override latest. Much like `git.jpi` works.
=> Download plugin by version

docs/BROWSER.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
For example the selenium/standalone-firefox-debug docker image.
@reviewbybees
=> Add posibility to use remote webdriver as a browser

src/test/java/plugins/SubversionPluginTest.java
[JENKINS-32477](https://issues.jenkins-ci.org/browse/JENKINS-32477)
* Stop using deprecated method <code>org.jenkinsci.test.acceptance.po.Build.shouldContainsConsoleOutput</code>
* Use <code>elasticSleep</code> method to fix test that fails. DOM tree is not regenerated fast enough.
@reviewbybees
=> [JENKINS-32477] Stop using deprecated methods and test fix

pom.xml
Needed to support -Dsurefire.rerunFailingTestsCount. Doesn't work in 2.17.
https://maven.apache.org/components/surefire/maven-surefire-plugin/examples/rerun-failing-tests.html
@reviewbybees
=> Upgrade to surefire 2.18

src/main/groovy/org/jenkinsci/test/acceptance/po/users/AddUserPage.groovy, src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java, src/main/java/org/jenkinsci/test/acceptance/po/Slave.java, src/test/java/plugins/OwnershipPluginTest.java
Attn @olivergondza 
The only test failure difference from my initial run against master is `SubversionPluginTest.clean_checkout:199`:
```
SubversionPluginTest.clean_checkout:199 
Expected: Build result SUCCESS
but: was FAILURE. Console output:
Started by user anonymous
Building in workspace /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace
Cleaning up /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace/.
Deleting /home/tfennelly/projects/acceptance-test-harness/target/jenkins8920358853420174796home/jobs/convenient_advertising/workspace/unversioned.txt
Updating http://127.0.0.1:32883/svn at revision '2016-04-01T20:13:53.243 +0100'
At revision 2 …
```
=> More Jenkins 2.0 test fixes

src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
See [JENKINS-34004](https://issues.jenkins-ci.org/browse/JENKINS-34004).
Adds a local user and email to the created repos. This makes the tests pass even if the global config is not set.
@reviewbybees
=> [JENKINS-34004] Add identity configuration when creating repo.

src/main/java/org/jenkinsci/test/acceptance/msbuild/MSBuildInstallation.java
Follow up on #83,  review completed 12 days ago. Merged today.
#89  merged 11 days ago, included a modification in the constructor of `ToolInstallation` from which `MSBuildInstallation` extends. 
Today #83 has been merged and build failed because the constructor that existed when the PR was under discussion has been modified. This PR fixes the issue.
@reviewbybees
=> Fix ATH broken build after PR#83 merged

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/ArtifactoryContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JabberContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/LdapContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SMBContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshdContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SvnContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat7Container/Dockerfile
Run another command on the same line to make sure that doesn't happen.
We're hitting this on an internal test run where there's a stale apt cache on an image and this is the best workaround I can find.
See https://github.com/docker/docker/issues/3313 
=> apt-get update alone can lead to Docker caching the results.

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Fixes a ton of job creation failures on Linux - doesn't make a
difference on OS X, and there are still a number of failures mentioned
in the JIRA that are credentials-related, but this is real progress.
cc @reviewbybees @recena @uhafner @olivergondza
=> [JENKINS-35134] Ensure no focus lib is used for Firefox.

src/test/java/plugins/AntPluginTest.java
[JENKINS-31060](https://issues.jenkins-ci.org/browse/JENKINS-31060)
I just don't see the point of this test in the first place - it's too
hard to control for environment to be worth keeping around.
=> [FIXED JENKINS-31060] Removing AntPluginTest.locallyInstalledAnt()

src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
[JENKINS-35307](https://issues.jenkins-ci.org/browse/JENKINS-35307)
Note - still fails on 2.x due to the more general ATH job creation problems, but fixed on 1.651.2.
=> [FIXED JENKINS-35307] Explicit selection of copy radio button needed.

src/test/java/plugins/MavenPluginTest.java
This test doesn't serve any real purpose, a la JENKINS-31060, and is
erratic in its behavior depending on test environment. So - remove it.
=> [FIXED JENKINS-35446] Remove MavenPluginTest.use_native_maven

src/main/java/org/jenkinsci/test/acceptance/guice/Cleaner.java
For instance, you could have some clean up relying on the WebDriver
which is initialized before. It should be cleaned up after.
https://issues.jenkins-ci.org/browse/JENKINS-35334
@reviewbybees
=> [FIXED JENKINS-35334] Decorators should be cleaned up in reverse order.

src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneDockerController.java, src/main/java/org/jenkinsci/test/acceptance/docker/Docker.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainerHolder.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java, src/main/java/org/jenkinsci/test/acceptance/junit/FailureDiagnostics.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SMBContainer/Dockerfile
- Log `docker run` and `docker build` separately into diagnostics directory.
- Introduce builder for `DockerImage` starting to keep the signatures sane.
- As a bonus, make sure `cid` file gets deleted.
@reviewbybees esp. @jtnord
=> Put Docker logs in diagnostics dir

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/FileCredentials.java, src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/StringCredentials.java, src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/CredentialsBinding.java, src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/ManagedCredentialsBinding.java, src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/SecretFileCredentialsBinding.java, src/main/java/org/jenkinsci/test/acceptance/plugins/credentialsbinding/SecretStringCredentialsBinding.java
`PageArea`s and `PageObject`s for `plain-credentials` and `credentials-binding` plugins so that acceptance tests can be written for them.
@reviewbybees
=> PageArea/PageObjects for plain-credentials and credentials-binding

src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java
The half-second sleep seems to hit race conditions periodically,
especially if the host is under load. Moving it to a second got rid of
the issues in my testing - from seeing it error out due to an empty
cidfile roughly half the time in 10 tests to zero times in 10 tests.
=> [FIXED JENKINS-36045] Bump sleep for waiting for cidfile

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java
[JENKINS-35275](https://issues.jenkins-ci.org/browse/JENKINS-35275)
The proposed fix tries to make the ATH upgrade policy the same as the one in real Jenkins. See ticket for better explanation.
@olivergondza your input here would be much appreciated. Thanks.
@reviewbybees
=> [JENKINS-35275] Don't force unneccessary dependencies to get upgraded in ATH

src/main/java/org/jenkinsci/test/acceptance/plugins/subversion/SubversionScm.java
https://issues.jenkins-ci.org/browse/JENKINS-36116
If multiple SCMs are installed, hardcoding to a specific radio button number doesn't work, so here's a more specific xpath.
cc @reviewbybees @olivergondza
=> [FIXED JENKINS-36116] Select SVN advanced button based on siblings.

docs/BROWSER.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, vnc.sh
ATH now takes the display for browser from `BROWSER_DISPLAY` property. The advantage compared to propagating plain old `DISPLAY` from shell exported envvar (that worked before) is it will not affect any other UI applications launched from the shell.
=> Automate vnc setup for local testing

pom.xml
1.1.0 doesn't work with current Selenium versions.
=> Use a current phantomjsdriver version.

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java, src/main/java/org/jenkinsci/test/acceptance/po/Control.java
Supersedes #133 
@olivergondza I have closed #133 since it is no longer relevant.
@reviewbybees esp @amuniz @recena @kwhetstone
=> [JENKINS-36046] Correct parent path for credentials. 

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
If we only click the first one, we're vulnerable if there's more than
one on the configure page, as could be the case depending on plugins
installed. To be safe, let's click all of the visible Advanced buttons
- we're not going to break anything by doing so, just increase visibility.
I tried to figure out a way to explicitly find the Advanced Project
Options advanced button, but I don't know xpath well enough to ensure
I get the right sibling of the <tr> that contains the Advanced Project
Options string, so...brute force!
=> [FIXED JENKINS-36125] Expand all Advanced when testing custom workspace

src/main/groovy/org/jenkinsci/test/acceptance/po/users/AddUserPage.groovy
https://issues.jenkins-ci.org/browse/JENKINS-35443
The title for either addUser or signup is always "Sign up" in 1.x,
at least in 1.651, but in 2.x, the title varies depending on whether
you're hitting the addUser endpoint or the signup endpoint. Since we
want the addUser endpoint, looking for a title of "Sign up" breaks on
2.x, while looking for a title of "Create user" (the one we get on the
right endpoint on 2.x) fails on 1.x.
So - instead, verify we're on the right page by looking for
"createAccountByAdmin" as the form action, since that's consistent and accurate.
cc @reviewbybees @olivergondza
=> [FIXED JENKINS-35443] Look for form action, not title.

src/main/java/org/jenkinsci/test/acceptance/docker/Docker.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainerHolder.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java
Also effectively rolls back 74ec1821ced1d2ef2b2567e92e699117370ff1bf
as unneeded.
NOTE: Don't merge this until I've had a chance to run a few more full runs to be sure it's doing the trick - it certainly appears to be fixing things so far, but I've been bit by false positives on this issue before. =) It's still just a band-aid at the core - I can't for the life of me figure out why it's happening in the first place, but this is the best workaround I've got yet.
EDIT:
I've left the retry in for now, but may end up opting to remove it entirely. The new approach (as described below) reworks how we get the container ID and logs entirely and doesn't seem to run into problems.
```
More testing needed to verify this actually does the trick
consistently, but it does *work* in the non-failure case …
```
=> [JENKINS-36045] Rework acquiring Docker CID.

src/main/java/org/jenkinsci/test/acceptance/po/Build.java
Since we don't visit the build page anymore once the build is started,
it is not useful to go to the Jenkins home page. Especially since the
method getJenkins() is not fully implemented (doesn't work if there are
several Jenkins instance in injector)
=> Don't visit Jenkins home page after scheduleBuild

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
We've had a lot of problems with scrolling to check
matrix/credentials/etc fields, which are...annoying. And fairly
pointless to work on, frankly. I'd strongly advocate for instead
allowing configurability of window geometry - I'd've thought that the
maximize call would do the trick on its own with a larger Xvnc
geometry, but it didn't - in fact, it seems to do absolutely *nothing*
when run inside Xvnc.
So instead, let's just suck it up and bump the minimum window size to
an admittedly silly-large 1680x1050. Selenium does fine with detecting
visibility of parts of the window that are off the screen, so a
smaller screen than 1680x1050 causes no problems.
I'd be open to a smaller width too, but definitely bigger than
1280x960, the previous minimum.
This replaces #145.
As always, cc …
=> Make minimum browser window size larger.

src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java
[JENKINS-36321](https://issues.jenkins-ci.org/browse/JENKINS-36321)
The issue reported is not easily reproduced.
My theory is that the error stems from an inconsistent UpdateCenter metadata: we get a NullPointerException when trying to install a plugin which is present as a dependency of another one, but actually not present in the UC metadata.
One thing we can do is to control this error and throw a proper exception if that happens. We were already validating that a plugin exists before trying to install it, but we were not doing so with the plugins declared as dependencies.
@reviewbybees esp @armfergom
=> [JENKINS-36321] Extra check when trying to install dependencies

src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainerHolder.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerFixture.java, src/main/java/org/jenkinsci/test/acceptance/docker/DockerImage.java, src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/FtpdContainer/Dockerfile, src/test/java/plugins/FtpPublishPluginTest.java
Fix for [JENKINS-34614](https://issues.jenkins-ci.org/browse/JENKINS-34614).
Several factors were preventing the connection to the ftp server:
1. Due to how FTP protocol works ([details here](http://www.slacksite.com/other/ftp.html)) we need an exact match of container and host ports. If anyone knows another solution please comment.
2. We needed to force the 'passive' ip/host in the ftp server.
My proposed solution to address (1) is to add a new boolean property `matchHostPorts` in the `DockerFixture` annotation, which when true will force an exact port mapping between docker container and host.
Also modified the `FtpdContainer`'s `Dockerfile` to fix the ubuntu version, and to address (2).
@reviewbybees esp @abayer, @olivergondza
=> [JENKINS-34614] Fix for ftpd container connectivity problems

src/test/java/plugins/ArtifactoryPluginTest.java
Solves [Issue JENKINS-36392](https://issues.jenkins-ci.org/browse/JENKINS-36392).
It seems that the expected message was incorrect/outdated. Fixed to the string that Jenkins actually returns.
@reviewbybees
=> [JENKINS-36392] Fix ArtifactoryPluginTest#check_config_is_persisted

src/test/java/plugins/ArtifactoryPluginTest.java
[JENKINS-35646](https://issues.jenkins-ci.org/browse/JENKINS-35646)
It seems like the test fails due to some groovy versions issue: looks like the ArtifactoryPlugin was built with a groovy version 2.3+, and when we try to launch a job using gradle 1.12 (older groovy) we get the error described here: http://www.groovy-lang.org/mailing-lists.html#nabble-td5720557.
So using gradle 2.0 in the test makes it work, but probably this is a real bug if we want to support past gradle versions (1.X). So should we open an issue for this? If so, where exactly?
EXTRA INFO:
The dependency of gradle with the artifactory plugin seems to stem from an gradle init-script which is autogenerated using a template (see [ArtifactoryGradleConfigurator](https://github.com/jenkinsci/artifactory-plugin/blob/08ea6585e78 …
=> [JENKINS-35646] Fix ArtifactoryPluginTest.gradle_integration failure

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
[JENKINS-36469](https://issues.jenkins-ci.org/browse/JENKINS-36469)
In the case the button is sticky this PR does not scroll before clicking it, in other case the functionality is the existing one
@reviewbybees
=> [JENKINS-36469] CapybaraPortingLayerImpl.clickButton() has problems with vertical scroll and sticky buttons

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile
[JENKINS-35644](https://issues.jenkins-ci.org/browse/JENKINS-35644)
Fix for JiraPluginTest. The problem is that the fixture was using always the latest JIRA version available, but from 7.0 the JIRA SOAP API was gone.
The test set up was trying to interact with the JIRA through this missing API, hence the failure. I've pinned down the docker fixture to 6.3, and the test now succeeds.
@reviewbybees
=> [JENKINS-35644] Fix JiraPluginTest

src/main/java/org/jenkinsci/test/acceptance/plugins/ant/AntInstallation.java, src/test/java/plugins/AntPluginTest.java
[JENKINS-31060](https://issues.jenkins-ci.org/browse/JENKINS-31060)
Proposal to bring back the test previously removed, with some modifications to make it work.
The original error was due mainly to:
1. an inconsistent setup of PATH and ANT_HOME env variables,
2. how ant is "too smart" when looking for an "ANT_HOME" variable
3. how we are also being smart enough at setting up a fake home for tool installations (see [ToolInstallation.java](https://github.com/jenkinsci/acceptance-test-harness/blob/c1512e4da9dc3b4dd701988dae103eaec405ec25/src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java#L123)).
In this test "the user" is entering the ANT_HOME (fake home) which jenkins must use for the build. I think that if the test uses this exact same ant script to set the expected …
=> [JENKINS-31060] - AntPluginTest does not work if ANT_HOME set

src/main/java/org/jenkinsci/test/acceptance/plugins/ant/AntInstallation.java
Follow up to [PR-156](https://github.com/jenkinsci/acceptance-test-harness/pull/156).
Related to issue [JENKINS-31060](https://issues.jenkins-ci.org/browse/JENKINS-31060).
The fix introduced in the previous PR solves the issue reported, but still I found some setups where some ant bug (see http://stackoverflow.com/questions/2336299/what-is-wrong-with-my-ant-configuration) raises if the ANT_HOME variable is not present and the ant script itself tries to guess it, and we are blanking it in [ToolInstallation.java](https://github.com/jenkinsci/acceptance-test-harness/blob/c1512e4da9dc3b4dd701988dae103eaec405ec25/src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java#L123) when we create a fake home.
So the test will be more resilient if we use ANT_HOME when present, and only …
=> [JENKINS-31060] make AntPluginTest use ANT_HOME if present

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java, src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
Reopened [JENKINS-35307](https://issues.jenkins-ci.org/browse/JENKINS-35307) to make the test work for Jenkins `2.x` as well.
Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/112.
@reviewbybees esp @abayer @recena @tfennelly
=> [JENKINS-35307] Discriminate Jenkins version for certain UI aspects when creating/copying jobs

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java
[JENKINS-37232](http://issues.jenkins-ci.org/browse/JENKINS-37232)
Firefox has an issue sending blur events when running the ATH. This simulates the blur event for a specific field that needs it during item creation.
@reviewbybees
=> [FIXED JENKINS-37232] - starting with 2.7 the ATH began to fail during create item

src/test/java/plugins/WorkflowPluginTest.java
Requires https://github.com/jenkinsci/junit-plugin/pull/53 to actually pass.
@reviewbybees esp. @kohsuke
=> [JENKINS-29922] Testing use of symbols in a realistic context

src/test/java/plugins/WorkflowPluginTest.java
Complements https://github.com/jenkinsci/pipeline-input-step-plugin/pull/2 by being more robust against JENKINS-37154-related behavior. Would benefit from https://github.com/jenkinsci/workflow-cps-plugin/pull/40.
@reviewbybees
=> Wait for the agent to come back online before we even try to resume the build

src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java, src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java
Proposal for [JENKINS-37615](https://issues.jenkins-ci.org/browse/JENKINS-37615).
Save page object context when received in constructor, and use it later to find the real Jenkins instance associated with the element, if available.
@reviewbybees
=> [JENKINS-37615] Honor context PageObject when looking for Jenkins instance

src/test/java/plugins/WorkflowPluginTest.java
Downstream of https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/9.
@reviewbybees
=> [JENKINS-26192] Demonstrating @Grab support in a realistic class loader environment

src/main/java/org/jenkinsci/test/acceptance/po/FolderItem.java, src/main/java/org/jenkinsci/test/acceptance/po/Job.java, src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java, src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
[JENKINS-38058](https://issues.jenkins-ci.org/browse/JENKINS-38058)
Passing context page object to folders so that we can retrieve the real Jenkins instance later on
@reviewbybees
=> [JENKINS-38058] pass context when creating 'FolderItem' objects

src/main/java/org/jenkinsci/test/acceptance/plugins/external_workspace_manager/ExternalNodeConfig.java
The External Workspace Node property was renamed from `localRootPath` to `nodeMountPoint`.
CC @oleg-nenashev @martinda
=> Fix property renaming from localRootPath to nodeMountPoint

src/main/java/org/jenkinsci/test/acceptance/junit/WithOS.java
[JENKINS-38684](https://issues.jenkins-ci.org/browse/JENKINS-38684)
Fix `@WithOS` annotation to work properly when multiple OS given
@reviewbybees
=> [JENKINS-38684] fix @WithOS when several OSes passed

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/199
@reviewbybees
=> [JENKINS-38974] Required version can be null

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/po/Job.java, src/test/java/core/PublisherOrderTest.java
[JENKINS-37276](https://issues.jenkins-ci.org/browse/JENKINS-37276)
Downstream of [PR-5](https://github.com/jenkinsci/form-element-path-plugin/pull/5)
I am not very sure about the `getText().contains` part, but as long as I see I only have four alternatives:
* The `getText().contains` one
* Modify @Describable value in the same way that the proposed by #162 
* Implement any other suggestion
* Let the things like they are because there is a very easy workaround for the bug
Option 2 seems not to have a lot of supporters given the time the PR has been open without activity
I am open to option 3 as soon as I receive a better alternative approach
I am also open to option 4 if anyone considers that this bug is not important or worth the risk
@reviewbybees specially @jglick 
Also @olivergondza …
=> [JENKINS-37276] Path atributes can change values if reordered

src/test/java/plugins/KerberosSsoTest.java
- make use of GlobalPluginConfiguration for plugin global config
- fix potential problem with BasicAuth test by resetting http client
=> Fix KerberosSsoTest when running with many plugins

src/main/java/org/jenkinsci/test/acceptance/plugins/artifactory/ArtifactoryPublisher.java, src/test/java/plugins/ArtifactoryPluginTest.java
- Update maven_integration test to enter repos directly.
- Due to JENKINS-39323, we are skipping the gradle_intregration test.
=> Fix Artifactory plugin maven test and ignore Gradle test

src/test/java/plugins/ArtifactoryPluginTest.java
- rely on default timeouts to allow for slower instances where
many plugins are installed.
=> Remove fixed timeouts for Artifactory Test

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
For instances where a large number of plugins are installed,
5 seconds may not be long enough for apply operation to complete.
Adjusting to 30 seconds.
=> Adjust timeout for Apply on job.apply()

docs/FIXTURES.md, src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainer.java
[JENKINS-39716](https://issues.jenkins-ci.org/browse/JENKINS-39716)
Support running ATH as docker container. Connect to docker fixtures through docker IPs instead of using host port-mappings.
For the moment, an environment variable SHARED_DOCKER_SERVICE is used to select this behaviour. Maybe in the future try to detect the situation automatically.
@reviewbybees
=> [JENKINS-39716] adapt docker tests execution when ATH itself runs as docker container

src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java, src/main/java/org/jenkinsci/test/acceptance/update_center/Dependency.java, src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java, src/main/java/org/jenkinsci/test/acceptance/utils/pluginreporter/ConsoleExercisedPluginReporter.java, src/test/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadataTest.java
Adding test coverage for dependency resolution as a response to #216 and #217, which I am not able to reproduce.
It is expected that the hot-deploy (*Failed to dynamically deploy this plugin*) fail in case the plugin already exists so it needs to be updated or plugin depends on plugin that needs to be updated. Throwing `LinkageError`s is not expected but it occurs due to bug in Jenkins core [JENKINS-40036](https://issues.jenkins-ci.org/browse/JENKINS-40036). The former situation is recognized and Jenkins is restarted to correctly resolve dependencies. The later situation is not detected but is usually accompanied by the former so Jenkins manages to recover. In case ATH does not restart Jenkins in these situations or the exceptions are present after the restart, it is a bug in ATH. But I …
=> Test dependency resolution

src/main/java/org/jenkinsci/test/acceptance/utils/groovy/InteractiveConsole.java
In practice it is an annoyance to have to handle or rethrow `InterruptedException` when you are temporarily adding a break to a method which did not already throw this.
@reviewbybees
=> Make InteractiveConsole.execute throw no checked exceptions

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
Cf. https://github.com/jenkinsci/ssh-slaves-plugin/pull/37. Both unused (according to my GitHub search), and wrong as https://github.com/jenkinsci/jenkins/pull/2633.
@reviewbybees
=> Deprecating getSlaveJarPath

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java, src/test/java/plugins/SshSlavesPluginTest.java
While trying to reproduce https://github.com/jenkinsci/ssh-slaves-plugin/pull/37,
@reviewbybees
=> [JENKINS-40092] Ensuring SshSlavesPluginTest can be run

src/main/java/org/jenkinsci/test/acceptance/plugins/foreman_node_sharing/ForemanSharedNodeCloudPageArea.java, src/test/java/plugins/ForemanNodeSharingPluginTest.java
- Adjust time execution wait times
- Adjust NodeProvisioner init times
- Adjust selector for Test Connection when many plugins present.
=> Foreman Node Sharing Fixes

src/main/java/org/jenkinsci/test/acceptance/plugins/publish_over/PublishOverSSHGlobalConfig.java
Fix for [JENKINS-40499](https://issues.jenkins-ci.org/browse/JENKINS-40499).
The `addAdvancedConfig` isn't actually creating a page area, just extending an existing one with more fields, so the `createPageArea` method call doesn't fit here.
@reviewbybees
=> [JENKINS-40499] Fix PublishOverSSHGlobalConfig#addAdvancedConfig

src/test/java/plugins/WorkflowMultibranchTest.java
[JENKINS-40476](https://issues.jenkins-ci.org/browse/JENKINS-40476)
Request 1.4 version of Javadoc plugin so there is no failure when used within a Pipeline.
@reviewbybees
=> [JENKINS-40476] WorkflowMultibranchTest#testMultibranchPipeline is failing

pom.xml
@olivergondza @uhafner @jenkinsci/code-reviewers 
Rationale:
* Selenium 3.x requires it
* The core is on its way to Java 8
* Java 8 \o/
See also https://groups.google.com/forum/#!msg/jenkinsci-dev/ckHjD6es4KQ/F7DfD7bQAQAJ
@reviewbybees
=> Update ATH to JDK 8 compiler settings

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
When Tests are executed with a "large" number of plugins,
the job configure page may display a script timeout in FireFox.
We adjust this to be more lenient.
=> Ensure Firefox doesn't throw script timeout for tests with many plugins

src/test/java/plugins/DiskUsagePluginTest.java
[JENKINS-40996](https://issues.jenkins-ci.org/browse/JENKINS-40996)
The job page needs to be opened after accessing disk-usage plugin configuration.
@reviewbybees
=> [JENKINS-40996] Fix DiskUsagePluginTest#show_graph_on_project_page test

src/test/java/plugins/JobConfigHistoryPluginTest.java
[JENKINS-41023](https://issues.jenkins-ci.org/browse/JENKINS-41023)
Wrong xpath was making the test to fail.
@reviewbybees
=> [JENKINS-41023] Fix JobConfigHistoryPluginTest#show_difference_in_config_history test

src/test/java/plugins/KerberosSsoTest.java
Without an email address, the sign up process fails. This leaves the instance without
the user that is required for the tests. The consequence is that the test will popup
a dialog waiting for simple authentication and will hang forever.
=> Fix user creation by supplying an email address

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
[JENKINS-41310](https://issues.jenkins-ci.org/browse/JENKINS-41310)
Fixing the name of the header so that ATH is able to get Jenkins version correctly. Otherwise, Jenkins instance is not recognised and no test can be run.
=> [JENKINS-41310] Fix name of X-Jenkins header.

src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java, src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java, src/test/java/plugins/AntisamyMarkupFormatterTest.java
[JENKINS-41484](https://issues.jenkins-ci.org/browse/JENKINS-41484)
Acceptance test for Antisamy Markup Formatter plugin.
Also includes the possibility of changing the Markup Formatter in Global Security config as well as setting a description for TopLevelItem (Folders and Jobs).
@reviewbybees
=> [JENKINS-41484] Create test for antisamy-markup-formatter plugin

src/main/java/org/jenkinsci/test/acceptance/po/Folder.java
Part of the changes once introduced with [JENKINS-38058](https://issues.jenkins-ci.org/browse/JENKINS-38058) have been removed in a recent commit (02c3799d89681b2447cffaa5380f45f803db9959).
This brings back a constructor, used in projects that depend on this ATH.
@reviewbybees 
@olivergondza please, if this is accepted and merged, I'd kindly ask to release a new version as well so we can pick up the change in depending projects.
=> [JENKINS-38058] bring back lost constructor for 'Folder'

src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
Fixes a wrong comment introduced by [PR #263](https://github.com/jenkinsci/acceptance-test-harness/pull/263) 
@reviewbybees
=> [JENKINS-41484] Fix wrong comment in Javadoc

src/test/java/plugins/WorkflowMultibranchTest.java
Trivial test failure from @stephenc’s recent refactorings.
@reviewbybees
=> Updated to SCM API 2.x labels.

src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java, src/test/java/plugins/GitUserContentTest.java
[JENKINS-41796](https://issues.jenkins-ci.org/browse/JENKINS-41796)
Acceptance test for git-userContent plugin (and indirectly for git-server plugin). 
One job clones the repo and pushes some changes. Other job (therefore other workspace) clones again the repo and verifies the changes done by the first one are there.
@reviewbybees
=> [JENKINS-41796] Create acceptance test for git-userContent

src/main/java/org/jenkinsci/test/acceptance/docker/DockerContainerHolder.java, src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer.java, src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/entrypoint.sh, src/test/java/plugins/WorkflowPluginTest.java
@mafraba found that this test could fail in a Dockerized test environment and tried to work around this by running the test environment with `-v /tmp`, without success. At root the problem was the unrealistic structure of the test, in which the build was being run on master, using the test environment’s own filesystem; and the consequent attempt to work around JENKINS-36997 by using `/tmp` for the workspace, which will not generally be available in a sibling container. To make it all work I had to switch to running the build in an agent container (linked to the Git container) accessing the host Docker daemon, a supported (indeed recommended) mode for `docker-workflow`, which does not trigger JENKINS-36997 since the workspace path is guaranteed to be short.
@reviewbybees
=> WorkflowPluginTest.sshGitInsideDocker overhaul

src/main/java/org/jenkinsci/test/acceptance/po/Build.java
Otherwise the call doesn't work with secured Jenkins instance.
=> Use the selenium driver to retrieve the console text

pom.xml
This failed the build, so reveals an issue. We need to work on understanding the failure this upgrades causes. I will refile a PR with that change and see if we can fix the failures.
Reverts jenkinsci/acceptance-test-harness#286
@reviewbybees
=> Revert "Update to latest parent jenkins:1.37"

src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackSlaveTemplate.java, src/test/java/plugins/OpenstackCloudPluginTest.java
- some tenants have more than 1 network and without a network
selected will result in an exception resembling "Multiple networks...please select
a network ID"
=> Add NetworkID activation parameter

src/main/java/org/jenkinsci/test/acceptance/plugins/openstack/OpenstackCloud.java
- need to better locate Test Connection button
when running test with many plugins.
=> Fix testConnection test in OpenstackCloudPluginTest

src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java
When ATH is run against downstream update center with plugins missing, the
tests will be correctly skipped. This also permits upstream tests for
plugins that are not distributed in upstream UC while they are in the
downstream one.
=> Skip tests explicitly requesting plugins not in update center

pom.xml
- I've been getting this dependency failing to download correctly under different versions of Maven
Safer to switch to a deployment on Maven
- This is particularly a problem when running the acceptance tests from within a docker container such as with https://github.com/jenkinsci/acceptance-test-harness/pull/238
@reviewbybees
=> Use a Monte Screen Recorder from Central

docs/PRELAUNCH.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/server/JenkinsControllerPoolProcess.java, src/main/java/org/jenkinsci/test/acceptance/server/PooledJenkinsController.java
jut-server already has the option to change the file name using the command line option -socket. However, the client (i.e. the unit test) does not have this option yet. This PR adds a new environment variable SOCKET that makes the socket configurable on both sides.
=> Make name of jut-server socket file configurable for the test runner.

src/main/java/org/jenkinsci/test/acceptance/po/ListView.java, src/main/java/org/jenkinsci/test/acceptance/po/View.java, src/main/java/org/jenkinsci/test/acceptance/steps/ViewSteps.java
ATH regression probably due to https://github.com/jenkinsci/jenkins/pull/2772 in 2.50.
Untested.
Probably safer to go with `Schedule a` instead?
=> [JENKINS-34522] Adapt to change in case

src/main/java/org/jenkinsci/test/acceptance/plugins/ldap/SearchForGroupsLdapGroupMembershipStrategy.java
[JENKINS-44130](https://issues.jenkins-ci.org/browse/JENKINS-44130)
Updated the `Describable` value to properly reflect the new caption of the field added in [this commit](https://github.com/jenkinsci/ldap-plugin/commit/0633afcd053254b38ee0d172c4e81c76d486640c#diff-8214e35f22e690a47c1358a68bc4dc1bR2)
I know there is an existing [PR](https://github.com/jenkinsci/acceptance-test-harness/pull/305/files) to increase test coverage for `1.15` but that PR is much broader in scope and AFAIK does not solve this issue, so I believe is compatible with this. This as a quick fix for the existing tests and the other as an enhancement for the ATH
@reviewbybees
=> [JENKINS-44130] LdapPluginTest failing with ldap 1.15

src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java, src/main/resources/org/jenkinsci/test/acceptance/selenium/scroller.js
See [JENKINS-44232](https://issues.jenkins-ci.org/browse/JENKINS-44232)
Supersedes #310 
@olivergondza this solution takes into account horizontal scrolling. I think this is better than the previous approach, and needed for this and other tests that need horizontal scrolling.
@reviewbybees
=> [JENKINS-44232] Consider horizontal scrolling too

src/main/java/org/jenkinsci/test/acceptance/po/LabelAxis.java
[JENKINS-44362](https://issues.jenkins-ci.org/browse/JENKINS-44362)
Test is flaky: sometimes when expanding the tree is necessary to look for the element, the click in actually tried before the checkbox is displayed.
@reviewbybees esp. @raul-arabaolaza @olivergondza
=> [JENKINS-44362] Fix MatrixPluginTest#run_configurations_on_with_a_given_label

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
Existing check relied on [this text](https://github.com/jenkinsci/jenkins/blob/dd18af378f014e1aae706c0bb300bcb0f66342a9/core/src/main/resources/lib/layout/layout.jelly#L281), which can be replaced with something else in an OEM distribution. Observed against `WorkflowPluginTest.linearFlow` in CloudBees products. Rather than relying on variable HTML contents, seems simpler and more robust to check the API, which is only offered after startup is complete. (`LocalController.startNow` uses `LogWatcher` but we cannot rely on that from `restart` I think.)
An alternate approach would be to scan for
```html
<span class="jenkins_ver">
```
which is at least less likely to be replaced by branding. Really the proper thing would be for Jenkins core to explicitly offer brandable resource strings, as …
=> Simpler implementation of check for restart()

src/test/java/plugins/GitUserContentTest.java
[JENKINS-44508](https://issues.jenkins-ci.org/browse/JENKINS-44508)
Set user.name and user.email before trying to commit
@reviewbybees specially @varyvol
=> [JENKINS-44508] git-userContent ATH test is failing

src/test/resources/openstack_plugin/cloud-init, src/test/resources/openstack_plugin/cloud-init-authfix, src/test/resources/openstack_plugin/cloud-init-jnlp
Previous URL would simply be redirected. The side-effect would be that the jdk would not get downloaded and installed in /usr/local/java and agents would not be able come up and connect to the JUT
=> Update Oracle JDK URL for cloud-init

src/test/java/plugins/no_docker/GitPluginNoDockerTest.java
[JENKINS-44610](https://issues.jenkins-ci.org/browse/JENKINS-44610)
The problem is that the `svn` branch no longer exists... so the easy fix is to change it to one that exists. I know that this test is fragile but AFAIK this suite is intended to be removed in the future so is not worth the effort
@reviewbybees
=> [JENKINS-44610] GitPluginNoDockerTest is failling in the ATH

src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java, src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/main/java/org/jenkinsci/test/acceptance/update_center/CachedUpdateCenterMetadataLoader.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadataProvider.java
Solves the problem alluded to in #318, which can be seen for example by
JENKINS_WAR=…/jenkins-war-2.46.3.war mvn -Dtest=plugins.FolderPluginTest\#folderScopedCredentialsTest test
Previously this would skip the test case, since metadata for an unspecified and presumed trunk version of Jenkins would be downloaded, so ATH would attempt to install `workflow-job` 2.12, then abort when it saw that this requires 2.60+. Now it will download `update-center.json?version=2.46.3` and install `workflow-job` 2.11 as expected.
@reviewbybees
=> Fixing CachedUpdateCenterMetadataLoader to take into account the version number of Jenkins

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
[JENKINS-44876](https://issues.jenkins-ci.org/browse/JENKINS-44876)
We are experiencing problems with `JobsMixIn#create` being unable to find the `name` input field on heavy load conditions. I have checked the last page and it seems the field is there so i suspect this is a rendering performance issue because the current code uses a `find` instead of a `waitFor`
Aditionally I switched to `ByFactory` instead of using a Selenium `By#name`
@reviewbybees
=> [JENKINS-44876] Use a explicit wait for name field

src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/BuildHistoryArea.java, src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/BuildQueueArea.java, src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/JobStatusArea.java, src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/MissionControlView.java, src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/NodeStatusArea.java, src/test/java/plugins/MissionControlTest.java
Implemented a basis for tests of the mission control plugin as well as two test cases.
=> Mission control view plugin: test basis and two test cases

src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserPublisher.java, src/test/java/plugins/LogParserTest.java, src/test/resources/logparser_plugin/rules/log-parser-rule-markings
Implemented two test cases to check if a build is appropriately marked as failed or unstable.
=> LogParser Plugin: Check for unstable and failed builds

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile
Switched to using the same base container as many other tests.
I now get a failure in the take screenshot test about it not printing something expected that I'm trying to investigate.
Basically Jenkins couldn't connect to the "old" container, so instead of deeply digging into why that was I unified the container to use the "standard" JavaContainer used by other tests.
@reviewbybees
=> Fix agent not connecting for XvncPluginTest

docs/SUT-VERSIONS.md, src/main/java/org/jenkinsci/test/acceptance/update_center/LocalOverrideUpdateCenterMetadataDecoratorImpl.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadataDecorator.java, src/test/java/plugins/RemotingPluginTest.java
Most of this change just adds a capability to test a plugin that's not yet released and available in the update center.
The test itself worked as expected once this was cleared.
=> [JENKINS-41196] demonstrate that core component override plugin can work in ATH

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
When checking #354 with a local plugin build from https://github.com/jenkinsci/ssh-credentials-plugin/pull/30, the test did not work: first Jenkins installed `ssh-credentials@1.14-SNAPSHOT` as requested, and then immediately afterwards it clobbered it with `ssh-credentials@1.13` from the UC. After the restart (BTW why do we need to restart when all the plugins are fresh installations?!), 1.13 was installed, thus defeating the purpose of specifying `$LOCAL_JARS`.
I found that by introducing a delay into the process, the asynchronous update center jobs had time to actually register that `ssh-credentials@1.14-SNAPSHOT` was already there and thus did not need to be added as a dependent installation of `ssh-slaves`.
I do not like this but I have not found a better way yet. Not clear if there …
=> When using $LOCAL_JARS, give installPlugin a moment to catch up

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer.java
Having a single authorized key is not much flexible. This adds a way to add more authorized keys to access the Git repository started by `GitContainer`.
@reviewbybees
=> API to add additional SSH pubkey to Git server

src/test/java/plugins/ConfigFileProviderTest.java
[JENKINS-46564](https://issues.jenkins-ci.org/browse/JENKINS-46564)
It is possible to create custom config files since config-file-provider-2.16.0. Some other plugins like maven-plugin test how they manage their configuration files, but this feature is not tested by any plugin. It would be recommendable to create a test to cover it.
@reviewbybees
=> [JENKINS-46564] Added acceptance test for custom configurations files

README.md
Documenting our new policy for test types we want ATH to hold as well as broken/flaky test eviction policy.
See https://groups.google.com/forum/#!topic/jenkinsci-dev/R8w7uhh-xbgfor discussion.
CC @jenkinsci/code-reviewers
=> Update README to reflect where we want ATH to be

src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
ATH is performing artifact resolution internally for several reasons but it keeps reporting the progress which is only desirable on interactive terminal.
```
Downloading ...
8/68 KB   
10/68 KB   
14/68 KB   
17/68 KB   
21/68 KB   
24/68 KB   
...
```
=> Avoid artifact download progress indication

src/main/java/org/jenkinsci/test/acceptance/po/JdkInstallation.java, src/test/java/core/JdkTest.java
See [JENKINS-47448](https://issues.jenkins-ci.org/browse/JENKINS-47448).
This PR fixes the test that downloads and installs an old version of the JDK from Oracle. I used this test to verify jenkinsci/jenkins#3093.
@reviewbybees
=> [JENKINS-47448] Fix JdkTest#autoinstallJDK

src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java
As noted in https://github.com/jenkinsci/acceptance-test-harness/pull/207#issuecomment-342691560 the download of transitive dependencies can be quite slow, several minutes, so imposing a 60s timeout just makes tests fail when you run on a slowish network.
@reviewbybees
=> Increasing timeout for waitForInstallationToComplete

src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java
Fixes [this failure](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/32/testReport/plugins/MatrixAuthPluginTest/projectMatrixAuth/):
```
Element must be user-editable in order to clear it.
…
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:67 …
```
=> Fix MatrixAuthPluginTest.projectMatrixAuth against matrix-auth 2.x

src/test/java/plugins/WorkflowPluginTest.java
Following up #366 etc. `workflow-aggregator` pulls in a lot of dependencies which are not actually being tested and which we do not care about; this plugin should really just be deprecated. And especially pending https://github.com/jenkinsci/acceptance-test-harness/pull/207#issuecomment-342691560, these deps add a lot to execution time.
@reviewbybees
=> Avoiding use of workflow-aggregator

Jenkinsfile
[INFRA-1404](https://issues.jenkins-ci.org/browse/INFRA-1404)
Enabled by https://github.com/jenkins-infra/jenkins-infra/pull/898. Would be improved by having https://github.com/jenkinsci/junit-realtime-test-reporter-plugin/pull/5 merged & released. Would be a merge conflict with #380, but easy to resolve.
@reviewbybees
=> [INFRA-1404] Use junit-attachments & junit-realtime-test-reporter plugins

src/main/java/org/jenkinsci/test/acceptance/plugins/post_build_script/PostBuildScript.java, src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java, src/main/java/org/jenkinsci/test/acceptance/update_center/PluginMetadata.java, src/main/java/org/jenkinsci/test/acceptance/update_center/UpdateCenterMetadata.java, src/test/java/plugins/ScriptlerPluginTest.java
Implements the notion I had in #207, and supersedes that PR. This seems to run a _lot_ faster: there is a single update center click which processes all changes, all dependencies (incl. implicit ones like `bouncycastle-api-2.16.2.hpi`) get served from the local Maven repository rather than the network, and there is no bogus restart.
Probably supersedes or clashes with #188 & #227.
@reviewbybees @jenkinsci/code-reviewers
=> MockUpdateCenter

src/main/java/org/jenkinsci/test/acceptance/po/WorkflowMultiBranchJob.java
See [JENKINS-48236](https://issues.jenkins-ci.org/browse/JENKINS-48236)
`WorkflowMultiBranchJob.waitForBranchIndexingFinished` is not reading the ElasticTime.factor property when method `waitFor().withTimeout()` is called.
@reviewbybees 
@olivergondza
=> [JENKINS-48236] WorkflowMultiBranchJob is not reading ElasticTime.factor property

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile
[JENKINS-48314](https://issues.jenkins-ci.org/browse/JENKINS-48314)
Drop legacy line since it is removing the default source list. 
We define ubuntu:xenial so there is no need for that line anymore.
Alternative fix is to add `xenial-security` as well to the souce.list but IMHO the whole line does not make sense anymore. @raul-arabaolaza shares this observation.
@reviewbybees @cloudbees/team-astro
=> [JENKINS-48314] https://issues.jenkins-ci.org/browse/JENKINS-48314

src/test/java/plugins/SshSlavesPluginTest.java
See [JENKINS-48681](https://issues.jenkins-ci.org/browse/JENKINS-48681)
Fix for `SshSlavesPluginTest#newSlave` and `SshSlavesPluginTest#newSlaveWithExistingCredential`, which are currently failing.
@reviewbybees
@olivergondza
=> [JENKINS-48681] Fix acceptance test failure for ssh-slaves

src/test/java/plugins/ForemanNodeSharingPluginTest.java
Tests for this plugins is constantly failing. Plugin is now in re-writing stage, skip these tests until rewriting is done.
=> Ignore tests for Foreman node sharing plugin

src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java, src/main/java/org/jenkinsci/test/acceptance/junit/TestRuleException.java
I have some tests running with the withPlugins test rule and a few others. I would really like a way to tell which of my test rules is failing when the tests fail to apply all the test rules. To that end I am submitting this PR to report which test rule failed and the throwable's cause. I didn't see a contributors guide for this, so if I missed it please let me know. @reviewbybees
=> adding more detailed logging in the event that a test rule fails to apply

src/test/java/core/InstallWizardTest.java
[JENKINS-49470](https://issues.jenkins-ci.org/browse/JENKINS-49470)
Fixing a test that has been consistently failing due to not taking into account that user.url is sanitized
@olivergondza I believe that the best fix would actually be to sanitize the url in the test as well but since the tests depend on a 1.36 jenkins version, I do not have hudson.Util available to use.
@reviewbybees
=> [JENKINS-49470] Fixing test assertion to take into account the sanitized url

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JavaGitContainer/Dockerfile, src/test/java/plugins/WarningsPluginTest.java
Fix the constant failure. There is used method for creating slave from abstract class, but this method create ssh slave - so there is necessary dependency on ssh-slave plugin. Plus this error hides that hash of image was not upgraded.
=> Add ssh-slave plugins dependency and Change hash of image.

src/main/java/org/jenkinsci/test/acceptance/junit/DiagnosticRule.java, src/main/java/org/jenkinsci/test/acceptance/junit/JenkinsAcceptanceTestRule.java
Move last-page.html and heap-dump.log generation to DiagnosticRule so they are taken into account by FailureDiagnostics when adding junit attachments
Adding screenshot in case of failure (screen recording is not available in headless mode so having a screenshot is better than nothing)
@reviewbybees
=> [JENKINS-49599] Fix last-page.html and heap-dump.log junit attachement by moving them into a Junit Rule

ath-container.sh
* The previous code was overwriting the /home/ath-user folder with the contents
of the ATH folder, resulting in .vnc folder, among other things probably,
being deleted and hence the container unable to run the ATH unless an
external browser was used
@reviewbybees
=> [INFRA-1489] Do not overwrite home folder when running container

Jenkinsfile
SHARED_DOCKER_SERVICE=true should be set. Sending pull request and see the results in upstream Jenkins run.
=> Set SHARED_DOCKER_SERVICE=true for running ath inside docker container.

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
Replace implicit wait of 1s by an explicit wait for the configure form to be present on the page to assert that the configure page is properly loaded.
Jira issue: https://issues.jenkins-ci.org/browse/JENKINS-49841
@reviewbybees
=> [JENKINS-49841] Explicitely wait for the configure form to be loaded instead of waiting 1s

src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
[JENKINS-50023](https://issues.jenkins-ci.org/browse/JENKINS-50023)
[JENKINS-22936](https://issues.jenkins-ci.org/browse/JENKINS-22936) changed the way to rename `TopLevelItem`s so `ViewTest#renameJob` is failing from `2.110` onwards
This small change makes the test to work again. Also, I have checked which tests use this method to compare with the results in [last master build](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/67/testReport/junit/plugins/) to check for possible regressions introduced by this change
* AnalysisCollectorPluginTest 
* CheckstylePluginTest 
* FindbugsPluginTest
* PmdPluginTest
* TaskScannerPluginTest
* WarningsPluginTest
=> [Jenkins-50023] core.ViewTest#renameJob was failing

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/CredentialsPage.java, src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/View.java
Allow to define configuration form name and text of the submit button. It does not work with views extensions as well with credentials.
=> Configuration form does not have to have name "config"

src/test/java/plugins/CheckStylePluginTest.java
The test uses a method from abstract class to create agent. This method creates ssh agent and requires ssh-slaves plugin.
=> Add missing dependency 

src/main/java/org/jenkinsci/test/acceptance/utils/mail/MailService.java, src/main/java/org/jenkinsci/test/acceptance/utils/mail/Mailtrap.java
Data for mailtrap was changed.
I add the time interval too since there are quite a lot of messages and searching for a message which does not exists (and will not exist because of some failure/bug) return 429 sometimes. There is no need to check for message so often.
=> Update account data.

src/test/java/plugins/KerberosSsoTest.java
Visiting unprotected root action as the first url causes that kerberos authentication is not done. Assure first that user is logged in on the main page and after do check by "whoAmI".
=> Assure that user is logged.

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/test/java/plugins/GitPluginTest.java
[JENKINS-50790](https://issues.jenkins-ci.org/browse/JENKINS-50790)
This should fix most of GitPluginTest and some others that are failing due to the
available plugins taking too much time to load on ci.jenkins.io
@reviewbybees
=> [JENKINS-50790] Temporarily override pageLoadTimeout for available plugins

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile
[JENKINS-51292](https://issues.jenkins-ci.org/browse/JENKINS-51292)
Should fix random issues where the cache was populated from a different
build long ago such as that observed in the referenced issue.
```
java.lang.Error: Failed to build image (100): 3e22c64d038a
at com.cloudbees.CustomTest.setUp(CustomTest.java:62)
Sending build context to Docker daemon 6.144 kB
Step 1/11 : FROM ubuntu:xenial
---> f975c5035748
Step 2/11 : RUN echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" > /etc/apt/sources.list
---> Using cache
---> e62553aa9c43
Step 3/11 : RUN apt-get update && apt-get install -y openssh-server
---> Using cache
---> 381056e8680f
Step 4/11 : RUN mkdir -p /var/run/sshd
---> Using cache
---> aa5449fdb24d
Step 5/11 : RUN apt-get install -y git
---> Running in …
```
=> [JENKINS-51292] attempt to fix random failures in GitCOntainer

src/main/java/org/jenkinsci/test/acceptance/po/TopLevelItem.java
See [JENKINS-51484](https://issues.jenkins-ci.org/browse/JENKINS-51484)
The `TopLevelItem.renameTo` method has been updated because of [JENKINS-22936](https://issues.jenkins-ci.org/browse/JENKINS-22936). The href used to locate the Rename link is valid in general, but fails when the job is located in a folder. 
@reviewbybees @olivergondza @raul-arabaolaza
=> [JENKINS-51484] Rename Job is failing when the job is in a folder

docs/SUT-VERSIONS.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/junit/WithPlugins.java
[JENKINS-51489](https://issues.jenkins-ci.org/browse/JENKINS-51489)
See the linked ticket, when running against an existing environment with a preconfigured set of plugins, for example, a war file generated from [CWP](https://github.com/jenkinsci/custom-war-packager)  or an existing instance seems reasonable for the ATH to not try to install/update any plugins but only validate the existing ones to check if they are enough for the set of tests to run.
This PR introduces a new `pre-configured plugins mode` which does exactly that if you specify a `pluginEvaluationOutcome` property via the groovy wiring script the mode is activated, depending on the value (see the new docs) a test whose dependencies are not satisfied may directly fail or be skipped without the ATH trying to install/update …
=> [JENKINS-51489] Introducing pre configured plugins mode

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile
See [JENKINS-52119](https://issues.jenkins-ci.org/browse/JENKINS-52119). This simple PR updates the URL from which the Atlassian SDK is downloaded.
Before this PR, if you don't already have the docker image downloaded from previous work, the test will fail as follows:
```
Building Docker image `docker build -t jenkins/jira:2b315e26c84f /tmp/Dockerfile8883778022481754579dir`: logfile is at target/diagnostics/jira_ticket_gets_updated_with_a_build_link(plugins.JiraPluginTest)/docker-JiraContainer.build.log
master55986|Jun 21, 2018 4:09:13 PM jenkins.metrics.api.Metrics$HealthChecker execute
master55986|WARNING: Some health checks are reporting as unhealthy: [backup : Last backup failed: null]
[[ATTACHMENT|/tmp/dockerhome/acceptance-test-harness/target/diagnostics/jira_ticket_gets_updated_with …
```
=> [JENKINS-52119] Fix URL for downloading Atlassian SDK

src/test/java/plugins/JobDslPluginTest.java
This deprecated feature was removed by commit  https://github.com/jenkinsci/job-dsl-plugin/commit/db9ca7d1b27f2daaad5bd13d733e51868ae9afdd#diff-4383c503e803309dfcf3aa10c24d9c25.
I know that purpose of this test is to test that it provides different build result if deprecated feature is used (to make it more visible for user). But this change is more then half year old and no one modified the test and it is failing since that. If someone wishes to have this behavior be tested and rewrite it to other deprecated feature, he can. But until it happens I suggest to skip this tests.
=> Ignore the test - deprecated features which is tested was removed.

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat7Container/Dockerfile
Solving issue when building the docker image as the `public key` is not reachable when using the generic ubuntu image. Besides that, it does allow to be more consistent and use always the same version.
* Current error:
```
Sending build context to Docker daemon  2.56 kB
Step 1/6 : FROM ubuntu
---> 113a43faa138
Step 2/6 : RUN echo "deb http://archive.ubuntu.com/ubuntu precise universe" >> /etc/apt/sources.list
---> Using cache
---> 54dd9361a398
Step 3/6 : RUN apt-get update && apt-get install -y tomcat7 tomcat7-admin
---> Running in 96f746fab525
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [83.2 kB]
Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
Get:3 http://security.ubuntu.com/ubuntu bionic-security/universe Sources [8194 B]
Get:4 …
```
=> Tomcat7Container docker image based on ubuntu:xenial

src/main/java/org/jenkinsci/test/acceptance/po/Login.java
[Issue detail](https://issues.jenkins-ci.org/browse/JENKINS-52779)
Login was relying on https://plugins.jenkins.io/form-element-path and path selectors.
This is not working anymore with the new Login page introduced by https://github.com/jenkinsci/jenkins/commit/90670e05c17b34270cda9436eaf877cc72a341ec.
As the form elements attributes has not been changed by the new Login page, use By.name selectors so it's working with both new and old Login pages.
@reviewbybees
=> [JENKINS-52779] Fix Login#doLogin with the new Login page

src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java
UI for adding user in matrix authentication plugin has changed. This fix should work for Jenkins version 2.60+ and plugin version 2.3+. I do not think that we need backward compatibility for previous versions of plugins or Jenkins (I do not like to have a lot of if/else for due to jenkins/plugin version), anyone with different opinion?
=> UI for adding user changed.

src/main/java/org/jenkinsci/test/acceptance/Matchers.java, src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
[JENKINS-52962](https://issues.jenkins-ci.org/browse/JENKINS-52962)
Fix for:
- password in the signup page now has only one field (no confirmation anymore)
- "Sign up" has been changed to "Create account" so use the name html field instead of text
- Text for incorrect login information has been changed from "Invalid login information. Please try again." to "Invalid username or password"
@reviewbybees
=> [JENKINS-52962] Make ath compatible with the new Login page

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/KerberosContainer.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/KerberosContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/KerberosContainer/src/etc.krb5.conf, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/KerberosContainer/src/prepare.sh
Tests for kerberos ticket are failing when ATH is running inside docker. The reason is that they were written for localhost:<port> (communication between host and container) which is not the way how one container can communicate with another.
=> Fix kerberos for ATH inside container

src/test/java/plugins/JobDslPluginTest.java, src/test/java/plugins/MatrixAuthPluginTest.java, src/test/java/plugins/SAMLPluginTest.java, src/test/java/plugins/ScriptSecurityPluginTest.java, src/test/java/plugins/WarningsPluginTest.java
As https://github.com/jenkinsci/acceptance-test-harness/pull/446 is introducing a non backward compatible change with matrix-auth plugin < 2.3, skipping the tests accordingly so if we run them with an older version, they won't fail.
@reviewbybees
=> Skip tests which require adding a user with matrix-auth plugin if version < 2.3

src/test/java/plugins/TaskScannerPluginTest.java
If ATH is running inside container, there is no command file installed. It is used for finding *.java files and edit them. There is no need to install another package for it, *.java files can be recognized even without it.
=> File command is missing, use another way how to select wanted files.

Jenkinsfile, src/main/resources/ath-container/Dockerfile
[JENKINS-54295](https://issues.jenkins-ci.org/browse/JENKINS-54295) This version was working perfectly for the 1.62 tag
* DO NOT MERGE YET, I HAVE CREATED THIS PR TO VALIDATE MY THEORY*
=> [JENKINS-54295] Fix docker image

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java, src/test/java/plugins/SubversionPluginTest.java
After merge of pull request #395 some tests which use select are broken (now the select does not search for option which contains given string, it has to match exactly). The problem is mostly in credentials select since there is used id (generated hash) or combination user name with /***** (and tests use for identification only username). I think that it is better to start use id of credentials since it is the only one unique identification for id. The most easy way how to do it is to use already implemented functionality and define which id should be used for credentials. 
Some of tests which use credentials are not broken, because they use their own implementation for identifying credentials. I let those test like they are and modify only the broken ones. I will modify them the same way …
=> Define id for clear identification in form.

run.sh
Can we useful as we're adding JDK 11 support and people use this for various JDK versions and be able to check they're actually running what they think.
cc @jenkinsci/java11-support @olivergondza
=> Display maven and JDK versions from `run.sh`

README.md, docs/JAVA11.md
See [[JENKINS-54975] Add how to run on java11](https://issues.jenkins-ci.org/browse/JENKINS-54975)
Add some documentation about how to run on a Java 11 VM. Added a note making it clear that it's a work in progress.
@jenkinsci/java11-support @olivergondza @reviewbybees
=> [JENKINS-54975] Add how to run on java11

Jenkinsfile
See **[[INFRA-1690] DevTools: Add support of Specifying Java Level for Test in runATH()
](https://issues.jenkins-ci.org/browse/INFRA-1690)**
Overrides the workflow-support plugin, add the modules/libraries removed from java 11 and do that only on java 11.
Block by #464 (jdk11 in the docker image)
@olivergondza @jenkinsci/java11-support @raul-arabaolaza
=> [INFRA-1690] overrides workflow-support with tag

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Proposed as an alternative to https://github.com/jenkinsci/acceptance-test-harness/pull/468 after some analysis.
This is an attempt to fix random errors we are seeing in CI on many PRs on
Jenkins Core currently.
```
Close WebDriver after test failed
Stacktrace
java.lang.AssertionError: Close WebDriver after test failed
at org.jenkinsci.test.acceptance.guice.Cleaner.performCleanUp(Cleaner.java:56)
at org.jenkinsci.test.acceptance.guice.TestCleaner.performCleanUp(TestCleaner.java:19)
at org.jenkinsci.test.acceptance.guice.World.endTestScope(World.java:66)
at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:64)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4 …
```
=> Catch also NoSuchSessionException when cleaning up

src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java, src/test/java/plugins/JobDslPluginTest.java
The original author has likely tried to get the plugin fullish functional coverage which is not what ATH was ever supposed to do. This collapses some trivial checks and removes many tests that are not fundamentally different from those that stayed.
=> [JENKINS-54916] Eliminate some of the Job DSL tests

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
In order to let the warnings tests run on Windows copying of resources need to be platform aware.
=> Added support to copy files on Windows.

src/main/java/org/jenkinsci/test/acceptance/po/ShellBuildStep.java
Currently a shell build step tries to set the "command" control as first alternative. If it is not available then the CodeMirror is used instead. 
However, on my machine with my Jenkins setup the CodeMirror is the preferred way to access the command. Otherwise the tests just wait for the command timeout and then use the CodeMirror. So I flipped the alternatives: First the code mirror is used, and then if not available the command control. 
This speeds up my tests by a couple of seconds for each shell command (there are quite a lot).
=> Speedup shell commands by trying CodeMirror as first alternative.

Jenkinsfile
The plugin tests was all that was in a single split. Its removal caused our build
has entered an infinite failure loop.
=> Fix broken split generation after Warnings plugin removal

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Current code will try to locate the driver in the OS PATH and always ends up setting the driver specific location property, regardless the property was already set.
This change preserve user value, allowing to have the driver *not* in the PATH.
Was discussed on the group: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/jenkinsci-dev/BNuQMy3lsFY/yMntNg0rBwAJ
=> Allow user to provide location of driver

src/main/java/org/jenkinsci/test/acceptance/po/ToolInstallation.java, src/test/java/plugins/AntPluginTest.java
Allow to install more than one tool of the same type, by expanding the collapsed tool area in recent Jenkins versions.
I have successfully tested the fix on our own test suite (SonarQube plugin) but I'm not very pleased by the proposed fix (try..catch) so if you know a better way, feel free to change.
I also tried to update a test to demonstrate what I'm trying to fix, but I didn't run it for real on my box.
=> Support installation of multiple tools versions

pom.xml, src/test/java/plugins/JavadocPluginTest.java
See [[JENKINS-56492] Fix Javadoc failures on Java11](https://issues.jenkins-ci.org/browse/JENKINS-56492)
Java11 is not using frames anymore, so we need to change how we check whether the javadoc is generated correctly or not.
Tested using **VERSION_OVERRIDES** and **set-java.sh** on ATH with:
**Java 8 / Javadoc 1.3**
Frames
**Java 8 / Javadoc 1.5**
Redirect but still frames
**Java 11 / Javadoc 1.3**
No frames, no redirection :laughing: 
**Java 11 / Javadoc 1.5**
No frames, redirect
Reviews welcome: @olivergondza @raul-arabaolaza @jenkinsci/java11-support
=> [JENKINS-56492] Fix JavadocPluginTest failures on Java11

src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
Removing the sha1 element like before https://github.com/jenkinsci/acceptance-test-harness/commit/240e438e2a3ab719a7301ab112de470fd503572e#diff-e5a5651006d379f437e8f02dfa5866de
allows to bring back support of older Jenkins versions.
=> Restore support of JUT before 2.168 where only plugin sha1 was checked

src/main/java/org/jenkinsci/test/acceptance/po/ContainerPageObject.java
See [[JENKINS-56982] Closing connection to avoid tests getting hung](https://issues.jenkins-ci.org/browse/JENKINS-56982)
The ATH tests were getting hung in our ATH tests. It happens if one of the tests executed has a `Jenkins.restart()` statement that ends up calling this code.
@olivergondza @jenkinsci/java11-support @raul-arabaolaza
=> [JENKINS-56982] Closing connection to avoid tests getting hung

src/main/java/org/jenkinsci/test/acceptance/plugins/jira/JiraGlobalConfig.java, src/test/java/plugins/JiraPluginTest.java
This [jenkinsci/jira-plugin#a06acf](https://github.com/jenkinsci/jira-plugin/commit/a06acf0770aace33de71f06a54d171d50785118d) and the JCasC support done by @casz, the global configuration of Jira in Jenkins is located in its own class.
=> [JENKINS-52906] Global configuration for Jira is now in a specific class

src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
[JENKINS-57804](https://issues.jenkins-ci.org/browse/JENKINS-57804)
The page object that can be used to configure the JenkinsDatabaseSecurityRealm in acceptance tests has a typo in the element name used to enable/disable the ability for users to self-register (ie. signup) when using this realm. The jelly form control is named "allowsSignup" but the pageobject references it using the name "allowSignup". This causes any ATH tests that rely on manipulating that element to fail with an element not found/Timeout exception.
[This was brought to light as the result of a recent change that forces the UI behavior to disable user signup by default (as a security precaution)](https://github.com/jenkinsci/jenkins/pull/3954/files#diff-aec8de1c6c772be0d3ecb3573c46ead8L29), which in turn caused some …
=> [JENKINS-57804] Fix typo in the name of the checkbox that enables user signup for the HudsonSecurityRealm page object

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Hoping to solve a subtle ATH regression in weeklies as described in https://github.com/jenkinsci/form-element-path-plugin/pull/8#discussion_r292442826.
=> Use 1.9 as default $FORM_ELEMENT_PATH_VERSION

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshPrivateKeyCredential.java
This updates the page object so that it clicks the button hiding the textarea before trying to refer to the otherwise nonexisting input field.
Compare to https://github.com/jenkinsci/jenkins/blob/master/test/src/test/java/lib/form/SecretTextareaTest.java
@reviewbybees @jeffret-b @Wadeck
=> Update page object for ssh-credentials 1.16

.gitignore
Removed *.log from gitignore since TextFinder plugin already uses this suffix (and IntelliJ complains about these problems). Maybe other plugins (like the warnings plugin) will use this suffix as well in the future. If we really want to ignore *.log files we should prefix them in the .gitignore with a path.
=> Removed *.log from .gitignore

src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenModuleSet.java
This allows the use of `MavenModuleSet.copyDir()` on windows when running
locally.  Currently the code just blows up at runtime with
`java.lang.UnsupportedOperationException: There are no build steps in maven projects`
=> Add Parity for batch steps to Shell Steps

src/test/java/core/CredentialsTest.java
Now that ssh-credentials uses f:secretTextarea, the private key value
cannot be viewed after saving it. This removes the prior assumption that
this value will always be viewable.
This fixes the CredentialsTest failures.
@reviewbybees @bmunozm @raul-arabaolaza @amuniz @jeffret-b
=> Fix test failures related to createSshKeys

.github/release-drafter.yml
Once merged, I can enable Release Drafter for this repository.
Other tools like PCT already use it, so IMHO it would be nice to enable it, even if we do not categorize pull requests here.
=> Add a Release Drafter configuration

src/test/java/plugins/LogParserTest.java
The check of summary on build page is fragile when it does not have expected order (the third). In case the ATH are executed with combination of plugins which are displayed on build summary (for example ownership).
=> Make searching for log parser on build page less fragile.

src/main/resources/ath-container/Dockerfile
Maven version `3.6.0` is no longer available from https://www.apache.org/dist/maven/maven-3/, this PR updates the `Dockerfile` to use `v3.6.1`
=> Update the maven version used in the ath docker image

src/main/java/org/jenkinsci/test/acceptance/po/Node.java
See https://issues.jenkins-ci.org/browse/JENKINS-59281
I needed this fix in order to get #525 running locally with enabled Windows Defender :(
=> [JENKINS-59281] - Introduce a default 30sec timeout for Groovy Console script executions, and make it configurable

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/main/java/org/jenkinsci/test/acceptance/po/Control.java, src/main/java/org/jenkinsci/test/acceptance/po/Login.java
If you have a large delay on your Authentication then login will return
but the login process will not have completed.
The upshot is you must never use WebElement.click() for anything that
will be gauranteed to change the current page (URL)
https://blog.codeship.com/get-selenium-to-wait-for-page-load/
Whilst this is a form I tried changing click() to submit() but this
caused a worse issue and did not even work.  So for now add sime methods
that will wait until the page has changed (ie the current element will
be stale.  This will occur even if the same page is returned)
=> login does not wait for the user to be logged in

src/main/java/org/jenkinsci/test/acceptance/Matchers.java, src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsLogWatcher.java, src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
_ is deprecated in java8 and I beleive dissallowed in Java9
given we do not care what the variable was called change the use of _
to ignored
=> Do not use underscore as an identifier.

src/main/resources/ath-container/run.sh
Faster and cleaner than:
```
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< org.jenkins-ci:acceptance-test-harness >---------------
[INFO] Building Acceptance Test Harness 1.69-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/com/github/jnr/jffi/maven-metadata.xml
Downloading from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/com/github/jnr/jffi/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/com/github/jnr/jffi/maven-metadata.xml (1.0 kB at 2.3 kB/s)
Downloaded from repo.jenkins-ci.org: https://repo.jenkins-ci.org/public/com/github/jnr/jffi/maven-metadata.xml (1.0 kB at 1.5 kB/s)
Downloading from central: …
```
=> Fail fast and clean when BROWSER_DISPLAY and BROWSER are both undefined

src/main/resources/ath-container/vnc.sh
Use setsid to detach processes that are supposed to keep running (vncserver and vncviewer) from current process group, so `^C` sent to any command run afterwards does not kill the vnc. Happens commonly when ATH is paused by `INTERACTIVE=true` and then killed normally.
=> Do not interrupt vnc(server|viewer) on ctrl-c

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/junit/WithInstallWizard.java, src/main/java/org/jenkinsci/test/acceptance/machine/RemoteJenkinsProvider.java, src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java
Early installation of form-element-path causes to install implied dependencies - 
in version that was detached. This can easily cause such plugin need to be updated
for other plugins to install correctly. While Plugin Manager is ready for this and
handle it well, Setup Wizard is reporting an issue and demand Jenkins to be restarted.
Note its page objects _can_ be made more robust to restart if needed, but since
it would happen every time, it would just obscure real issues this can detect. Not
to mention this is running Setup Wizard out of its expected mode of execution, as
it does not expect any plugins to be present effectively testing corner case rather
that main code paths.
Alternative [approach](https://github.com/jenkinsci/form-element-path-plugin/pull/8/files#r292442826) used in the …
=>  Do not install form-element-path for tests annotated with @WithInstallWizard

src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java, src/main/java/org/jenkinsci/test/acceptance/plugins/mission_control/MissionControlView.java, src/main/java/org/jenkinsci/test/acceptance/po/Build.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayer.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/main/java/org/jenkinsci/test/acceptance/po/Job.java, src/main/java/org/jenkinsci/test/acceptance/po/WorkflowJob.java, src/main/java/org/jenkinsci/test/acceptance/po/Workspace.java, src/test/java/core/FormValidationTest.java
Also honors the provided timeout (#542 changed it to hardcoded 10 seconds)
=> [JENKINS-60102] In order to capture the right window handle to get back to, confirmAlert/handleAlert should take a Runnable.

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
I got the following unhelpful stacktrace during a run...
```
Caused by: java.lang.AssertionError: java.net.MalformedURLException: Illegal character in URL
at org.jenkinsci.test.acceptance.po.Jenkins.getVersionNumber(Jenkins.java:87)
at org.jenkinsci.test.acceptance.po.Jenkins.lambda$waitForStarted$0(Jenkins.java:103)
at org.jenkinsci.test.acceptance.junit.Wait$1.apply(Wait.java:94)
at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:260)
... 26 more
Caused by: java.net.MalformedURLException: Illegal character in URL
at sun.net.www.protocol.https.HttpsURLConnectionImpl.checkURL(HttpsURLConnectionImpl.java:87)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:99)
at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
at …
```
=> Make the exception a bit more helpful

src/main/resources/ath-container/Dockerfile
3.6.1 is no longer available on the download site, so CI builds are failing. Amends #503 & #522.
Maybe better to use Maven Central as the download location? We know releases cannot be pulled from there.
=> Switch ATH Docker images to Maven 3.6.3

src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
As per https://github.com/jenkinsci/jenkins/pull/2930#issuecomment-558312450 you otherwise get
```
org.openqa.selenium.NoSuchElementException: Unable to locate By.cssSelector: [path='/useSecurity'] in http://127.0.0.1:50158/configureSecurity/
at org.jenkinsci.test.acceptance.po.CapybaraPortingLayerImpl.find(CapybaraPortingLayerImpl.java:203)
at org.jenkinsci.test.acceptance.po.Control.resolve(Control.java:73)
at org.jenkinsci.test.acceptance.po.Control.check(Control.java:91)
at org.jenkinsci.test.acceptance.po.GlobalSecurityConfig.useRealm(GlobalSecurityConfig.java:51)
at core.TriggerRemoteBuildsTest.triggerBuildRemotely(TriggerRemoteBuildsTest.java:46)
```
=> [JENKINS-40228] Accommodate lack of a useSecurity checkbox

pom.xml, src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java
As per https://github.com/jenkinsci/acceptance-test-harness/pull/84#discussion_r57729985 this is versioned separately, and was not compatible with the newer Selenium:
```
java.lang.NoClassDefFoundError: org/openqa/selenium/remote/SessionNotFoundException
at org.jenkinsci.test.acceptance.FallbackConfig.createWebDriver(FallbackConfig.java:141)
```
Using the latest available version would force a Selenium upgrade (https://github.com/SeleniumHQ/htmlunit-driver/commit/dc9a3872b0be68eae438dd9bdf0cdba6e6ab9c50) so I chose something a bit older, and resolved version conflicts in favor of upper bounds.
Also disabled `Scroller` as it does not work with this driver (just times out) and is probably unnecessary anyway.
Tested on `TriggerRemoteBuildsTest`.
=> BROWSER=htmlunit

src/main/resources/ath-container/Dockerfile
See [JENKINS-60633](https://issues.jenkins-ci.org/browse/JENKINS-60633)
The link to download **_Maven 3.6.1_** is broken, so I changed the link to an existing one.
I've not changed to Maven 3.6.3 because I have no enough bandwidth to check whether it's safe. It should be safe, but who knows.
@olivergondza @raul-arabaolaza @varyvol @fcojfernandez @alecharp @rsandell @batmat reviews appreciated
=> [JENKINS-60633] Update maven 3.6.1 url to the archive repo

README.md, docs/BROWSER.md, docs/CONTRIBUTING.md, docs/EXTERNAL.md, pom.xml, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java, src/main/java/org/jenkinsci/test/acceptance/guice/Cleaner.java, src/main/java/org/jenkinsci/test/acceptance/utils/IOUtil.java
Permit ATH to utilize [selenium containers](https://github.com/SeleniumHQ/docker-selenium) to host browser, driver and selenium server. This si tangential to what ath-container do, but it integrates nicely with `buildPlugin`.
This is intended to be a way to use ATH from plugins source code.
Downstream PRs:
- https://github.com/jenkinsci/kerberos-sso-plugin/pull/19
- https://github.com/jenkinsci/openstack-cloud-plugin/pull/288
- https://github.com/jenkinsci/jms-messaging-plugin/pull/164
=> Explore ATH run against containerized selenium

src/main/tool_installers/updates/hudson.tasks.Maven.MavenInstaller, src/test/java/plugins/WarningsNextGenerationPluginTest.java, src/test/resources/warnings_ng_plugin/source-view/pom.xml
Since [analysis-model-7.0.0](https://github.com/jenkinsci/analysis-model/releases/tag/analysis-model-7.0.0) the Maven parser detects the module a warning is from. So a new tab will be shown in the test.
=> Fix broken test due to maven module detection in maven parser

README.md
I always need to search around to find the latest CI results. Maybe a badge will give us some more motivation to keep the build green.
=> Add badge for CI build results

src/test/java/plugins/GitPluginTest.java
Git plugin 4.0 uses `<strong>` instead of `<b>` tag.
`<strong>` tag is recommended over `<b>` in some online locations.  The `<b>` tag meaning has changed in HTML 5 according to https://www.w3.org/International/questions/qa-b-and-i-tags .
See [build 209 test result](https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/209/testReport/junit/plugins/GitPluginTest/java_8_split9___custom_scm_name/) for an example of the failure.
Review preferred by @mikecirioli or @fcojfernandez or @rsandell or @oleg-nenashev
=> Adapt GitPluginTest regex for git plugin 4.0

src/main/java/org/jenkinsci/test/acceptance/plugins/warnings_ng/AnalysisSummary.java, src/test/java/plugins/WarningsNextGenerationPluginTest.java
- The icon (error/info) is now an SVG icon that has a different XPath
- There are no errors reported anymore for broken absolute paths
=> Update warnings tests for 8.0.0 release and newer

src/main/java/org/jenkinsci/test/acceptance/ByFactory.java
See https://github.com/jenkinsci/jenkins/pull/3895
There's another class on the checkbox now, and looking for exact match caused 2 smoke tests to fail
=> JENKINS-56109 Adjust locator for table -> div layout changes

src/main/java/org/jenkinsci/test/acceptance/po/Job.java
When copying ressources into the workspace of a jenkins test instance, the command "xcopy" is used on windows machines.
When copying ressources directyl the options"/E" and "/Y" are added to the command. When copying directories only the "/E" option is added.
This poses a problem when copying directories with ressources while having duplicate files already in the workspace.  That's because then a overwrite message pops up for the user which is normally suppressed with the "/Y" option. This results in failing the jenkins build.
Therefore the "/Y" option is also added to copying directories.
=> Fix overwrite message when copying directories on Windows

src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailGlobalConfiguration.java
The failure was happening because the PO `AuditTrailGlobalConfiguration` was using a wrong selector to find an HTML input (`GlobalPluginConfiguration`)
Replace invalid selector in `AuditTrailGlobalConfiguration`, with the current one.
The failure was reproduced with jenkins-core 2.204.5 and 2.222.3, and the fix has been validated against those lines too.
=> [JENKINS-62481] Fix AuditTrailPluginTest

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Be sure "check for updates" is working consistently, clicking the button, and waiting until the page is refresh. This will avoid some flakiness in testing.
Tested in Java8 and Java11
cc/ @batmat @varyvol @raul-arabaolaza @imonteroperez
=> Be sure "Check Now" button action is finished before continue with a test

src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
Useful when `-Dupdate_center_url` is overridden so this fails instead of silently using upstream UC.
=> Make sure the test fails instead of defaulting to upstream UC when overridden

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Currently we start test cases if there is no progress shown
in the update manager screen. However, sometimes the plugins are
already installed but not yet initialized.
See https://issues.jenkins-ci.org/browse/JENKINS-61477
=> [JENKINS-61477] Wait until plugins have been initialized

src/main/resources/org/jenkinsci/test/acceptance/selenium/scroller.js
See [JENKINS-62691](https://issues.jenkins-ci.org/browse/JENKINS-62691).
When scrolling to a form sticky button the scroller would get stuck in an infinite loop when the form buttons container touched the footer. It's better described on the issue.
@EstherAF 
@bmunozm
@amuniz
=> [JENKINS-62691] Fix bug where scroller is stuck in infinite loop

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
This reverts commit 95698c6eb8262f272da951b1e9d65bb02dd3481a, reversing
changes made to 26b15fd0763ceaef27ed1f07728e152e7df21ba0.
I'm observing erratic behaviour in ATHs, some `visit` calls are randomly failing to actually visit the page when it's run after a `save` call. I'm not sure what's really happening, but reverting this change I get consistent test runs.
/cc @olivergondza
=> Revert "Merge pull request #536 from jtnord/save-should-use-submit"

src/test/java/core/FreestyleJobTest.java
The css classes of the error shown when the format of the build schedule field is wrong has changed. This PR distinguish both formats depending on the Jenkins version.
Error displayed:
New css:
=> Fix a test failure because of an error css changed

src/main/java/org/jenkinsci/test/acceptance/po/LabelAxis.java
Theses changes https://github.com/jenkinsci/matrix-project-plugin/pull/64 released on [Matrix Project Plugin 1.15](https://github.com/jenkinsci/matrix-project-plugin/releases/tag/matrix-project-1.15) make https://github.com/jenkinsci/acceptance-test-harness/blob/000ee55fab1ef9497e3f81ccecdad7cac3a2e22a/src/test/java/plugins/MatrixPluginTest.java#L107 to fail because the change on the terminology from `slave` to `agent`. 
Added `Agents` to allow the tests pass on older versions of the plugin.
=> Fix Matrix Project failure after 1.15 (slave -> agent)

src/test/java/plugins/GitPluginTest.java
Table to div UI changes probably broke this UI test.  Already have strong coverage for ancestry strategy in the git plugin tests.  There are two other build chooser strategy tests in this suite.  More valuable to spend our time on other areas.
=> [JENKINS-62868] Delete one Git ancestry strategy test

src/test/java/plugins/OwnershipPluginTest.java
Runs with recent LTS or even `master` results in failures because right now `getText` on the node page does not return the `Primary` literal even if it is visible in the UI, I guess some security hardening or the expected behaviour, in any case I prefer to change the assert in the test that change the behaviour of `getText` as that could break other tests.
See failure https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/241/testReport/plugins/OwnershipPluginTest/java_8_split6___explicitly_set_ownership/
=> Fix OwnershipPluginTest for LTS

pom.xml, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java, src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
Upgrades selenium to `3.141.59` 
I don't actually need this - but in the process of actually trying to work out what the issue I was observing was I tried using the latest - turns out the issue was with the docker container & env I was using to run firefox.
so no urgency, but would probably need doing at some point so filing so that the work does not have to be duplicated.
=> upgrade selenium to 3.141.59

src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
This makes tests that check form validation work when using tables to divs PR.
Specifically fixes the jcasc test
https://issues.jenkins-ci.org/browse/JENKINS-62866
=> JENKINS-62866 Fix form validation - tables to divs

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java
With tables to divs the page is longer, `moveToElement` doesn't seem to work with our credentials dialog popup.
This fixes it
cc @fqueiruga @olivergondza
=> JENKINS-62871 Fix ssh slaves with tables to divs

src/main/java/org/jenkinsci/test/acceptance/po/PasswordParameter.java, src/test/java/core/FreestyleJobTest.java
https://issues.jenkins-ci.org/browse/JENKINS-62822
The path to the default value of the Password parameters on Jobs value changed with https://github.com/jenkinsci/jenkins/pull/4630/files#diff-bb80f35e7698754c0c72d989e4f04406.
The ATH PO for the [Parameter](https://github.com/jenkinsci/acceptance-test-harness/blob/master/src/main/java/org/jenkinsci/test/acceptance/po/Parameter.java) was previously providing a `setDefaultValue` compatible, but with this change the path to the input is no longer valid. Now it has to be [`defaultValueAsSecret`](https://github.com/daniel-beck/jenkins/blob/13d242af0472e99757770846dc9a0022df40ada2/core/src/main/resources/hudson/model/PasswordParameterDefinition/config.jelly#L32)
As there was no default implementation for the Password parameter, any downstream …
=> [JENKINS-62822] Add PasswordParameter overriding the 'default' control path

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
See discussion in SonarSource/jenkins-sonar-plugin#158.
ATH 1.73+ is not backward-compatible with Jenkins prior to 2.189, because of #566 (fix for [JENKINS-61477](https://issues.jenkins-ci.org/browse/JENKINS-61477)).
It is now waiting for a log message after installing plugins ("*Completed installation of X plugins*"), but this message has only been introduced in 2.189, via jenkinsci/jenkins@5169f14019, in jenkinsci/jenkins#4124.
This PR disables waiting for this message when using an older Jenkins version.
CC: @uhafner, @olivergondza (from #566)
=> [JENKINS-61477] fix 2.176.x backward compatibility

pom.xml, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java, src/test/java/org/jenkinsci/test/acceptance/recorder/HarRecorderTest.java
* [Browsermob proxy](https://github.com/lightbody/browsermob-proxy) hasn't been touched for 3 years. Migrating to [browserup proxy](https://github.com/browserup/browserup-proxy) which seems to be more active.
* Update dependencies as needed.
* trust all certificates on chrome (to align with ff behaviour)
* capture request/response headers as well
=> Upgrade browser proxy to an active fork

src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
Without this property on the proxy, one will see errors in their logs when the server presents an insecure cert:
```
2020-09-23 15:26:07,161 [LittleProxy-0-ProxyToServerWorker-0] ERROR  (ProxyToServerConnection.java:465) org.littleshoot.proxy.impl.ProxyToServerConnection - (DISCONNECTED) [id: 0xe2dbfcdd, L:0.0.0.0/0.0.0.0:51215 ! R:/35.199.14.121:443]: Caught an exception on ProxyToServerConnection
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: General SSLEngine problem
```
=> Trust all servers to avoid SSL errors in logs

src/test/java/plugins/LdapPluginTest.java
See discussion in https://github.com/jenkinsci/ldap-plugin/pull/49/commits/7c00268c86aafe3985ab5eacedc43c17726777a4. Have not actually tried running this, just trying to edit the test to match the `JenkinsRule` version.
=> Fixing LdapPluginTest.use_environment_varibales [sic]

Jenkinsfile
The initial build is not splitting correctly.
this attempts to fix that based on a guess that the if is failing as it
is comparing a String to an int.
=> [JENKINS-64038] environment variables are Strings

Jenkinsfile
https://issues.jenkins-ci.org/browse/JENKINS-64038
if previous builds are aborted or failed and the `splitTests` step has
no reference we still need to split the tests - so fallback in any case
there is not a previously completed non failed build.
this is an obvious improvement over #612
=> [JENKINS-64038] we need to split the tests when there are no reference builds

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
when saving the global configuration if you are going from an unsecured
to secured instance then you will have 2 page loads
the first will be the action of saving causing a navigate to /manage on
completion.  however this may now be access controlled, so rather than
the normal manage page you may get the jenkins 403 page which is a very
plain HTML page with a meta refresh and some javascript of a similar
line that will then cause the page to navigate to the login page.
so when cehcking that "the page expects a form submission" text there is
a race condition as that is performed in 2 parts.
1) getting the root element (by.css("html")
2) getting the text of that element
however if you have just secured Jenkins in the manage page then you
could get the html element of the redirect page …
=> Fix racecondition when saving forms

src/main/java/org/jenkinsci/test/acceptance/po/CodeMirror.java
The script console is added by Javascript and not completely ready with
the page load.
Therefore we need to wait for the parts we want to manipulate to be
ready.
Fixes a flaky test observed when using master.runStript() with the following failure:
```
org.openqa.selenium.NoSuchElementException:
Unable to locate element: //*[@path='/script']
```
=> Fix a flakiness observed when using master.runScript()

src/main/java/org/jenkinsci/test/acceptance/po/Control.java
fixes various flakes.
`click()` was flaky when the WebElement had to be scrolled into view due to obsuring by the "Save" and "Apply" buttons (so we waitfor the click to happen).
the dropDown selector was flaky and would sometimes not be visible - so also changed to using waits (and update the code that was sleeping to use wait to make the tests faster where possible)
=> deflake `Control.click` and `Control.selectDropdownMenu`

src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/controls/JobFiltersArea.java
[JENKINS-62867](https://issues.jenkins.io/browse/JENKINS-62867)
Since  2.239 and jenkinsci/jenkins#4466, the job filter has its own view.
=> [JENKINS-62867] Fixes job filtering selection in views

src/main/java/org/jenkinsci/test/acceptance/po/JenkinsDatabaseSecurityRealm.java
The signup is a source of flakiness because the control of the `signup` function is returned before making sure that the submission finished loading. This is addressing it, with the implicit timeout of the `clickAndWaitToBecomeStale`, which is 30s.
=> Reduce flakiness during signup: Make signup to wait until the page is loaded

src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/LdapContainer.java, src/test/java/plugins/LdapPluginTest.java
Moving default creation of LDAP data to the docker fixture to allows to use it easily in tests.
=> Move LDAP default configuration to Docker fixture.

src/main/java/org/jenkinsci/test/acceptance/controller/ExistingJenkinsController.java, src/main/java/org/jenkinsci/test/acceptance/controller/JenkinsController.java, src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java, src/main/java/org/jenkinsci/test/acceptance/utils/AccessTokenGenerator.java, src/main/java/org/jenkinsci/test/acceptance/utils/FormElementPath.java, src/main/java/org/jenkinsci/test/acceptance/utils/HttpUtils.java
I'm running an ATH against an existing Jenkins instance running in Kubernetes. The usual workflow is to login, go through the setup wizard (once), then perform a functional test.
This PR brings a few changes to support this way of running an ATH:
* Support `form-element-path` installation through rest api
* `ExistingJenkinsController`: Initial support for authenticated Jenkins when using `TYPE=existing`
* `ExistingJenkinsController`: checking for form-element-path can be skipped. (this is called later)
* Support for access token generation
=> Support form-element-path installation through rest api

src/main/java/org/jenkinsci/test/acceptance/Matchers.java
Making the check of the logged user using Jenkins API instead the UI, so the check is more robust in case something is not well rendered.
@bmunozm @EstherAF 
@jtnord I think you're the new maintainer?
=> Make check of logged-in user independent of UI

src/main/java/org/jenkinsci/test/acceptance/po/Login.java
https://github.com/jenkinsci/acceptance-test-harness/pull/631 checks the logged in user by the `getJenkins().getCurrentUser()`. Some internal testing using SSO, probed that method will fail in such situation. The reason is that the injector is retrieving always the same jenkins instance instead of the actual instance where the Login happened.
@jtnord @amuniz
=> jenkins.getCurrentUser() can use an incorrect context

src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
`MockUpdateCenter` should check that the `default` Update Site is configured in the Update Center page in a similar way that it's already checking that only one Update Site is configured.
@jtnord @amuniz
=> MockUpdateCenter should only be installed if the current UC is the default

pom.xml
workaround https://issues.apache.org/jira/browse/SUREFIRE-1798
=> failure stacktrace is no longer trimmed by surefire

src/main/java/org/jenkinsci/test/acceptance/po/Login.java, src/test/java/plugins/ActiveDirectoryTest.java
I'm seeing regularly flakiness in my ATH such as
```
Expected: has logged in user tmpuser
but: tmpuser is not logged in.
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at org.junit.Assert.assertThat(Assert.java:964)
at org.junit.Assert.assertThat(Assert.java:930)
at org.jenkinsci.test.acceptance.po.Login.doSuccessfulLogin(Login.java:67)
at org.jenkinsci.test.acceptance.po.Login.doSuccessfulLogin(Login.java:72)
```
I think in some cases the current check is not enough and the navigation happens before the login is really completed.
While working on this area, I notices `doLoginDespiteNoPaths` was useless since `doLogin` has been changed to not use path since https://github.com/jenkinsci/acceptance-test-harness/commit/ebdd746c9a9b57877e4035ee5674f0344b32818e. So I …
=> reduce flakiness of doSuccesfulLogin

src/main/java/org/jenkinsci/test/acceptance/po/FormValidation.java
`FormValidationTest` has been reliably failing for a while.
This fixes the cause of failure where the validation being selected was not the correct one.
possibly caused by https://github.com/jenkinsci/jenkins/pull/5195
Given this is in the upcoming LTS and mainline I have not bothered about backwards compatibility.
e.g. https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/master/lastCompletedBuild/testReport/core/FormValidationTest/java_8_split9___validate/
=> Fix form validation

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
if Cygwin was on the path `which` would work and return a cygwin path -
and those are not executable on windows..
e.g. fix the following:
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed:
2.293 s <<< FAILURE! - in core.FormValidationTest
[ERROR] validate(core.FormValidationTest)  Time elapsed: 2.254 s  <<<
ERROR!
com.google.inject.ProvisionException:
Unable to provision, see the following errors:
1) Error in custom provider, java.lang.IllegalStateException: The driver
executable does not exist: C:\cygdrive\c\tools\geckodriver
at
org.jenkinsci.test.acceptance.FallbackConfig.createWebDriver(FallbackConfig.java:293)
(via modules: org.jenkinsci.test.acceptance.guice.World ->
com.google.inject.util.Modules$OverrideModule -> …
```
=> Fix driver location support when run on windows and cygwin is in the path.

src/test/java/core/FormValidationTest.java
Firefox is broken, so just ignore failures from it for now.
see https://bugzilla.mozilla.org/show_bug.cgi?id=1693857 for details.
=> [JENKINS-65016] ignore failures from buggy firefox

docs/BROWSER.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Whilst you can use a system property (`webdriver.firefox.bin`) that is
cumbersome when running via surefire.  this exposes a system property
for advanced use to control which firefox to start.
=> Allow the firefox binary to be specified with `FIREFOX_BIN`

docs/BROWSER.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Adds support for `BROWSER=remote-webdriver-chrome` to run the tests in a remote chrome browser.
=> Add the ability to connect to a remote chrome session with `BROWSER=remote-webdriver-chrome`

README.md, docs/SUPPORT-BUNDLE.md, pom.xml, src/main/java/org/jenkinsci/test/acceptance/junit/AbstractJUnitTest.java, src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java, src/main/java/org/jenkinsci/test/acceptance/recorder/SupportBundle.java, src/main/java/org/jenkinsci/test/acceptance/utils/SupportBundleRequest.java
Collect a support bundle a after a failing test.
I found this very useful to investigate flaky tests as it collects way
more information than the standard output.
=> Attach support bundle after running the test

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Update form-element-path to 1.10 to avoid some detached dependencies, should fix the failing `git` plugin tests
Still will pull in sshd but updating that will mean this no longer runs in the current LTS.
=> update form-element-path to prevent some detached plugins

docs/DOCKER.md, pom.xml
To pick https://github.com/jenkinsci/docker-fixtures/pull/32 basically.So I can use docker-compose to launch the ATH in a trivially portable way.
This pr should be enough to test the change, I have manually tested this and on my personal CI system
=> Docker fixtures update to 1.11

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
I've observed this failing with `StaleElementReferenceException` from
time to time. I tracked it down to the plugin manager UI dynamic
behaviour (DOM elements show up and down) so the initially select
element becomes stale after a few milliseconds.
There is no way to know if the element will become stale or not, so the
only way I found to make this less flaky is by waiting 1 second and
retrying, then give up if it fails again.
=> Reduce flakiness on plugins check

src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
When crumb issuer is disabled (using `-Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true`), the support bundle collection fails because it doesn't handle this case.
=> Support bundle should not fail when crumb issuer is disabled

src/test/java/core/FreestyleJobTest.java
https://issues.jenkins.io/browse/JENKINS-65587
Test failed in latest cores as the build status icon was no longer an image but an SVG.
=> [JENKINS-65587] fix FreestyleJobTest#should_visit_build_with_permalink  in latest cores

src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/LdapContainer/Dockerfile
Ubuntu Precise is no longer supported and the container can not be
built.  Switch to Focal as the most recent ubuntu LTS
=> Update LdapContainer image to no longer use the ubuntu precise repo

src/main/tool_installers/updates/hudson.plugins.groovy.GroovyInstaller
Bintray is no more, so get the groovy artifacts from
https://groovy.jfrog.io/ui/packages which is the same place as a real
jenkins would get them from.
=> Fix GroovyPluginTest.run_groovy

src/main/java/org/jenkinsci/test/acceptance/utils/aether/ArtifactResolverUtil.java, src/main/resources/ath-container/run.sh
Fixes
```
Downloading: http://repo.jenkins-ci.org/public/org/jenkins-ci/plugins/form-element-path/1.10/form-element-path-1.10.hpi
org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact org.jenkins-ci.plugins:form-element-path:hpi:1.10 from/to repo.jenkins-ci.org (http://repo.jenkins-ci.org/public/): Permanent Redirect (308)
at org.eclipse.aether.connector.basic.ArtifactTransportListener.transferFailed(ArtifactTransportListener.java:43)
at org.eclipse.aether.connector.basic.BasicRepositoryConnector$TaskRunner.run(BasicRepositoryConnector.java:355)
```
=> Should use https

Jenkinsfile, src/main/resources/ath-container/Dockerfile
Fixes https://issues.jenkins.io/browse/INFRA-3006 until the
docker.inside is removed.
Root cause was https://github.com/jenkins-infra/packer-images/pull/57
which changed the default UID if the agent's `jenkins` user.
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>
=> fix: specifies UID and GID from the user running pipeline

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
```
java.lang.RuntimeException: java.io.FileNotFoundException: File does not exist: [redacted]
at org.jenkinsci.test.acceptance.controller.LocalController.tearDown(LocalController.java:295)
at org.jenkinsci.test.acceptance.controller.JenkinsController.close(JenkinsController.java:138)
at org.jenkinsci.test.acceptance.guice.TestCleaner.performCleanUp(TestCleaner.java:23)
at org.jenkinsci.test.acceptance.guice.World.endTestScope(World.java:66)
at org.jenkinsci.test.acceptance.junit.JenkinsAcceptanceTestRule$1.evaluate(JenkinsAcceptanceTestRule.java:64)
... 30 more
Caused by: java.io.FileNotFoundException: File does not exist: [redacted]
at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2275)
at org.jenkinsci.test.acceptance.controller.LocalController.tearDown(LocalController.java …
```
=> Don't display an ugly stacktrace if the JENKINS_HOME doesn't exist when cleaning up

src/main/java/org/jenkinsci/test/acceptance/utils/FormElementPath.java
Its not always possible to check for and install plugins when running tests against protected Jenkins instances where the test user has limited access. This PR adds the ability to instruct form-element-path check to skip check and assume it is installed.
In our case we use the acceptance test harness to run various sanity checks against our production instances. We don't want any golden service account that has admin access on all of our Jenkins instances, but rather a service user which behaves like a normal user. The check in FormElementPath prevents us in doing so, hence this PR.
=> Add ability to skip form-element-path plugin check

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java
In some cases it was causing `StaleElementReferenceException` when saving too early.
=> Wait for ConfigurablePageObject elements even if we don't need to navigate

src/main/java/org/jenkinsci/test/acceptance/plugins/workflow_shared_library/WorkflowGithubSharedLibrary.java
The change from radio button to dropdown list made in https://github.com/jenkinsci/workflow-cps-global-lib-plugin/pull/106 breaks `WorkflowGithubSharedLibrary`. 
CC @jtnord @MRamonLeon @Vlatombe
=> update WorkflowGithubSharedLibrary for JENKINS-62813

src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
Should workaround issues with recent firefox such as
```
org.openqa.selenium.ElementClickInterceptedException: 
Element <input class="  " name="[hudson.model.Hudson.Read]" type="checkbox"> is not clickable at point (244,207) because another element <div class="bd"> obscures it
```
=> Workaround some problems with checking elements with tooltip

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
=> Set firefox options consistently (local, container, remote)

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Follows up on #680 and #684
This fixes handling of open alerts when closing firefox in all scenarios (was covered only for local firefox)
=> Fix up firefox closing in all cases

src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java
Changing the access for `envVarOpts(...)` to protected so it doesn't need to be re-implemented in a derived class.
=> Change envVarOpts to protected for use in derived class

src/main/java/org/jenkinsci/test/acceptance/po/View.java, src/test/java/plugins/JobDslPluginTest.java
Fixes `JobDslPluginTest#are_columns_created`
At some point after the latest LTS, icons were switched from png to svg
=> Fix JobDslPluginTest#are_columns_created

docs/BROWSER.md, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java, src/test/java/org/jenkinsci/test/acceptance/recorder/HarRecorderTest.java
#684 specified the firefox options consitently across all firefox
browser types, however this broke remote-webdriver-firefox as the proxy was not localhost as far as firefox was conserned (as it was by definition remote).
This change makes the NIC to use for the proxy configurable so that you
can bind to a specific NIC and pass that to firefox via selenium.
Tested on Windows with `BROWSER=remote-webdriver-firefox`, `REMOTE_WEBDRIVER_URL=http://0.0.0.0:4444/wd/hub`  `SELENIUM_PROXY_HOSTNAME=redacted` and `JENKINS_LOCAL_HOSTNAME=redacted` 
Without this change all tests fail as the server (JENKINS) is unreachable.  with this change (and no environment set the same failure occurs), with this change and `SELENIUM_PROXY_HOSTNAME` the test passes as expected.
=> [JENKINS-66827] enable the ability to specify the proxy server

unsafe.key
The target file was removed in commit bd7fe3ffbff68c8df84f5f5dd1fe1f9eb2223993 in 2017 in #252 and replaced by the "docker-fixtures" dependency.
=> Remove broken symlink

src/main/java/org/jenkinsci/test/acceptance/ByFactory.java, src/main/java/org/jenkinsci/test/acceptance/plugins/maven/MavenModuleSet.java, src/main/java/org/jenkinsci/test/acceptance/plugins/priority_sorter/PriorityConfig.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/main/java/org/jenkinsci/test/acceptance/po/Job.java, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/ArtifactoryContainer/Dockerfile, src/test/java/core/FreestyleJobTest.java
Required for https://github.com/jenkinsci/jenkins/pull/5923
Already applied for radio buttons in
https://github.com/jenkinsci/acceptance-test-harness/pull/704
Browser can't click on the new checkboxes if you ask them to click the input, the label must be clicked instead.
=> Click label instead of input for checkbox

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java, src/test/java/core/PluginManagerTest.java
https://github.com/jenkinsci/jenkins/pull/5916 removes the check now button from the advanced page is it looks out of place there and doesn't really have any purpose being on that page as nothing you check will influence that page.
=> Forward compat for plugin manager modernise

pom.xml
Noticed after writing [jenkinsci/pom#42  (comment)](https://github.com/jenkinsci/pom/pull/42#issuecomment-992757629). As far as I can tell, all code in `src/{main,test}/groovy` was deleted sometime around 2016 in #209, so this plugin simply doesn't need to be included in the build anymore.
=> Remove GMaven plugin

Jenkinsfile
Seems unneeded to run on both? Running just Java 11 should save a lot of CI time
related to https://github.com/jenkinsci/jenkins/pull/6092 and https://github.com/jenkinsci/jenkins/pull/6083
=> Drop Java 8 on CI

src/main/java/org/jenkinsci/test/acceptance/po/Slave.java, src/test/java/plugins/SshSlavesPluginTest.java
Pre is no longer nested as pre -> pre, just pre -> div now.
Plugin manager tests worked fine because it just loads `pre`.
So adjusted to the same
=> Fix SSH Agents on recent core

Jenkinsfile
As we need to run the ATH against LTS version when they are released we
should ensure that the ATH itself has no regressions when run against
it.
This allows us to actually identify issues in the LTS as opposed to the
ATH no longer being compatible with it.
This requires that the ATH be compatible with the weekly and the LTS
line, which should have been mostly done but was never tested in the PR
builder.
As we have recently removed the Java8 test this should not add any extra load onto ci.jenkins.io that was not present a few weeks ago but adding Mark for this as I know the ATH is relatively intensive for CI resources.
There is possible going to be some test failures here that need to be fixed too (so WIP until at least I have a report on failures)
=> Test against the LTS as well as the weekly

grab-latest-rc.sh, src/main/resources/ath-container/run.sh
Let's recommend the https mirror in favor over the plain old http one.
=> Exchange Jenkins http mirror in favor of https

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java, src/main/java/org/jenkinsci/test/acceptance/po/JenkinsLogger.java, src/main/java/org/jenkinsci/test/acceptance/po/Node.java, src/main/java/org/jenkinsci/test/acceptance/po/WizardCustomizeJenkins.java, src/main/resources/ath-container/run.sh, src/test/java/core/InstallWizardTest.java, src/test/java/plugins/NodeLabelParameterPluginTest.java, src/test/java/plugins/SshSlavesPluginTest.java
Adapt to:
- https://github.com/jenkinsci/jenkins/pull/6455
- https://github.com/jenkinsci/jenkins/pull/6464
TODO:
- Regression in https://github.com/jenkinsci/credentials-plugin/pull/296 needs fixing, see https://github.com/jenkinsci/acceptance-test-harness/pull/759#issuecomment-1103226304
FYI @NotMyFault @janfaracik 
Let's get these builds green again before testing anything
=> Adapt to core and plugin changes

pom.xml, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/DockerAgentContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile, src/test/java/core/FormValidationTest.java, src/test/java/plugins/SshSlavesPluginTest.java
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/807
=> Upgrade `docker-fixtures` from 1.11 to 1.12

Jenkinsfile
Analogous to https://github.com/jenkins-infra/pipeline-library/pull/405. Should be possible as of https://github.com/jenkins-infra/helpdesk/issues/2984#issuecomment-1176418097.
=> [JENKINS-49707] Retry `node` block after infrastructure outages

pom.xml, src/main/java/org/jenkinsci/test/acceptance/docker/fixtures/MailhogContainer.java, src/test/java/plugins/WorkflowMultibranchTest.java
mail is discontinued and lives on as jakarta mail, alternative to https://github.com/jenkinsci/acceptance-test-harness/pull/827
=> build: Update mail to 2.x

pom.xml
Follow up to https://github.com/jenkinsci/acceptance-test-harness/pull/850
The artifact seems to be covered by our now updated versions of httpcore and -client and is now obsolete.
=> build: Remove old httpclient version

pom.xml
Gets a rid of the deprecated `git` and `java.level` options
=> chore: Minor pom cleanup

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java, src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
clicking on something produces some asynchronous change and the result
may or may not be present by the time we then try to do something.
instead of assuming the click immediately produces a result we wait for
the expect result before then interacting with it.
Fixes #866
=> Deflake SshSlavesPluginTest

pom.xml
The parent was updated to produce java11 bytecode in https://github.com/jenkinsci/acceptance-test-harness/pull/851#issuecomment-1192377049.
We should not yet be requiring Java11, indeed even when Jenkins is Java11 there is no rush to move to Java11 until we want to take advantage of a java11 library or use java11 features.
=> ATH should not be Java11 only (yet)

src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/AcceptFirstConnectionStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/KnownHostsFileStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/ManuallyProvidedKeysStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/NoVerificationStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/git_client/ssh_host_key_verification/SshHostKeyVerificationStrategy.java, src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java, src/test/java/plugins/GitPluginTest.java, src/test/java/plugins/WorkflowPluginTest.java
Proposed solution for https://github.com/jenkinsci/acceptance-test-harness/issues/877
Git-client 3.11.2 and later uses ‘Known hosts file’ as default strategy (instead of git-client 3.11.1 used ‘Accept first connection'), so tests will continue to fail, I suggest to use ’No verification’ strategy for now (but please confirm that ATH only connects to local Git servers and we do not care about MitM attacks), but once #878 will be merged better to switch to ‘Accept first connection’.
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/877
=> Use "No verification" ssh host key verification strategy

src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java, src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java, src/test/java/plugins/SshSlavesPluginTest.java
The FileDetector replaces any string that is also a local file by a
temp string and uploads that file to the remote system (at the location specified in the temp string).
This is generally a good thing, but sometimes the string that is also a file path is really a string and not something local or that needs replaces.
This is always the case for the JVM path when used in an external system.
Amends #780   detected when trying to bump this as a dependency in a closed source test suite.
```
[08/09/22 12:54:32] [SSH] Starting agent process: cd "/home/test" && /tmp/7fd87797-fc61-4f70-9b2d-079c37ac4a49/upload1745090074472040540file/java  -jar remoting.jar -workDir /home/test -jar-cache /home/test/remoting/jarCache
sh: 1: /tmp/7fd87797-fc61-4f70-9b2d-079c37ac4a49/upload1745090074472040540file/jav …
```
=> ByPass the FileDetector for things that are not files

src/main/java/org/jenkinsci/test/acceptance/utils/ElasticTime.java
`warnings-ng` failed in PCT with
```
java.lang.NumberFormatException: For input string: ".75C"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
at java.base/java.lang.Integer.parseInt(Integer.java:638)
at java.base/java.lang.Integer.parseInt(Integer.java:770)
at org.jenkinsci.test.acceptance.utils.ElasticTime.<init>(ElasticTime.java:48)
at org.jenkinsci.test.acceptance.utils.IOUtil.<clinit>(IOUtil.java:39)
at …
```
See https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#forkCount
> When terminated with "C", the number part is multiplied with the number of CPU cores. Floating point value are only accepted together with "C".
=> Do not assume that `forkCount` is an integer

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
This is a fix for #804 
Using the `webdriver` it is now possible to wait for the plugin to be installed.
I'm using the same kind of `xpath` as the one used in `UpdateCenter`: https://github.com/jenkinsci/acceptance-test-harness/blob/5fd86076fe1454f3f444871455d6f275af675c5b/src/main/java/org/jenkinsci/test/acceptance/po/UpdateCenter.java#L77-L85
=> installPlugin(File) now properly wait for plugin installation (#804)

src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java, src/test/java/plugins/GerritTriggerTest.java
This pull request fixes either 1.) Temporary Directory Hijacking Vulnerability, or 2.) Temporary Directory Information Disclosure Vulnerability, which existed in this project.
The system temporary directory is shared between all users on most unix-like systems (not MacOS, or Windows). Thus, code interacting with the system temporary directory must be careful about file interactions in this directory, and must ensure that the correct file permissions are set.
This PR was generated because the following chain of calls was detected in this repository in a way that leaves this project vulnerable.
`File.createTempFile(..)` -> `file.delete()` -> either `file.mkdir()` or `file.mkdirs()`.
This vulnerability can have one of two impacts depending upon which vulnerability it is.
1. Temporary …
=> [SECURITY] Fix Temporary Directory Hijacking or Information Disclosure Vulnerability

src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java, src/main/java/org/jenkinsci/test/acceptance/slave/SlaveController.java
Even if James' proposed changes were valid according to IJ, they didn't suffice for javadoc ☹️ 
I changed your proposal to a Class#method reference to be explicit.
(On a future note, these issues should probably fail the build, because addressing them post merge isn't the best imo)
=> Use proper `@see` javadoc notation

src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java
See https://github.com/jenkinsci/acceptance-test-harness/pull/890#issuecomment-1213431409 for context
Javadocs are pretty nasty...
(Head branch, please delete after merge.)
=> fix: Workaround (possible) javadoc 11 issue with `@see` and generics

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java, src/main/java/org/jenkinsci/test/acceptance/po/SlavesMixIn.java, src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java
The WebDriver may be wrapped or unwrapped so we need to unwarp it to get
the underlying driver to see if that is a RemoteWebDriver to configure
the FileDetector
amends #884
=> the WebDriver may be wrapped so we also need to unwrap it

pom.xml
This has been in the parent POM since https://github.com/jenkinsci/pom/pull/257 which was released in 1.76.
=> Remove redundant project.build.sourceEncoding property

pom.xml
This has been in the parent POM since https://github.com/jenkinsci/pom/pull/273 which was released in 1.79.
=> Remove redundant `maven.test.redirectTestOutputToFile` property

src/test/java/core/CreateItemTest.java, src/test/java/core/InstallWizardTest.java, src/test/java/core/JenkinsDatabaseSecurityRealmTest.java, src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java, src/test/java/plugins/AntisamyMarkupFormatterTest.java, src/test/java/plugins/AuthorizeProjectTest.java, src/test/java/plugins/ConfigFileProviderTest.java, src/test/java/plugins/CredentialsBindingTest.java, src/test/java/plugins/MSBuildPluginTest.java
JUnit's Assert#assertThat is deprecated in favor of hamcrest, which already is used in a plenty of occasions.
=> tests: Address #assertThat deprecations

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
Hello :wave:
For some internal tests we are writting at CloudBees relying on the ATH, we would like to use `getAvailableVersionForPlugin` which is private. 
This Pull Request is to make it public, but also to use a simplified XPath (and probably an easier way to retrieve
plugins' versions), and finally, to protect the test from flakiness by properly waiting for the plugins' list to be
loaded before searching for the version after using the filterbox.
Let me know if you'd like any changes to the proposed code.
=> getAvailableVersionForPlugin now properly waits for plugin list to refresh, and becomes public

Jenkinsfile.infra.ci.jenkins.io, src/main/resources/ath-container/Dockerfile
Ref. https://github.com/jenkins-infra/helpdesk/issues/3084
This PR adds a 2nd pipeline which goal is to build/test/deploy the ATH Docker image on the Jenkins controller infra.ci.jenkins.io.
- ~[ ] Link to relevant pull requests, esp. upstream and downstream changes~
=> chore(ATH Docker Image) build and deploy with infra.ci.jenkins.io

README.md
Adds an easy-to-use badge leading to the docker hub to grab the image with ease.
=> Add docker badge to README

src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
When plugins are injected using `LOCAL_JARS`, Jenkins fails to load them because of `java.io.IOException: Inconsistent file length: expected XXXXXX but only got YYYYYY`.
While I do not understand why it was working before - all relevant code seems in place for years. The discrepancy between metadata and actual file size is undesirable.
So this erases file size from metadata, forcing Jenkins to accept whatever is being served.
- [n/a] Link to relevant issues in GitHub or Jira
- [n/a] Link to relevant pull requests, esp. upstream and downstream changes
- [n/a] Ensure you have provided tests - that demonstrates feature works or fixes the issue
=> Fix plugin size mismatch when LOCAL_JARS is used

pom.xml
Apparently unused, if it's not a dependency for something else.
=> Drop XMLUnit-legacy

src/main/resources/ath-container/Dockerfile
Additionally, use an apache mirror to download maven.
=> Bump maven from 3.8.3 to 3.8.6 for the Dockerfile

pom.xml
A better version of https://github.com/jenkinsci/acceptance-test-harness/pull/947
=> Update trilead-ssh from build-217-jenkins-223.v546f979619d4 to build-217-jenkins-231.vda_87ca_d57ecf

src/main/resources/ath-container/Dockerfile
IntelliJ interprets `-bin` as part of the MAVEN_VERSION env. I don't see this as an issue in real test scenarios, but better be safe by escaping the version.
=> Escape maven version in Dockerfile

pom.xml
The selenium GAV is banned for any dependency updates by dependabot, but 2.64.0 of the htmlunit driver is the last version labeled as compatible with our Selenium version and should be safe to use.
=> Update htmlunit-driver from 2.33.0 to 2.64.0

Jenkinsfile
The change proposed runs the ATH after the weekly release, to highlight possible regressions quicker, and outside regularly core PR testing.
=> Run ATH on a weekly basis

Jenkinsfile
Apparently TUE is unsupported
```
java.lang.IllegalArgumentException: Could not instantiate {spec=0 18 * * TUE} for hudson.triggers.TimerTrigger: java.lang.reflect.InvocationTargetException
```
Let's use a numeric entry.
=> Use a numeric cron value

pom.xml, src/main/java/org/jenkinsci/test/acceptance/SshKeyPairGenerator.java
java xml libraries are provided by a java standard module (java.xml)
having them in 2 different jars causes the following compilation errors (shown by the eclipse compiler)
Fixes using base64 from the stock JDK at the same time (rather than xalan) as that is likely to be yanked in a future PR. (it was yanked here - but then reverted as I figured htmlunit may actually depend on xalan directly rather then use the xml apis).
```
* The package javax.xml is accessible from more than one module: <unnamed>, java.xml
* The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml
* The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
* The package javax.xml.xpath is accessible from more than one module: <unnamed>, java.xml
* The …
```
=> prevent split modules

src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java, src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneDockerController.java
AJP support was removed in Jetty 9 and Winstone 3.0 in https://github.com/jenkinsci/winstone/pull/22, never to return. As a result I ripped it out in https://github.com/jenkinsci/winstone/pull/291. But before I can release that PR, I need the ATH to drop its requirement on the existence of this option to avoid errors like
```
[2022-10-19T18:42:41.243Z] Exception in thread "main" java.lang.IllegalArgumentException: Unrecognized option: --ajp13Port=-1
[2022-10-19T18:42:41.243Z] 	at winstone.cmdline.CmdLineParser.parse(CmdLineParser.java:52)
[2022-10-19T18:42:41.243Z] 	at winstone.Launcher.getArgsFromCommandLine(Launcher.java:399)
[2022-10-19T18:42:41.243Z] 	at winstone.Launcher.main(Launcher.java:369)
[2022-10-19T18:42:41.243Z] 	at …
```
=> Remove references to `--ajp13Port`

src/test/java/plugins/WorkflowPluginTest.java
Deleting test added in #176. Known to be flaky.
https://github.com/jenkinsci/pipeline-groovy-lib-plugin/blob/master/src/test/java/org/jenkinsci/plugins/workflow/cps/global/GrapeTest.java covers most of this, and could be extended to use `RealJenkinsRule` for added strength as needed.
=> Deleting `WorkflowPluginTest.grapeLibrary`

Jenkinsfile.infra.ci.jenkins.io
Follow-up of https://github.com/jenkinsci/acceptance-test-harness/pull/905, [the corresponding pipeline library pull request](https://github.com/jenkins-infra/pipeline-library/pull/459) has been merged, no need to keep this annotation.
=> chore: remove `@Library` annotation in infra pipeline

src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java
Introduced in 6f6f371a84130888ead74f50cda778c4873de87a apparently with no use case, not currently used, and anyway broken as of https://github.com/jenkinsci/jenkins/pull/4339.
=> Removing unused and broken `JenkinsConfig.addCloud`

src/main/resources/ath-container/Dockerfile, src/main/resources/ath-container/run.sh, src/test/java/plugins/OwnershipPluginTest.java
110 (current one available in ppa) seems to have some issues with Selenium making the existing code not work anymore
~So to validate is the firefox version I am using here firefox esr 108, if that solves problems I will rewrite to use the standard firefox instead, sadly 108 version is not on the ppa repository anymore, that is why for this tests I am using esr~
The last known good version was 108.0.2, which is now installed, and fixed,  in the docker image. Basically I copied and adapted the installation procedure from the selenium docker images.
=> Use older 108 version of firefox in ath-container

ath-container.sh, grab-latest-rc.sh, jut-server.sh, src/main/resources/ath-container/run.sh, src/main/resources/ath-container/set-java.sh, src/main/resources/ath-container/vnc.sh
While reading these shell scripts my eyes started twitching: a variety of different conventions were in place for indentation, quoting style, conditionals, shebang lines, etc. I fixed this up using a combination of automated tools and manual editing. The result is `shfmt`-clean, (mostly) `shellcheck` clean, and a whole lot easier to read. I recommend reviewing this with the "hide whitespace changes" feature enabled.
=> Clean up shell scripts

src/main/resources/ath-container/run.sh
Per the [Bash documentation](https://www.gnu.org/software/bash/manual/bash.html#Here-Documents):
> If the redirection operator is `<<-`, then all leading tab characters are stripped from input lines and the line containing _delimiter._ This allows here-documents within shell scripts to be indented in a natural fashion.
Note that only tab character are stripped. Spaces are not stripped. For this reason, it is _objectively_ better to use tabs rather than spaces for indentation in `bash(1)` scripts.
Now that #1086 has been merged and `run.sh` is `shfmt(1)`-clean, tabs are being used consistently for indentation in that file. As the above documentation states, "this allows here-documents within shell scripts to be indented in a natural fashion." This is an improvement over the status quo …
=> Use `<<-` here document redirection operator where applicable

pom.xml
Fix a `RequireUpperBoundDeps` error and remove a no longer necessary `<trimStackTrace>` option that is now included in the latest parent POM.
=> Upgrade parent POM from 1.94 to 1.97

Jenkinsfile, pom.xml, src/main/resources/ath-container/run.sh
Fixes #736. Preparatory work for #963. See self-review for details.
High-level changes:
- Retry CI stage on agent failure, consistent with other jobs.
- Publish incrementals, just like other jobs.
- Set `maven.repo.local` inside `WORKSPACE_TMP` in CI, just like jenkinsci/bom#1842.
- Define `jenkins.version` in `pom.xml`, where user-submitted PRs may set it to an incremental build. This version will be updated by Dependabot.
- Define an LTS Maven profile with the LTS version. This will need to be updated by the release lead after shipping an LTS.
- When `latest`, `lts`, or a version number are provided, have `run.sh` delegate to Maven rather than trying to do the download itself. Continue to support usages of a URL or a filesystem path to the WAR.
- Update documentation.
- Observe …
=> Revamp build/CI

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
the selenium containers failed to start with 
```Was passed main parameter '-port' but no main parameter was defined in your arg class```
the option in Selenium 4 is
```
-p, --port
Port to listen on. There is no default as this parameter is used by
different components, for example Router/Hub/Standalone will use 4444
and Node will use 5555.
```
=> Update Selenium parameter for Selenium 4

pom.xml
Routine parent POM upgrade. Can this please be released? This adds `Implementation-Build` to `META-INF/MANIFEST.MF`, which I need in order to start making progress on the Launchable prototype.
=> Upgrade parent POM from 1.97 to 1.98

Jenkinsfile
This `Jenkinsfile` is indented inconsistently, making it extremely difficult to edit. This PR introduces (manual) two-space consistent indentation. Those who feel some degree of antipathy toward Spotless need not fear this change. Reviewers are encouraged to use the **Hide whitespace** feature when reading this diff.
=> Fix indentation in `Jenkinsfile`

Jenkinsfile
This `Jenkinsfile` includes a matrix of combinations, which is a common pattern in builds (common enough that declarative Pipeline jobs feature dedicated syntax for it). This PR refactors the `Jenkinsfile` to use the Groovy `combinations` method to produce the combinations, which improves readability a little I think. Even though most of the combinations only have a single entry, this makes the code easier to read and makes it easier to add additional combinations in the future. Right now the only reason we probably don't have more combinations is that it would be too expensive, but Launchable should allow us to add more combinations without breaking the budget. This PR is best reviewed with whitespace changes hidden.
=> Refactor combinations in `Jenkinsfile` for readability

src/main/java/org/jenkinsci/test/acceptance/plugins/git/GitRepo.java
fixes: #745
tested with `mvn test -Dtest=plugins.WorkflowPluginTest#hello_world_from_git` locally (windows)  ([source](https://github.com/jtnord/acceptance-test-harness/blob/0f5270fd68e2d278188cf6ebd911a13de418d514/src/test/java/plugins/WorkflowPluginTest.java#L99-L119))
There will be some environments where this does not work (no ssh.exe is available - and then if your git global config is set to use `plink` (an option when installing) then whilst gitRepo works, tests will eventual fail due to the git-client plugin not supporting this, and also https://issues.jenkins.io/browse/JENKINS-71122 is ssh.exe is on the path but not in a "well known" location (workaround is to set GIT_SSH to the path of the ssh executable).
these issues are either environmental or bugs in a plugin not the ATH. …
=> enable `GitRepo` to work on windows

pom.xml
The [new version](https://github.com/jenkinsci/extensibility-api/releases/tag/extensibility-1.6) supports Java 17 and has a recent Guice dependency, obviating the existing `sisu-inject-plexus` exclusion.
=> Upgrade Extensibility API from 1.5 to 1.6

src/main/resources/ath-container/Dockerfile, src/main/resources/ath-container/set-java.sh
Adds the `openjdk-17-jdk` package to the Docker image to enable local testing on Java 17. (The test suite does not currently work on Java 17.) Note that everywhere this image is consumed, we should be calling `set-java.sh` to a well-defined Java version rather than relying on the default. All consumers in this repository look fine (including this repository's `Jenkinsfile` build, which always explicitly sets Java 11), but Jenkins core's `ath.sh` is not doing this, so it will need to be adapted when we pull in this new image there.
=> Add Java 17 to Docker image

src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/main/java/org/jenkinsci/test/acceptance/po/Control.java
This PR addresses the deprecation of the PR title, by migrating to `Duration.of*` according to the javadocs.
It appears the method to use wasn't introduced when the deprecation was put in place in https://github.com/jenkinsci/acceptance-test-harness/pull/973/files#diff-addf4f5ac9e35192228ef3c7c0fa96e212baa9f6ad9c71f0c1ef42320547463bR227f
Therefore, I introduced it in this PR, while removing the deprecated method.
=> Address `#pollingEvery(long duration, TimeUnit unit)` deprecation

Jenkinsfile
ATH builds are quite resource heavy. When doing dependabot updates or merging multiple PRs in a row, every merge is build independently.
To keep the amount of occupied resources surveyable, I'd like to prevent concurrent builds, similar to core and other major repositories.
=> Disable concurrent builds on the main branch

src/main/java/org/jenkinsci/test/acceptance/junit/Wait.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
This PR completes the cleanup from https://github.com/jenkinsci/acceptance-test-harness/pull/1119 by removing the deprecated method. 
All occurrences on our end have been updated.
=> Remove deprecated `withTimeout(long duration, TimeUnit unit)` in favor of `withTimeout(Duration timeout)`

.github/dependabot.yml, .github/renovate.json, src/main/resources/ath-container/Dockerfile
ref https://github.com/jenkinsci/acceptance-test-harness/pull/1141#pullrequestreview-1406969616
I left the existing Dockerfile configurations of dependabot in place, given they all use ubuntu 22 and don't require frequent updates.
=> Track geckodriver

pom.xml
There's no such artifact with the pattern `org.slf4j:jcl-api` available on the [central repository](https://repo1.maven.org/maven2/org/slf4j/jcl-api).
Although, `slf4j-jcl` exists, it appears we can remove the dependency safely because it doesn't exist and the build didn't complain about it before.
=> Remove jcl-api because it doesn't exist

pom.xml, src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
Upgrade Maven from 3.3.9 to 3.8.1 which also involves a migration from Aether to `maven-resolver`. I followed the example at https://github.com/apache/maven-resolver/blob/89dadad860dc802fd328f2c7a29e7285b599ecde/maven-resolver-demos/maven-resolver-demo-snippets/src/main/java/org/apache/maven/resolver/examples/guice/DemoResolverModule.java when adapting to the breaking API changes.
=> Upgrade Maven from 3.3.9 to 3.8.1

.github/renovate.json
While we could try to keep up with Maven updates, my experience maintaining various Maven plugins in the Jenkins ecosystem is that doing so is a lot of effort for very little benefit: constant small API changes and Enforcer conflicts, for example. Recently we configured all our Maven plugins to use a stable baseline of Maven 3.8.1 and turned off Dependabot updates for Maven. This PR does the same for this repository. While not an apples-to-apples comparison (because this is not a Maven plugin), I think this will make it easier to maintain this repository. Maven upgrades can be done across the Jenkins ecosystem whenever we decide to shift to a newer Maven baseline and usually require a few API adaptations and a bit of testing.
=> Ignore Maven dependency updates

Jenkinsfile
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/988
=> chore(Jenkinsfile) Use `jenkins/ath` instead of rebuilding it

src/main/java/org/jenkinsci/test/acceptance/AbstractPipelineTest.java, src/main/java/org/jenkinsci/test/acceptance/ByFactory.java, src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java, src/main/java/org/jenkinsci/test/acceptance/po/PageObject.java, src/main/java/org/jenkinsci/test/acceptance/utils/PipelineTestUtils.java, src/test/java/plugins/AuditTrailPluginTest.java, src/test/java/plugins/ConfigFileProviderTest.java, src/test/java/plugins/ExternalWorkspaceManagerPluginTest.java
This PR fixes the compiler warnings in the Jenkins core master build that are actually caused by the test harness code. See https://ci.jenkins.io/job/Core/job/jenkins/job/master/java
In addition it fixes resource leaks.
The aim is not to have no warnings locally (there are way more in my IDE), but rather to have zero warnings on the CI server.
This is not relevant for any changelog.
Just compiled locally. I'm not sure if I could really verify Selenium based tests on my Windows machine with sufficient trust.
=> Fix compiler warnings in jenkins core master caused by test harness

pom.xml
hancrest -core and -library are deprecated in favor of `hamcrest`.
=> Update hamcrest to non-deprecated package

.github/renovate.json
see https://github.com/jenkinsci/acceptance-test-harness/pull/1174 and https://github.com/jenkinsci/acceptance-test-harness/pull/1205
they should have been grouped together
untested, but can iterate next time there's a selenium release
=> Group selenium deps

pom.xml
I have seen some interesting interactions and there is some static code in the test-harness, so do not attempt to reuse surefire.
this should reduce a bit of flakyness and should not be noticable given the overhead of starting a Jenkins insance for test.
This is also the setting we use for plugins in the plugin pom where the %age overhead would be more noticable than here
=> disable surefire reuse of forks

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java, src/main/java/org/jenkinsci/test/acceptance/controller/WinstoneController.java, src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java, src/test/java/org/jenkinsci/test/acceptance/recorder/HarRecorderTest.java
The controller logs just use master0000 as the logId was using the port and since we use dynamic port the value is non stable (changes during he test) and also collides (every controller will start as master0000)
Also adds diadnostic logging to HARRecprder as I have been seeing tests where firefox can not connect to Jenkins as the browser is not running and test failures where the HAR can not be gathered as the proxy has already been stopped.
```
java.lang.IllegalStateException: Proxy server is already stopped. Cannot re-stop.
at com.browserup.bup.BrowserUpProxyServer.stop(BrowserUpProxyServer.java:514)
at com.browserup.bup.BrowserUpProxyServer.stop(BrowserUpProxyServer.java:493)
at org.jenkinsci.test.acceptance.recorder.HarRecorder.recordHar(HarRecorder.java:120)
at …
```
=> Add extra debuging and fix controller logs

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
Tidy up the contract around the HAR being recorded and the proxy being created
The proxy was created on the first call to getProxy and every call after
when the har had been recorded for the previous test.
the Fallback config was responsible for updating the proxy with the test
name
This spread the responsibility for the HAR recording between FallbackConfig
and the HarRecorder.
This change moves the initialisation of the har from the FallbackConfig to
the HarRecorder itself, and no longer shuts down the proxy if a test causes
the har to be recorded.
Whilst the Proxy would not be closed, this is the status quo today and it is
terminated when the surefire JVM exists.
So now we will start the proxy only once per surefire JVM.
This could be a candidate for auto-wiring but that is left for a …
=> improve the contract around HARRecording

src/test/java/plugins/AntPluginTest.java
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1133
Checking for a specific Java version doesn't make much sense, if tests are supposed to be run independently of a Java version.
=> Workaround ant's specific Java version test

pom.xml
>  [WARNING] Parameter 'additionalparam' is unknown for plugin 'maven-javadoc-plugin:3.5.0:jar (attach-javadocs)'
=> Replace 'additionalparam' with doclint

src/main/resources/ath-container/Dockerfile
https://github.com/jenkinsci/acceptance-test-harness/pull/1262 fails on infra.ci because of:
```
21:18:13  #11 ERROR: process "/bin/bash -o pipefail -c curl -ffSLO [https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-\"$MAVEN_VERSION\"-bin.tar.gz](https://dlcdn.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-/%22$MAVEN_VERSION/%22-bin.tar.gz) &&     tar -xvzf apache-maven-\"$MAVEN_VERSION\"-bin.tar.gz -C /opt/ &&     mv /opt/apache-maven-* /opt/maven" did not complete successfully: exit code: 22
```
a new version has been released and the old one is no longer available on the mirror specified. The change proposed uses a generic dl URL, being more robust for future updates.
=> Update maven URL to be more robust for maven updates

Jenkinsfile
Each build weight ~100 Mb (mainly due to junit-attachment which is 80 to 90 Mb per build).
This PR proposes to discard old builds: no more than 10 builds on the principal branch (~1 month during the past 6 months) instead of 50 and no more than 5 builds per PR.
The goal is to decrease the amount of storage used on ci.jenkins.io and the I/O pressure.
=> chore(Jenkinsfile) discard old builds (5/PR and 10 on primary branch)

Jenkinsfile, src/main/resources/ath-container/run.sh
This PR activates the use of artifact caching proxy for this repository.
Closes https://github.com/jenkinsci/acceptance-test-harness/issues/963
Ref: https://github.com/jenkins-infra/helpdesk/issues/3481#issuecomment-1608840888 & https://github.com/jenkins-infra/helpdesk/issues/2752
Successfully ran a replay with the `no-tranfer-progress` option removed from `run.sh` to check the use of the artifact caching proxy: https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1279/4/
```[tasklist]
```
=> Use artifact caching proxy for `acceptance-test-harness`

pom.xml, src/main/java/org/jenkinsci/test/acceptance/controller/LocalController.java
with the current java11 I have not had a successful stacktrace when a test timesout.
As we do not require parsing of the stacktrace we can replace dumpling with standard calls.
jstack works on windows (without the jstack.exe).
Whilst this requires jstack to be on the path - as we are calling java to launch this should be an acceptable requirement for the ATH.
fixes #1222
Tested on windows 11 with a test that is consistently timing out in a specific environment
validate that the threaddump.log is valid.
```[tasklist]
```
=> replace dumpling with a call to jstack

README.md, docs/WALKTHROUGH.md
Hi, I have made a walkthough for how to use the ATH when testing changes made to a local version of Jenkins. I was not entirely confident about where to link it in the main ReadMe, please let me know if you think it is not in the correct place.
Hopefully someone will find this useful 😄 
This is a documentation PR, I have tested locally by veiwing the files and making sure they display corectly.
```[tasklist]
```
=> Add a walkthrough document and linked on the ReadMe

src/main/java/org/jenkinsci/test/acceptance/po/PluginManager.java
it has been observed that plugin installation was flaky as the installation clicked the button but then immediately looked like there where no plugins to update.
the HAR showed that the response to the install POST had not finished and then the GET call to the UpdateCenter was made. As the previous call had not completed, there where no installation jobs present and so deemed that there was nothing to wait for.  the check then fails as the plugin has not infact been installed
e.g.
```
java.lang.IllegalArgumentException: workflow-multibranch plugin not installed
at org.jenkinsci.test.acceptance.po.Plugin.<init>(Plugin.java:49)
at org.jenkinsci.test.acceptance.po.Jenkins.getPlugin(Jenkins.java:214)
at org.jenkinsci.test.acceptance.po.UpdateCenter.waitForInstallationToComplete(UpdateCenter.ja …
```
=> Installing plugins was flaky

src/main/resources/ath-container/Dockerfile, src/main/resources/ath-container/set-java.sh
Prerequisite for #1320. Without changing the existing configuration (Java 17 as default, Java 11 available), add OpenJDK 21 to the image.
Verified OpenJDK 17 was still the default. Verified I could switch to OpenJDK 21 with `set-java.sh` and ran `java -version` successfully.
=> Install OpenJDK 21 in ATH image

src/main/resources/ath-container/Dockerfile
Without fixing #1322, restore the status quo as of before #1321 by allowing the image to build (but not run) on AArch64.
Built the image on both amd64 and AArch64.
=> Support Java 21 on AArch64

Jenkinsfile
as per https://github.com/jenkins-infra/helpdesk/issues/3673#issuecomment-1660606208
this PR select a spot instance on first try or falls back to on-demand.
spot instance ensure that most of the builds are cheap but we don't want builds to fail due to infra issues.
=> chore(jenkinsfile): use spot instance for the first try or falls back to on-demand

src/main/tool_installers/updates/hudson.tasks.Maven.MavenInstaller
amends #1327 to provide the required metadata
Without the metadata all the changed tests became flaky or failed reliably (depending on infrastructure setup) due to requiring a successful update from the update center.
none
```[tasklist]
```
=> Update missing tool installation for maven 3.9.4

src/test/java/plugins/GitLabPluginTest.java
`GitLabPluginTest.gitLabGroupFolderOrganization` is being consistently "flaky". It will always fail on one of the jdk 21 tests, sometimes on jdk 11. Disabling this test until it can be fixed
See #1365 
```[tasklist]
```
=> disable flaky gitlab test

pom.xml
Jenkins 2.426.1 has been released and is being used on ci.jenkins.io and in many other configurations.  Let's use it for acceptance testing as well.
Rely on ci.jenkins.io to do the testing.  2.426.1 pre-release testing with ATH was successful.
```[tasklist]
```
=> Use 2.426.1 in lts profile instead of 2.414.3

src/test/java/plugins/GroovyPluginTest.java, src/test/java/plugins/JobDslPluginTest.java, src/test/java/plugins/ScriptSecurityPluginTest.java
Reverting #1444 since these should pass ~as soon as https://github.com/jenkinsci/script-security-plugin/pull/549 is deployed~ now that it is deployed.
Fixes https://github.com/jenkinsci/acceptance-test-harness/pull/1463
=> Enable `script-security` tests again

src/main/java/org/jenkinsci/test/acceptance/po/BuildHistory.java
previously it was `table`, now it is `a` (theoretically it can also be `div` but not for the build history).
See https://github.com/jenkinsci/jenkins/pull/8821
```[tasklist]
```
=> compatibility for new progressbar rendering

docs/CONTROLLER.md, src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
Add a new environment variable `SKIP_UPDATES` to skip Jenkins plugin updates before starting the tests. Dramatically reduces the startup time for tests. Using this option makes sense when you are running tests against a Jenkins instance that is already set up with the plugins you need (see environment variable `PLUGINS_DIR`).
=> Add an option to skip initialization of the fake update center

src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/BuildStatisticsPortlet.java, src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/LatestBuildsPortlet.java, src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/UnstableJobsPortlet.java
Adapt to the changes from https://github.com/jenkinsci/dashboard-view-plugin/pull/328
```[tasklist]
```
=> fix dashboard-view plugin tests

src/main/java/org/jenkinsci/test/acceptance/plugins/credentials/Credential.java, src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java, src/test/java/plugins/DeclarativeAssistantMigrationTest.java
* Updates selectors to match latest release of credentials dialog (follow-up for https://github.com/jenkinsci/credentials-plugin/pull/500 ) 
* Updates selector for Declarative Migration Assistant (follow-up for https://github.com/jenkinsci/declarative-pipeline-migration-assistant-plugin/pull/232)
Observed that CI passed
```[tasklist]
```
=> Update selectors: credentials dialog, declarative migration assistant

pom.xml, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/plugins/config_file_provider/ConfigFileProvider.java, src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_credentials/SshCredentialDialog.java, src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/JobsMixIn.java, src/main/java/org/jenkinsci/test/acceptance/po/SlavesMixIn.java, src/main/java/org/jenkinsci/test/acceptance/selenium/Scroller.java, src/test/resources/artifactory_plugin/quickstart/gradle/wrapper/gradle-wrapper.properties, src/test/resources/artifactory_plugin/quickstart/gradlew.bat
Bundles several dependency updates into one PR and resolves compatibility issues.
#1472 
#1465 
#1471
#1411
#1483 
CI passed
```[tasklist]
```
=> Update Java dependencies: Selenium, GitLab API, Netty, parent POM

src/main/java/org/jenkinsci/test/acceptance/po/JenkinsConfig.java, src/main/java/org/jenkinsci/test/acceptance/po/SnippetGenerator.java, src/test/java/org/jenkinsci/test/acceptance/po/SnippetGeneratorTest.java
I use this PO in the ATH tests of the warnings plugin:
https://github.com/jenkinsci/warnings-ng-plugin/blob/5effdb04eaa5dc1025085ac41257e5a6ade4de80/ui-tests/src/test/java/io/jenkins/plugins/analysis/warnings/SnippetGeneratorUiTest.java
=> Add a page object for the snippet generator

.github/workflows/verify-gradle-wrapper.yaml
I noticed https://github.com/jenkinsci/acceptance-test-harness/commit/865cecc01a41076b69cbc0069a953f78e00f941d and in case someone bumps the wrapper in the future, if needed, the action added validates whether the .jar is legit or not.
=> Validate Gradle wrapper

pom.xml
Unclear why we missed 2.440.1 as LTS
https://github.com/jenkins-infra/release/issues/510 is the 2.440.2 release checklist and it references this task.
No testing performed.  Relying on ci.jenkins.io to do the work.
```[tasklist]
```
=> Use Jenkins 2.440.2 as LTS version

src/main/java/org/jenkinsci/test/acceptance/update_center/MockUpdateCenter.java
the size for every plugin is set to `-1` which creates excessive spam when running.
prevents spam like the following
```
Apr 12, 2024 11:02:22 AM org.jenkinsci.test.acceptance.update_center.MockUpdateCenter updating
INFO: for SBuild updating size from 19,704 to -1
Apr 12, 2024 11:02:22 AM org.jenkinsci.test.acceptance.update_center.MockUpdateCenter updating
INFO: for SSSCM updating size from 11,287 to -1
Apr 12, 2024 11:02:22 AM org.jenkinsci.test.acceptance.update_center.MockUpdateCenter updating
INFO: for StashBranchParameter updating size from 1,206,570 to -1
Apr 12, 2024 11:02:22 AM org.jenkinsci.test.acceptance.update_center.MockUpdateCenter updating
INFO: for Surround-SCM-plugin updating size from 41,279 to -1
Apr 12, 2024 11:02:22 AM …
```
=> prevent spam when setting size to -1

src/test/java/core/CreateItemTest.java, src/test/java/core/FreestyleJobTest.java
Work around [JENKINS-73034](https://issues.jenkins.io/browse/JENKINS-73034) and [JENKINS-73168](https://issues.jenkins.io/browse/JENKINS-73168) to stabilize the test suite; those two tickets track the long-term fix. Once this is merged and the weekly line is green again, I will file two additional ATH tickets to remove these workarounds, blocked on JENKINS-73034 and JENKINS-73168 respectively.
CI build of weekly line
Fixes #1544, fixes #1545
=> Work around JENKINS-73034 and JENKINS-73168

.github/dependabot.yml, Jenkinsfile, ath-container.sh, pom.xml, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/GitContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/JiraContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/SshAgentContainer/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/Tomcat10Container/Dockerfile, src/main/resources/org/jenkinsci/test/acceptance/docker/fixtures/XvncSlaveContainer/Dockerfile, src/test/java/plugins/AntPluginTest.java, src/test/java/plugins/SshSlavesPluginTest.java
Updates Docker test fixtures to the new Ubuntu 24.04 and Java 17 based release, as well as upgrading a handful of container images in this repository (ones that seem to be still used) to Ubuntu 24.04 and Java 17. While I was here I also switched the default environment from 11 to 17 since we are getting close to the cutoff date.
=> Upgrade test containers to Ubuntu 24.04 and Java 17

src/test/java/core/FreestyleJobTest.java
Assertion was disabled due to user interface change that has been modified in Jenkins 2.459 to again report when the build has no changes.
[JENKINS-73168](https://issues.jenkins.io/browse/JENKINS-73168) fixes it in Jenkins 2.459.
Fixes #1548
This reverts part of commit 4d71d1b782a23b8eb94b914bf86771f212f3b7ed.
Tested by running the modified test with JENKINS_WAR set to a copy of the 2.459 Jenkins war file.
=> Enable 'Build has no changes' assertion in FreestyleJobTest

pom.xml, src/main/java/org/jenkinsci/test/acceptance/plugins/dashboard_view/read/BuildExecutorStatus.java, src/test/java/plugins/DashboardViewPluginTest.java
with the removal of idle executors (https://github.com/jenkinsci/jenkins/pull/9177) we no longer have a big table so find the corresponding div for the headers. As executors are only shown while building remove the check for shown executors completely.
fixes #1603
=> adjust to removal of idle executors

src/main/java/org/jenkinsci/test/acceptance/po/SnippetGenerator.java
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1619
Verified locally, looks like YUI automatically appends -button to the ID thats set but the plain html button uses the expected ID.
=> Fix SnippetGeneratorTest

Jenkinsfile
Ref. jenkins-infra/helpdesk#4192 (comment)
=> chore(Jenkinsfile) increase DockerHub rate limit with authentication

src/main/resources/ath-container/Dockerfile
https://github.com/mozilla/geckodriver/issues/1956 has been fixed
=> Update `geckodriver` URL

Jenkinsfile
fixup of #1634 (b1e9d055)
This PR uses the DockerHub authentication in the proper location as pointed out by @basil in https://github.com/jenkinsci/acceptance-test-harness/pull/1634#pullrequestreview-2200077460 (sorry for the noise)
The DockerHub login now happens at the beginning of each test:
Note: the long term solution would be to use a local Docker cache-through proxy as per https://github.com/jenkins-infra/helpdesk/issues/4192#issuecomment-2250887939.
=> chore(pipeline) Limit Docker API rate limit when testing

.github/renovate.json, src/main/resources/ath-container/Dockerfile
Packages take a long time to download on my slow internet connection, so by installing them at the beginning we can most effectively leverage the Docker cache when making modifications to later parts of the build.
=> Install packages at beginning of Docker build

ath-container.sh, src/main/resources/ath-container/Dockerfile
Apparently if we don't have UID/GID set to 1001 then we can't use pre-built images in CI.
=> Revert UID/GID changes from #1645

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/test/java/core/FormValidationTest.java
Without dropping support for Firefox 123 and earlier, add support for Firefox 129 or newer. Note that Firefox 124 through 128 are known to not work, as explained in https://github.com/mozilla/geckodriver/issues/2182#issuecomment-2180048632.
- CI build of this PR
- CI build with Firefox 129 in #1648
Fixes #1639
=> Add support for Firefox 129 or newer

src/main/resources/ath-container/Dockerfile
Fixes #1170
Draft until the release of Firefox 129 (currently scheduled for August 6, 2024)
=> Upgrade Firefox from 123.x to 129.x

src/main/resources/ath-container/Dockerfile
Apache Maven 3.9.9 released a day or two ago and is available from https://maven.apache.org/download.cgi .  Let's update to use that most recent release of Apache Maven.
Also updates the download URL to use the current URL from
https://maven.apache.org/download.cgi
That URL uses the content delivery network of the Apache project
The [ASF blog](https://news.apache.org/foundation/entry/apache-software-foundation-moves)- describes their transition to a content delivery network.
Apache Maven 3.9.9 is successfully building and testing the plugins that I maintain and I'm using it on all my development machines, controllers, and agents.
No issues detected since installing it a day ago.
I also tested the `curl` command from my RHEL 8 computer and confirmed that it downloaded the correct file
Will …
=> Use Apache Maven 3.9.9 instead of 3.9.8

src/test/java/plugins/JavadocPluginTest.java, src/test/java/plugins/PipelineTest.java
Javadoc tests appear to be broken on the main branch, apparently because version 3.10.0 of the Apache Maven Javadoc Plugin was just released and stores HTML files in a new directory.
=> Adapt to Apache Maven Javadoc Plugin 3.10.0

Jenkinsfile, ath-container.sh, src/main/resources/ath-container/Dockerfile
The permissions on the mounted `docker.sock` where incorrect for the current user, which lead to workarounds setting the docker binary SUID.
However this was a bit hacky and if programmatic access to docker was needed (e.g. TestContainers, or anything else that used the socket and not the binary) then access would fail.
Rather than set the binary SUID which only works for some of the docker use cases, we add the `ath-user` to the docker group that has access to the socket on the host at run time.
extracted from #705 
Testing in this PR and #705 for the test containers case.
https://ci.jenkins.io/job/Core/job/acceptance-test-harness/job/PR-1705/4/testReport/plugins/OicAuthPluginTest/ (shows the test-container tests run and do not fail because of docker) …
=> Cleanup the docker permission issues.

src/main/java/org/jenkinsci/test/acceptance/po/OicAuthConfigurationMode.java, src/main/java/org/jenkinsci/test/acceptance/po/OicAuthSecurityRealm.java, src/test/java/plugins/OicAuthPluginTest.java
See https://github.com/jenkinsci/acceptance-test-harness/issues/1723
https://github.com/jenkinsci/oic-auth-plugin/pull/399 changes the describables in the plugin, so the `OicAuthPluginTest` must be adapted. As this test has been there for less than 2 weeks, I don't see any need to keep any backward compatibility checking the plugin version.
=> Adapt the OicAuthPluginTest to the changes in the describables

pom.xml, src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
See https://github.com/jenkinsci/maven-hpi-plugin/pull/668. Adapting to https://github.com/apache/maven-resolver/pull/140 and https://github.com/apache/maven-resolver/pull/319. (Previously: #1153).
=> Upgrade Maven from 3.8.1 to 3.9.6

.github/renovate.json, pom.xml, src/main/java/org/jenkinsci/test/acceptance/utils/aether/AetherModule.java
Migrate to Sisu and drop use of deprecated AetherModule (is removed in Resolver 2.x).
This PR uses "fully fledged" Sisu to create `RepositorySystem` instance, and will discover (using sisu index) dynamically any JSR330 component that is present on classpath at the moment `AetherModule` is being constructed.
Also, Guice and Sisu are changed (by exclusion from transitive dep and explicit addition as direct dependency) to "no asm" versions (these have no shaded in ASM), and since ASM was already on path (was 9.2) updated to latest 9.7. Now Guice and Sisu and that something (that pulled ASM in orginally) all use same ASM version 9.7.
CI build
Fixes #1730
=> Migrate from deprecated `org.eclipse.aether.impl.guice.AetherModule` to Sisu

pom.xml, src/main/java/org/jenkinsci/test/acceptance/plugins/ssh_slaves/SshSlaveLauncher.java
https://github.com/jenkinsci/credentials-plugin/pull/551
=> Forward compatibility with jenkinsci/credentials-plugin#551

src/main/java/org/jenkinsci/test/acceptance/po/ConfigurablePageObject.java, src/main/java/org/jenkinsci/test/acceptance/po/View.java
This allows to remove customizations done in `View` PO (initially introduced in #421)
Needed for https://github.com/jenkinsci/jenkins/pull/9813
=> Avoid depending on labels, rather use the button name

src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/MatrixAuthorizationStrategy.java, src/main/java/org/jenkinsci/test/acceptance/plugins/matrix_auth/ProjectMatrixProperty.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java
Fixes https://github.com/jenkinsci/acceptance-test-harness/issues/1803
```
BROWSER=firefox JENKINS_VERSION=2.462.3 mvn test -Dtest=MatrixAuthPluginTest
BROWSER=firefox JENKINS_VERSION=2.462.3 VERSION_OVERRIDES=matrix-auth=3.2.2 mvn test -Dtest=MatrixAuthPluginTest
BROWSER=firefox JENKINS_VERSION=2.462.3 VERSION_OVERRIDES=matrix-auth=3.2.3 mvn test -Dtest=MatrixAuthPluginTest
```
=> Adapt to dialog changes in matrix-auth 3.2.3

src/test/java/plugins/OicAuthPluginTest.java
https://issues.jenkins.io/browse/JENKINS-74005
Switched how Log in link was obtained, so now it looks for the href attribute, which will always be the same regardless the button text changes.
Runned ATHs with no problem
=> [JENKINS-74005] Obtaining login button via href instead of text

Jenkinsfile, src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java, src/main/java/org/jenkinsci/test/acceptance/po/GlobalSecurityConfig.java
Opt-in to enable CSP in restrictive mode
Enabled on weekly line in `Jenkinsfile`
Can be enabled on LTS line when it is based on 2.480 or later
Can be enabled in CloudBees when CloudBees is ready for it
Can be enabled in plugin test suites at the convenience of plugin maintainers
=> Run ATH with CSP

src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java, src/main/java/org/jenkinsci/test/acceptance/plugins/csp/ContentSecurityPolicyReport.java, src/test/java/core/PublisherOrderTest.java, src/test/java/plugins/ArtifactoryPluginTest.java, src/test/java/plugins/JobDslPluginTest.java, src/test/java/plugins/MailerPluginTest.java, src/test/java/plugins/MatrixAuthPluginTest.java, src/test/java/plugins/PlainCredentialsBindingTest.java, src/test/java/plugins/ScriptSecurityPluginTest.java, src/test/java/plugins/SshSlavesPluginTest.java
Building on #1743, when `csp.rule` is defined, we not only enable CSP in restrictive mode, but also we verify at the end of each test that there are no violations logged on the report page. Currently skipped for two plugins that have known violations:
- `ArtifactoryPluginTest` (tracked in JENKINS-74047)
- `SubversionPluginTest` (tracked in JENKINS-73900)
=> Enforce that there are no CSP violations when `csp.rule` is defined

pom.xml
Released 30 Oct 2024.
Changelog:
* https://www.jenkins.io/changelog-stable/2.479.1/
Upgrade guide:
* https://www.jenkins.io/doc/upgrade-guide/2.479/
Release checklist:
* https://github.com/jenkins-infra/release/issues/606
Relying on ci.jenkins.io to perform the testing.
=> Use Jenkins 2.479.1 in LTS profile

.github/renovate.json
This repository has good test coverage and I can't remember a single time there's been a green build for a dependency here that I wouldn't merge myself, so save maintainers a bit of time by automating this.
If a PR is reverted then it won't go into and auto merge loop and renovate will disable automerge for that dep
=> Enable automerge for renovate PRs

src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
Title:
Removed workaround for JENKINS-73900 in CspRule.java
Description:
This pull request addresses an outdated workaround for JENKINS-73900 within the CspRule.java file in the acceptance test harness.
Changes:
Removed the conditional code that was bypassing CSP report checks specifically for SubversionPluginTest.
With this workaround removed, SubversionPluginTest will now be subject to the same CSP checks as other tests in CspRule.java.
Issue Reference:
Fixes JENKINS-73900
Testing:
Verified that the tests run successfully after the removal.
Ran mvn test to confirm that the modification does not introduce new errors.
Additional Notes:
Maintainers may wish to ensure compatibility with other plugins, as this change affects SubversionPluginTest specifically.
Fixes #1810
=> Remove workaround for JENKINS-73900 in `CspRule`

src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java, src/main/java/org/jenkinsci/test/acceptance/plugins/csp/ContentSecurityPolicyReport.java
see https://github.com/jenkinsci/csp-plugin/pull/16
Tested it works if no CSP violations, haven't managed to test with something with violations, artifactory plugin test won't run on my machine, artifactory just won't start.
=> Adapt to new CSP design

src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java
=> Remove JENKINS-74890 workaround

src/main/java/org/jenkinsci/test/acceptance/junit/DiagnosticRule.java
Temporary files are created with permissions `600`, differing from defined umask. For the screenshot file that is later attached as diagnostic, this can cause permission issues in some environments.
Tested by arbitrary failing a test and checking permissions set on resulting `screenshot.png` that can be found under `target/diagnostics/{testName}/screenshot.png`.
In my case `644` instead of `600`.
=> Avoid using a temporary file to store screenshot after a test failure

src/main/java/org/jenkinsci/test/acceptance/plugins/scriptler/ScriptResult.java, src/main/java/org/jenkinsci/test/acceptance/po/Jenkins.java
Scriptler 390 and above use "(built-in)" to refer to the built-in node instead of "(controller)" or "(master)" (jenkinsci/scriptler-plugin#128). Update the test harness to check for any of these terms.
The adaptation code can be simplified once older versions of the Scriptler plugin are no longer being tested.
Tested the Scriptler unit tests locally.
=> JENKINS-74974 - Adapt Scriptler test to use preferred terminology

Jenkinsfile
As described in https://github.com/jenkins-infra/helpdesk/issues/4316#issuecomment-2618309804, if the [VM agent](https://github.com/jenkinsci/acceptance-test-harness/blob/ea72d04b39a3e4e9ad1d26a4010864821a923fc3/Jenkinsfile#L125) does set the `JAVA_HOME` environment variable, then it is passed to the [Docker agent container](https://github.com/jenkinsci/acceptance-test-harness/blob/ea72d04b39a3e4e9ad1d26a4010864821a923fc3/Jenkinsfile#L131) which is the default behavior of the docker workflow plugin:
```bash
docker run -t -d -u 1001:1001 --group-add 999 -v /var/run/docker.sock:/var/run/docker.sock -v /home/jenkins/agent/workspace/ath_master/target/ath-reports:/reports:rw --shm-size 2g -w /home/jenkins/agent/workspace/ath_master -v …
```
=> Ensure that Jenkins node setup does not influence the container Java setup

src/test/java/plugins/JiraPluginTest.java
Atlassian has removed one or more of the necessary artifacts from their public repository.  Since Jira Server is no longer supported and we were relying on a very, very old version of Jira, let's ignore this test.
Issue is described in detail in:
* https://github.com/jenkinsci/acceptance-test-harness/issues/1910
The docker build process cannot download:
https://marketplace.atlassian.com/rest/1.0/plugins/atlassian-plugin-sdk-deb
Since Atlassian no longer supports Jira Server, they are unlikely to provide any fix for the installation of that very old Jira version.
The Docker container build failure is visible on ci.jenkins.io and on my local Debian installation.
The [contributing guide](https://github.com/jenkinsci/acceptance-test-harness/blob/master/docs/CONTRIBUTING.md#dealing-with-fragile …
=> Ignore JiraPluginTest because Jira test container does not build

pom.xml
Fixes 6104383882a417c420913370d57bb60e79e95a14
Amends https://github.com/jenkinsci/acceptance-test-harness/pull/1958
Confirmed that a test passes from the Maven command line after the change.
=> Use guava 33.4.7-jre instead of the android version

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/junit/CspRule.java, src/main/java/org/jenkinsci/test/acceptance/po/CapybaraPortingLayerImpl.java, src/test/java/core/FormValidationTest.java, src/test/java/core/PublisherOrderTest.java, src/test/java/plugins/ArtifactoryPluginTest.java, src/test/java/plugins/MailerPluginTest.java, src/test/java/plugins/PlainCredentialsBindingTest.java, src/test/java/plugins/SshSlavesPluginTest.java
#1657 introduced a fragile workaround in `FormValidationTest` (moving from `jenkins.open()` to clicking on a breadcrumb link), and that fragile workaround was copied and pasted in more places in #1749. That code was then adjusted even further in #1917, which is still causing some problems for OEMs that have not adopted the Jenkins header change. This PR does some code cleanup:
- Restores `FormValidationTest` to the less fragile way it was before #1657, effectively reimplementing #1657 to use BiDi to dismiss the alert. This removes the fragility associated with `#jenkins-head-icon`.
- Adds this new BiDi implementation to `CspRule`, avoiding the need for copypasta in a bunch of tests and saving test execution time when `CspRule` is disabled.
The net result is a strict improvement over the …
=> Clean up `beforeunload` user prompt handling

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Other cases in this repository use SystemUtils.IS_OS_WINDOWS.  No need to create a private method when SystemUtils is already in use.
https://github.com/jenkinsci/acceptance-test-harness/pull/1987#discussion_r2072465477
Confirmed that `mvn compile` compiles successfully;
=> Use consistent Windows detection conditional

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
@jtnord notes that the BiDi support added in #1657 won't work with `RemoteWebDriver`:
> `RemoteWebdriver` doesn't know if it is BiDi or not (it's a runtime thing) so it doesn't implement the interfaces. […] IIRC you will need to wrap it with a call to `Augmenter#augment`
This PR does exactly that.
Reproduced BiDi failures with `FormValidationTest` and `RemoteWebDriver`; could no longer reproduce after this PR.
=> Support BiDi in `RemoteWebDriver`

vars.sh
Porting https://github.com/jenkinsci/acceptance-test-harness/blob/a429dbeab2db40df7cb5bfbc084eece035c48e1f/vars.cmd to Unix to allow for `RemoteWebDriver` testing on Unix platforms.
=> Port `vars.cmd` to Unix

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
#457 added a workaround. I wonder if it is still necessary or if it can be deleted.
CI build, which does include `CspRule`.
=> Remove workaround added in #457

src/main/java/org/jenkinsci/test/acceptance/recorder/HarRecorder.java
Pending #1998, disable HAR recording by default. In local testing I found it not to fail outright but rather to introduce instability into WebDriver BiDi builds using WebSocket, which is even worse than failing outright. When #1998 is implemented, it can be re-enabled.
Observed non-fatal timeouts and stack traces from the BrowserUp Proxy library when running the test suite locally against a remote Selenium Grid container without this PR; they went away after this PR.
=> Disable HAR recording by default

docs/BROWSER.md
These images have been archived; use the non-deprecated equivalents.
=> Stop using outdated `-debug` images in documentation

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, vars.cmd, vars.sh
Use the correct environment variables as documented in https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#setting-screen-resolution and also update the Java code to match these dimensions.
=> Use consistent screen dimensions

.github/renovate.json
The regex we use for Renovate happens to work with `vars.sh`, so let's keep that up-to-date with Renovate too. Updating the regex to work with `vars.cmd` is left as an exercise for the reader.
=> Automatically update `vars.sh` with Renovate

src/main/java/org/jenkinsci/test/acceptance/plugins/audit_trail/AuditTrailLogger.java, src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserGlobalConfig.java, src/main/java/org/jenkinsci/test/acceptance/selenium/UselessFileDetectorReplacement.java
Extracted from #2010. Fixes two problems:
1. We were using `UselessFileDetectorReplacement` in one place where it was needed, but not two other places where it was also needed. Fixed by using it in those two other places.
2. Even in the place where we were using it, it wasn't actually working, because the `RemoteWebDriver` instance was an anonymous ByteBuddy wrapper subclass, not the actual `RemoteWebDriver` class itself. Fixed by using `instanceof`.
#2010 is now passing.
=> Fix `UselessFileDetectorReplacement`

ci.sh, docker-compose.yml, src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java, src/main/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRule.java, src/test/java/org/jenkinsci/test/acceptance/recorder/TestRecorderRuleTest.java
Fixes #1041
In #2010 we observed that Monte was crashing Selenium on Java 17, so we turned off recording there. This PR removes that workaround and re-enables recording everywhere by moving from Monte to Selenium's native recording system. This also fixes #1041.
See the docs here: https://github.com/SeleniumHQ/docker-selenium?tab=readme-ov-file#video-recording
This PR does not remove Monte, since CloudBees is still using it. But when `VIDEO_FOLDER` is set we now use the native Selenium system. This triggers writing out a recording when the Selenium WebDriver is closed, which we then fish out and move to where Monte would have placed it. Once CloudBees switches to this new system, the Monte code can be deleted.
Ensured that the videos could be opened on a macOS system.
Tested with failing …
=> Record videos with Selenium instead of Monte

src/main/java/org/jenkinsci/test/acceptance/FallbackConfig.java
Pending #2025, at least get the Chrome build to start by consolidating the various Chrome configuration paths into one method, like Firefox, and enabling BiDi there. This also switches us to `RemoteWebDriver.builder` which is slightly more readable and avoids the need for `org.openqa.selenium.remote.Augmenter`.
Extracted from #2018.
=> Clean up Chrome support in `FallbackConfig`

src/main/resources/ath-container/Dockerfile
```
=> WARN: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 7)                                                                                                                0.0s
=> WARN: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 50)                                                                                                               0.0s
=> WARN: LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 67)                                                                                                               0.0s
```
CI build
=> Fix Docker build warnings

ath-container.sh, build-image.sh, ci.sh, docker-compose.yml, src/main/java/org/jenkinsci/test/acceptance/plugins/logparser/LogParserPublisher.java, src/test/java/plugins/ConfigurationAsCodeTest.java
Unlike Ubuntu Linux, Fedora uses SELinux instead of AppArmor, which requires the ":Z" option when bind-mounting local volumes into the container. From the man page:
> To change a label in the container context, you can add either of two suffixes :z or :Z to the volume mount. These suffixes tell Docker to relabel file objects on the shared volumes. The z option tells Docker that two containers share the volume content. As a result, Docker labels the content with a shared content label. Shared volume labels allow all containers to read/write content.  The Z option tells Docker to label the content with a private unshared label. Only the current container can use a private volume.
Using the :Z option on an Ubuntu system with Docker does not cause harm, but it is effectively ignored since …
=> Support Fedora Linux
